// Package unicodepin renders the Unicode tables pkg/generator decides Go
// identifiers and struct-tag names by, from the unicode package of the Go
// toolchain it runs under.
//
// Why a copy at all: whether a rune may appear in a Go identifier, and whether
// encoding/json accepts it in a struct tag's name, is decided by the unicode
// tables of the toolchain that *compiles* the generated code, and generated code
// is compiled by every Go from the go.mod minimum to the current release. A
// letter Unicode added after the minimum's version is a letter to a newer Go and
// an illegal character to the minimum -- so a generator reading its own tables,
// running on a newer Go, emitted identifiers the minimum refuses to compile, and
// tags whose names the minimum's encoding/json silently ignored. The same for a
// case mapping Unicode added later: a newer Go uppercases a letter the minimum
// maps to itself, onto a letter the minimum does not have.
//
// So the generator reads tables pinned to the oldest supported Go's Unicode
// version -- rendered by this package, under that toolchain, into
// pkg/generator/unicode_tables.go -- and a test holds the file to the renderer
// whenever the toolchain running it has that Unicode version.
package unicodepin

import (
	"bytes"
	"fmt"
	"go/format"
	"unicode"
)

// Render returns the Go source of pkg/generator/unicode_tables.go, built from
// the running toolchain's unicode package.
func Render() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by pkg/generator/internal/unicodepin/gen; DO NOT EDIT.\n\n")
	b.WriteString("package generator\n\n")
	b.WriteString("import \"unicode\"\n\n")
	fmt.Fprintf(&b, "// pinnedUnicodeVersion is the Unicode version the tables below were\n// rendered from: that of the oldest Go the generated code supports.\n")
	fmt.Fprintf(&b, "const pinnedUnicodeVersion = %q\n\n", unicode.Version)
	for _, t := range []struct {
		name, doc string
		table     *unicode.RangeTable
	}{
		{"pinnedLetter", "Unicode letters (category L), which a Go identifier may use anywhere", unicode.Letter},
		{"pinnedUpper", "upper-case letters (Lu), which an exported Go identifier starts with", unicode.Upper},
		{"pinnedLower", "lower-case letters (Ll)", unicode.Lower},
		{"pinnedDigit", "decimal digits (Nd), which a Go identifier may use after its first rune", unicode.Digit},
	} {
		fmt.Fprintf(&b, "// %s holds the %s.\n", t.name, t.doc)
		fmt.Fprintf(&b, "var %s = &unicode.RangeTable{\n", t.name)
		if len(t.table.R16) > 0 {
			b.WriteString("\tR16: []unicode.Range16{\n")
			for _, r := range t.table.R16 {
				fmt.Fprintf(&b, "\t\t{Lo: %#04x, Hi: %#04x, Stride: %d},\n", r.Lo, r.Hi, r.Stride)
			}
			b.WriteString("\t},\n")
		}
		if len(t.table.R32) > 0 {
			b.WriteString("\tR32: []unicode.Range32{\n")
			for _, r := range t.table.R32 {
				fmt.Fprintf(&b, "\t\t{Lo: %#x, Hi: %#x, Stride: %d},\n", r.Lo, r.Hi, r.Stride)
			}
			b.WriteString("\t},\n")
		}
		fmt.Fprintf(&b, "\tLatinOffset: %d,\n}\n\n", t.table.LatinOffset)
	}
	b.WriteString("// pinnedCaseRanges is the case mapping of the same version.\n")
	b.WriteString("var pinnedCaseRanges = []unicode.CaseRange{\n")
	for _, c := range unicode.CaseRanges {
		fmt.Fprintf(&b, "\t{Lo: %#04x, Hi: %#04x, Delta: [unicode.MaxCase]rune{%s, %s, %s}},\n",
			c.Lo, c.Hi, delta(c.Delta[unicode.UpperCase]), delta(c.Delta[unicode.LowerCase]), delta(c.Delta[unicode.TitleCase]))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// delta spells one CaseRange delta, naming the UpperLower sentinel.
func delta(d rune) string {
	if d == unicode.UpperLower {
		return "unicode.UpperLower"
	}
	return fmt.Sprintf("%d", d)
}
