package emitter

import (
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/mgilbir/schemagen/pkg/generator"
)

// containsNormalized checks whether s contains sub after collapsing runs of
// whitespace to a single space. This accounts for gofmt alignment.
func containsNormalized(s, sub string) bool {
	normalize := func(in string) string {
		var b strings.Builder
		inSpace := false
		for _, r := range in {
			if r == ' ' || r == '\t' {
				if !inSpace {
					b.WriteByte(' ')
					inSpace = true
				}
			} else {
				b.WriteRune(r)
				inSpace = false
			}
		}
		return b.String()
	}
	return strings.Contains(normalize(s), normalize(sub))
}

func mustNew(t *testing.T) *Emitter {
	t.Helper()
	e, err := New()
	if err != nil {
		t.Fatalf("New() error: %v", err)
	}
	return e
}

func TestEmitStructDef(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name:        "Person",
				Description: "A person object.",
				Fields: []generator.FieldDef{
					{
						Name:      "Name",
						JSONName:  "name",
						Type:      &generator.PrimitiveType{Name: "string"},
						OmitEmpty: false,
						Required:  true,
					},
					{
						Name:        "Age",
						JSONName:    "age",
						Type:        &generator.PrimitiveType{Name: "int64"},
						OmitEmpty:   true,
						Description: "The person's age.",
					},
					{
						Name:      "Addresses",
						JSONName:  "addresses",
						Type:      &generator.ArrayType{ItemType: &generator.NamedType{Name: "Address"}},
						OmitEmpty: true,
					},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	// Check package
	if !strings.Contains(src, "package model") {
		t.Error("expected 'package model' in output")
	}

	// Check generated comment
	if !strings.Contains(src, "Code generated by schemagen. DO NOT EDIT.") {
		t.Error("expected generated code comment")
	}

	// Check struct definition
	if !strings.Contains(src, "type Person struct") {
		t.Error("expected 'type Person struct'")
	}

	// Check description
	if !strings.Contains(src, "// Person - A person object.") {
		t.Error("expected description comment")
	}

	// Check field with no omitempty
	if !strings.Contains(src, `json:"name"`) {
		t.Errorf("expected json tag without omitempty for Name field, got:\n%s", src)
	}

	// Check field with omitempty
	if !strings.Contains(src, `json:"age,omitempty"`) {
		t.Errorf("expected json tag with omitempty for Age field, got:\n%s", src)
	}

	// Check field description
	if !strings.Contains(src, "// The person's age.") {
		t.Error("expected field description comment")
	}

	// Check array type
	if !strings.Contains(src, "[]Address") {
		t.Errorf("expected []Address type, got:\n%s", src)
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitEnumDef(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		TypeDefs: []generator.TypeDef{
			&generator.EnumDef{
				Name:        "Color",
				BaseType:    &generator.PrimitiveType{Name: "string"},
				Description: "Supported colors.",
				Values: []generator.EnumValue{
					{Name: "ColorRed", Value: "red"},
					{Name: "ColorGreen", Value: "green"},
					{Name: "ColorBlue", Value: "blue"},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	if !strings.Contains(src, "type Color string") {
		t.Errorf("expected 'type Color string', got:\n%s", src)
	}

	if !containsNormalized(src, `ColorRed Color = "red"`) {
		t.Errorf("expected ColorRed constant, got:\n%s", src)
	}

	if !containsNormalized(src, `ColorGreen Color = "green"`) {
		t.Errorf("expected ColorGreen constant, got:\n%s", src)
	}

	if !strings.Contains(src, "// Color - Supported colors.") {
		t.Error("expected description comment")
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitAliasDef(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		TypeDefs: []generator.TypeDef{
			&generator.AliasDef{
				Name:        "Metadata",
				Underlying:  &generator.MapType{KeyType: &generator.PrimitiveType{Name: "string"}, ValueType: &generator.PrimitiveType{Name: "any"}},
				Description: "Arbitrary metadata.",
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	if !strings.Contains(src, "type Metadata map[string]any") {
		t.Errorf("expected 'type Metadata map[string]any', got:\n%s", src)
	}

	if !strings.Contains(src, "// Metadata - Arbitrary metadata.") {
		t.Error("expected description comment")
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitMultipleTypeDefs(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"},
			{Path: "time", Alias: ""},
		},
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Config",
				Fields: []generator.FieldDef{
					{
						Name:     "Host",
						JSONName: "host",
						Type:     &generator.PrimitiveType{Name: "string"},
					},
					{
						Name:      "Port",
						JSONName:  "port",
						Type:      &generator.PrimitiveType{Name: "int64"},
						OmitEmpty: true,
					},
				},
			},
			&generator.EnumDef{
				Name:     "LogLevel",
				BaseType: &generator.PrimitiveType{Name: "string"},
				Values: []generator.EnumValue{
					{Name: "LogLevelDebug", Value: "debug"},
					{Name: "LogLevelInfo", Value: "info"},
				},
			},
			&generator.AliasDef{
				Name:       "Tags",
				Underlying: &generator.ArrayType{ItemType: &generator.PrimitiveType{Name: "string"}},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	// All three types should appear
	if !strings.Contains(src, "type Config struct") {
		t.Error("expected Config struct")
	}
	if !strings.Contains(src, "type LogLevel string") {
		t.Error("expected LogLevel enum")
	}
	if !strings.Contains(src, "type Tags []string") {
		t.Error("expected Tags defined type")
	}

	// Imports
	if !strings.Contains(src, `"encoding/json"`) {
		t.Errorf("expected encoding/json import, got:\n%s", src)
	}
	if !strings.Contains(src, `"time"`) {
		t.Errorf("expected time import, got:\n%s", src)
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitOutputIsValidGo(t *testing.T) {
	e := mustNew(t)

	// Emit a complex file and verify go/format.Source doesn't fail
	// (which means it's syntactically valid Go)
	f := &generator.File{
		PackageName: "example",
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Widget",
				Fields: []generator.FieldDef{
					{Name: "ID", JSONName: "id", Type: &generator.PrimitiveType{Name: "string"}},
					{Name: "Count", JSONName: "count", Type: &generator.PrimitiveType{Name: "int64"}, OmitEmpty: true},
					{Name: "Labels", JSONName: "labels", Type: &generator.MapType{
						KeyType:   &generator.PrimitiveType{Name: "string"},
						ValueType: &generator.PrimitiveType{Name: "string"},
					}},
					{Name: "Parent", JSONName: "parent", Type: &generator.PointerType{
						Inner: &generator.NamedType{Name: "Widget"},
					}, OmitEmpty: true},
				},
			},
			&generator.EnumDef{
				Name:     "Status",
				BaseType: &generator.PrimitiveType{Name: "int64"},
				Values: []generator.EnumValue{
					{Name: "StatusActive", Value: 1},
					{Name: "StatusInactive", Value: 0},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	// Pointer type
	if !strings.Contains(src, "*Widget") {
		t.Errorf("expected *Widget pointer type, got:\n%s", src)
	}

	// Int enum values
	if !containsNormalized(src, "StatusActive Status = 1") {
		t.Errorf("expected StatusActive = 1, got:\n%s", src)
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitStructWithOneOf(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Event",
				Fields: []generator.FieldDef{
					{Name: "ID", JSONName: "id", Type: &generator.PrimitiveType{Name: "string"}},
				},
				OneOfs: []generator.OneOfDef{
					{
						InterfaceName: "isEvent_Payload",
						FieldName:     "Payload",
						JSONName:      "payload",
						Variants: []generator.OneOfVariant{
							{WrapperName: "Event_Click", FieldName: "Click", Type: &generator.NamedType{Name: "ClickPayload"}},
							{WrapperName: "Event_View", FieldName: "View", Type: &generator.NamedType{Name: "ViewPayload"}},
						},
					},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	if !strings.Contains(src, "Payload isEvent_Payload") {
		t.Errorf("expected OneOf field 'Payload isEvent_Payload', got:\n%s", src)
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitEmptyFile(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "empty",
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)

	if !strings.Contains(src, "package empty") {
		t.Errorf("expected 'package empty', got:\n%s", src)
	}

	// Should not have import block
	if strings.Contains(src, "import") {
		t.Errorf("expected no import block for empty file, got:\n%s", src)
	}

	t.Logf("Output:\n%s", src)
}

func TestEmitValidationCapabilityForHybridRuntimeFeatures(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "github.com/mgilbir/schemagen/pkg/validationruntime"},
		},
		ValidationCapability: generator.ValidationCapability{
			Mode:            generator.ValidationModeHybrid,
			RequiresRuntime: true,
			RuntimeFeatures: []generator.ValidationFeature{generator.ValidationFeatureDynamicRef},
			ResourceCount:   2,
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)
	for _, want := range []string{
		`"github.com/mgilbir/schemagen/pkg/validationruntime"`,
		`const SchemagenValidationMode = "hybrid"`,
		`func SchemagenValidationRuntimeFeatures() []string`,
		`func SchemagenValidationCapability() validationruntime.Capability`,
		`RuntimeFeatures: []validationruntime.Feature{validationruntime.Feature("$dynamicRef")}`,
		`ResourceCount:   2`,
	} {
		if !containsNormalized(src, want) {
			t.Errorf("expected generated validation capability snippet %q, got:\n%s", want, src)
		}
	}
}

func TestEmitNotSchemaBranchesWithSimpleValidations(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"},
			{Path: "fmt"},
			{Path: "math"},
			{Path: "unicode/utf8"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.NotSchemaDef{
				Name: "Root",
				NotBranches: []generator.NotSchemaBranch{
					{
						Types: []string{"integer"},
						Validations: []generator.ValidationRule{
							{RuleType: "minimum", Value: 10.0},
						},
					},
					{
						Types: []string{"string"},
						Validations: []generator.ValidationRule{
							{RuleType: "minLength", Value: 3},
						},
					},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}

	src := string(out)
	for _, want := range []string{
		`if _num < 10`,
		`utf8.RuneCountInString(_s) < 3`,
		`return fmt.Errorf("not: value matches forbidden branch`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("expected generated not-schema validation snippet %q, got:\n%s", want, src)
		}
	}
}

func TestFuncMapGoType(t *testing.T) {
	tests := []struct {
		input    generator.GoType
		expected string
	}{
		{&generator.PrimitiveType{Name: "string"}, "string"},
		{&generator.PrimitiveType{Name: "int64"}, "int64"},
		{&generator.NamedType{Name: "Foo"}, "Foo"},
		{&generator.NamedType{Name: "Foo", Pointer: true}, "*Foo"},
		{&generator.ArrayType{ItemType: &generator.PrimitiveType{Name: "string"}}, "[]string"},
		{&generator.MapType{KeyType: &generator.PrimitiveType{Name: "string"}, ValueType: &generator.PrimitiveType{Name: "any"}}, "map[string]any"},
		{&generator.PointerType{Inner: &generator.NamedType{Name: "Bar"}}, "*Bar"},
	}

	for _, tt := range tests {
		got := goTypeFunc(tt.input)
		if got != tt.expected {
			t.Errorf("goTypeFunc(%T) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}

func TestFuncMapEnumValue(t *testing.T) {
	tests := []struct {
		input    any
		expected string
	}{
		{"hello", `"hello"`},
		{42, "42"},
		{int64(100), "100"},
		{3.14, "3.14"},
		{float64(5), "5"},
	}

	for _, tt := range tests {
		got := enumValueFunc(tt.input)
		if got != tt.expected {
			t.Errorf("enumValueFunc(%v) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}

func TestFuncMapReceiverName(t *testing.T) {
	tests := []struct {
		input, expected string
	}{
		{"Person", "p"},
		{"Config", "c"},
		{"", "x"},
	}

	for _, tt := range tests {
		got := receiverNameFunc(tt.input)
		if got != tt.expected {
			t.Errorf("receiverNameFunc(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}

func TestFuncMapLowerFirst(t *testing.T) {
	tests := []struct {
		input, expected string
	}{
		{"Hello", "hello"},
		{"ABC", "aBC"},
		{"", ""},
		{"a", "a"},
	}

	for _, tt := range tests {
		got := lowerFirstFunc(tt.input)
		if got != tt.expected {
			t.Errorf("lowerFirstFunc(%q) = %q, want %q", tt.input, got, tt.expected)
		}
	}
}

func TestNormalizeECMA262PatternEscapedClassIdentity(t *testing.T) {
	input := `^[A-Za-z0-9_\-\.\:]+$`
	got := normalizeECMA262Pattern(input)
	want := `^[A-Za-z0-9_\x2d\.\x3a]+$`
	if got != want {
		t.Fatalf("normalizeECMA262Pattern(%q) = %q, want %q", input, got, want)
	}
}

func TestNormalizeECMA262PatternLiteralClosingBracketInClass(t *testing.T) {
	input := `^[\]\:]+$`
	got := normalizeECMA262Pattern(input)
	want := `^[\]\x3a]+$`
	if got != want {
		t.Fatalf("normalizeECMA262Pattern(%q) = %q, want %q", input, got, want)
	}
}

func TestGeneratedPatternValidationAcceptsEscapedClassIdentity(t *testing.T) {
	e := mustNew(t)
	f := &generator.File{
		PackageName: "main",
		Imports: []generator.Import{
			{Path: "github.com/mgilbir/goecma262", Alias: "ecma262"},
			{Path: "github.com/mgilbir/goecma262/flags", Alias: "ecmaflags"},
			{Path: "fmt"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.AliasDef{
				Name:       "Name",
				Underlying: &generator.PrimitiveType{Name: "string"},
				Validations: []generator.ValidationRule{
					{RuleType: "pattern", Value: `^[A-Za-z0-9_\-\.\:]+$`},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)
	if !strings.Contains(src, `^[A-Za-z0-9_\\x2d\\.\\x3a]+$`) {
		t.Fatalf("expected normalized pattern in generated code, got:\n%s", src)
	}

	tmp := t.TempDir()
	if err := os.WriteFile(filepath.Join(tmp, "types.go"), out, 0o644); err != nil {
		t.Fatalf("write types.go: %v", err)
	}
	mainSrc := `package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	var v Name
	if err := json.Unmarshal([]byte(` + strconv.Quote(`"wake_up_time"`) + `), &v); err != nil {
		panic(err)
	}
	if err := v.Validate(); err != nil {
		panic(err)
	}
	fmt.Println("ok")
}
`
	if err := os.WriteFile(filepath.Join(tmp, "main.go"), []byte(mainSrc), 0o644); err != nil {
		t.Fatalf("write main.go: %v", err)
	}
	goMod := "module patternrepro\n\ngo 1.23\n\nrequire github.com/mgilbir/goecma262 v0.0.0-20260219184840-8bfa4bb752b0\n"
	if err := os.WriteFile(filepath.Join(tmp, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	goSum := "github.com/mgilbir/goecma262 v0.0.0-20260219184840-8bfa4bb752b0 h1:g5uVjex1bABu72M6R0A//gQDoVXPSatqP50yZDX5wUQ=\n" +
		"github.com/mgilbir/goecma262 v0.0.0-20260219184840-8bfa4bb752b0/go.mod h1:wQvOAFchLrhVSiF4JsSzH+yE6eLpc8gOBrvpuahNucI=\n"
	if err := os.WriteFile(filepath.Join(tmp, "go.sum"), []byte(goSum), 0o644); err != nil {
		t.Fatalf("write go.sum: %v", err)
	}

	cmd := exec.Command("go", "run", ".")
	cmd.Dir = tmp
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated code failed: %v\n%s", err, string(output))
	}
	if programOutput(output) != "ok" {
		t.Fatalf("output = %q, want ok", programOutput(output))
	}
}

// programOutput returns the output of a generated test program with Go
// toolchain progress lines removed. A cold module cache makes the throwaway
// module's build print "go: downloading ..." onto the same stream as the
// program's own output, which would fail an exact-match assertion for reasons
// that have nothing to do with the generated code.
func programOutput(out []byte) string {
	lines := strings.Split(string(out), "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "go: ") {
			continue
		}
		kept = append(kept, line)
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}

func TestEmitMultilineDescriptions(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name:        "Config",
				Description: "First line.\nSecond line.",
				Fields: []generator.FieldDef{
					{
						Name:        "Value",
						JSONName:    "value",
						Description: "Field first line.\nField second line.",
						Type:        &generator.PrimitiveType{Name: "string"},
					},
				},
			},
		},
	}

	// Emit runs the output through go/format, so a description breaking out
	// of its comment fails here.
	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)
	if !strings.Contains(src, "// Config - First line.\n// Second line.") {
		t.Errorf("type description not continued as a comment:\n%s", src)
	}
	if !containsNormalized(src, "// Field second line.") {
		t.Errorf("field description not continued as a comment:\n%s", src)
	}
}

// TestEmitBigIntAliasOneOfVariants pins the emitter half of a defect the
// co-generation harness found. The generator has always filled a
// BigIntAliasDef's AnyOfVariants and OneOfVariants, and the big-int Validate
// template rendered Validations and nothing else -- so under --big-int
// {"type":"integer","oneOf":[{"minimum":10},{"maximum":5}]} emitted a Validate
// that checked nothing and accepted every integer, including 7, which satisfies
// neither branch.
//
// The plain alias template has rendered both all along; this is the same
// counting, through big.Float so an integer past int64 is compared at full
// precision rather than through float64.
func TestEmitBigIntAliasOneOfVariants(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"},
			{Path: "fmt"},
			{Path: "math"},
			{Path: "math/big"},
			{Path: "strings"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.BigIntAliasDef{
				Name: "Windowed",
				OneOfVariants: [][]generator.ValidationRule{
					{{RuleType: "minimum", Value: 10}},
					{{RuleType: "maximum", Value: 5}},
				},
				AnyOfVariants: [][]generator.ValidationRule{
					{{RuleType: "multipleOf", Value: 3}},
					{{RuleType: "exclusiveMinimum", Value: 100}},
				},
			},
		},
	}

	// Emit runs go/format, so a template that produced uncompilable Go for the
	// big-int receiver fails here rather than in a user's build.
	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		"oneOf: exactly one variant must be satisfied.",
		"if oneOfCount != 1 {",
		"anyOf: at least one variant must be satisfied.",
		"value does not match any anyOf variant",
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("big-int Validate is missing %q:\n%s", want, src)
		}
	}
	// Each branch bound has to reach the emitted comparison, at big.Float
	// precision rather than through float64.
	for _, want := range []string{
		`_limit.SetString("10")`,
		`_limit.SetString("5")`,
		`_divisor.SetString("3")`,
		`_limit.SetString("100")`,
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("big-int Validate is missing the branch bound %q:\n%s", want, src)
		}
	}
	if strings.Contains(src, "float64(w)") {
		t.Fatalf("big-int Validate compared through float64, losing precision past int64:\n%s", src)
	}
}

// TestEmitOneOfUnionValidateDispatch is the emitter half of issue #61: the
// owner's Validate never descended into a oneOf union field, so an object
// variant's nested constraints were never applied. The generator half -- which
// variants are marked Validatable -- is pinned in
// pkg/generator/generator_test.go.
//
// Only Payload is marked Validatable here. Text is a scalar variant whose
// wrapper holds a plain Go string, so a dispatch case for it would emit
// _oneOfSel.Text.Validate() on a string and Emit's go/format pass would reject
// the file.
func TestEmitOneOfUnionValidateDispatch(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"},
			{Path: "fmt"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Envelope",
				OneOfs: []generator.OneOfDef{{
					InterfaceName: "isEnvelope_Body",
					FieldName:     "Body",
					JSONName:      "body",
					Variants: []generator.OneOfVariant{
						{
							WrapperName: "Envelope_Payload",
							FieldName:   "Payload",
							Type:        &generator.NamedType{Name: "Payload", Pointer: true},
							Validatable: true,
						},
						{
							WrapperName: "Envelope_Text",
							FieldName:   "Text",
							Type:        &generator.PrimitiveType{Name: "string"},
						},
					},
				}},
			},
			&generator.StructDef{Name: "Payload"},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		"switch _oneOfSel := e.Body.(type) {",
		"case *Envelope_Payload:",
		"if _oneOfSel.Payload != nil {",
		"if err := _oneOfSel.Payload.Validate(); err != nil {",
		`return fmt.Errorf("body.%w", err)`,
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("Envelope.Validate is missing %q:\n%s", want, src)
		}
	}
	// The scalar variant must not be dispatched to. Asserting on the absence of
	// the case is what keeps the Validatable gate honest: without it the
	// emitted file would not compile, and Emit's format pass would say so.
	if strings.Contains(src, "case *Envelope_Text:") {
		t.Fatalf("Envelope.Validate dispatches to a scalar variant, whose type has no Validate:\n%s", src)
	}
}

// TestEmitOneOfUnionWithNoValidatableVariantsEmitsNoSwitch guards the gate that
// decides whether the dispatch is written at all. A type switch with no cases
// binds _oneOfSel and never reads it, which does not compile -- so a union of
// nothing but scalars has to emit nothing rather than an empty switch.
func TestEmitOneOfUnionWithNoValidatableVariantsEmitsNoSwitch(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"},
			{Path: "fmt"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Envelope",
				OneOfs: []generator.OneOfDef{{
					InterfaceName: "isEnvelope_Body",
					FieldName:     "Body",
					JSONName:      "body",
					Variants: []generator.OneOfVariant{
						{WrapperName: "Envelope_String", FieldName: "String", Type: &generator.PrimitiveType{Name: "string"}},
						{WrapperName: "Envelope_Integer", FieldName: "Integer", Type: &generator.PrimitiveType{Name: "int64"}},
					},
				}},
			},
		},
	}

	// Emit runs go/format, so an empty type switch fails here rather than in a
	// user's build.
	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	if strings.Contains(string(out), "_oneOfSel") {
		t.Fatalf("a union with no validatable variant still emitted a dispatch:\n%s", out)
	}
}

// oneOfNarrowingFile builds a two-variant union whose selection is decided by
// required-key presence, which is the shape issue #81 is about. The second
// variant's judgement is the parameter: FullyChecked when everything it says is
// already tested by selection, and neither that nor Validatable when it is not.
func oneOfNarrowingFile(secondFullyChecked bool) *generator.File {
	return &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"},
			{Path: "fmt"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name:           "Envelope",
				NeedsUnmarshal: true,
				OneOfs: []generator.OneOfDef{{
					InterfaceName: "isEnvelope_Body",
					FieldName:     "Body",
					JSONName:      "body",
					Variants: []generator.OneOfVariant{
						{
							WrapperName:    "Envelope_Payload",
							FieldName:      "Payload",
							Type:           &generator.NamedType{Name: "Payload", Pointer: true},
							RequiredFields: []string{"x"},
							Validatable:    true,
						},
						{
							WrapperName:    "Envelope_Any",
							FieldName:      "Any",
							Type:           &generator.PrimitiveType{Name: "any"},
							RequiredFields: []string{"x", "y"},
							FullyChecked:   secondFullyChecked,
						},
					},
				}},
			},
			&generator.StructDef{Name: "Payload"},
		},
	}
}

// TestEmitOneOfSelectionNarrowsOnBranchConstraints is the emitter half of issue
// #81. Selection counted a branch as matched once its required keys were
// present, so a document carrying both branches' required keys was rejected as
// "multiple oneOf variants matched" even when only one branch was satisfied.
//
// The repair reads the branches' own constraints -- an object branch keeps them
// inside its variant type, reachable only through that type's Validate -- and
// uses them to narrow a selection the decoder was about to reject anyway. The
// generator half, which decides whether a branch can be judged at all, is
// pinned in pkg/generator/generator_test.go.
func TestEmitOneOfSelectionNarrowsOnBranchConstraints(t *testing.T) {
	e := mustNew(t)

	out, err := e.Emit(oneOfNarrowingFile(true))
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)

	for _, want := range []string{
		// The stricter tally, and the branch constraint that feeds it.
		"if _vErr := candidate.Validate(); _vErr == nil {",
		"oneofStrict++",
		// Only consulted where selection was already going to reject.
		"if oneofMatched > 1 && oneofOpaque == 0 {",
		"case oneofStrict == 1:",
		"e.Body = oneofStrictSel",
		// A value no branch accepts is not ambiguity, and is not reported as a
		// count.
		`return fmt.Errorf("Envelope.Body: no matching oneOf variant: %w", oneofStrictErr)`,
	} {
		if !strings.Contains(src, want) {
			t.Fatalf("Envelope.UnmarshalJSON is missing %q:\n%s", want, src)
		}
	}
	// The narrowing must not displace the ambiguity rejection: two branches that
	// are both satisfied are still two matches.
	if !strings.Contains(src, `multiple oneOf variants matched (%d), expected exactly 1`) {
		t.Fatalf("Envelope.UnmarshalJSON stopped rejecting a genuinely ambiguous value:\n%s", src)
	}
}

// TestEmitOneOfSelectionDoesNotNarrowPastAnUnjudgeableBranch is the over-reach
// guard for the arm above. Narrowing is sound only while every branch that
// matched can be judged; a branch that is neither Validatable nor FullyChecked
// is one nothing read, and counting it out would select a variant while a
// sibling that also matched went unexamined -- accepting a document that
// matches two branches.
func TestEmitOneOfSelectionDoesNotNarrowPastAnUnjudgeableBranch(t *testing.T) {
	e := mustNew(t)

	out, err := e.Emit(oneOfNarrowingFile(false))
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)

	if !strings.Contains(src, "oneofOpaque++") {
		t.Fatalf("the unjudgeable branch does not mark itself opaque, so the narrowing runs without having read it:\n%s", src)
	}
	if !strings.Contains(src, "if oneofMatched > 1 && oneofOpaque == 0 {") {
		t.Fatalf("the narrowing is not gated on every matched branch being judged:\n%s", src)
	}
}

// TestEmitFieldContainsPointerSlice renders the one arm of the contains check
// the generator cannot currently reach: a field typed *[]T. Ranging over a
// dereferenced nil pointer panics, so the arm wraps the count in a nil guard,
// and nothing else in the suite would notice if that wrapper stopped being
// valid Go -- Emit runs the result through format.Source, so a broken arm is a
// failure here and silence everywhere else.
func TestEmitFieldContainsPointerSlice(t *testing.T) {
	e := mustNew(t)

	minContains, maxContains := 2, 3
	f := &generator.File{
		PackageName: "model",
		Imports: []generator.Import{
			{Path: "encoding/json"}, {Path: "fmt"}, {Path: "math"},
		},
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Doc",
				Fields: []generator.FieldDef{
					{
						Name:     "Nums",
						JSONName: "nums",
						Type: &generator.PointerType{
							Inner: &generator.ArrayType{ItemType: &generator.PrimitiveType{Name: "int64"}},
						},
						Required: true,
					},
				},
				ContainsValidations: []generator.FieldContainsDef{
					{
						FieldName: "Nums",
						JSONName:  "nums",
						IsPointer: true,
						Contains: &generator.ContainsDef{
							Checks: []generator.ContainsCheck{
								{CheckType: "type", Value: "integer"},
								{CheckType: "minimum", Value: 10.0},
							},
						},
						MinContains: &minContains,
						MaxContains: &maxContains,
					},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)

	if !containsNormalized(src, "if d.Nums != nil {") {
		t.Fatalf("expected a nil guard around the pointer slice's contains check:\n%s", src)
	}
	if !containsNormalized(src, "for _, _cElem := range *d.Nums {") {
		t.Fatalf("expected the count to range over the dereferenced slice:\n%s", src)
	}
	if !containsNormalized(src, `"nums: contains: %d matching elements, minimum is 2"`) {
		t.Fatalf("expected the error to be reported under the property name:\n%s", src)
	}
	if !containsNormalized(src, `"nums: contains: %d matching elements, maximum is 3"`) {
		t.Fatalf("expected the maxContains error:\n%s", src)
	}
}

// TestEmitFieldContainsFalseIsVetClean pins the shape `contains: false` is
// emitted in. No element can ever match, so the count stays at zero and the
// bounds decide -- the same code every other sub-schema gets. Returning
// unconditionally instead, which is what this emitted before the check moved
// onto struct fields, leaves everything after it in Validate unreachable, and
// `go vet` fails a generated file for that. Nothing else in the suite would
// see it: unreachable code compiles.
func TestEmitFieldContainsFalseIsVetClean(t *testing.T) {
	e := mustNew(t)

	f := &generator.File{
		PackageName: "model",
		Imports:     []generator.Import{{Path: "fmt"}},
		TypeDefs: []generator.TypeDef{
			&generator.StructDef{
				Name: "Doc",
				Fields: []generator.FieldDef{
					{
						Name:     "Nums",
						JSONName: "nums",
						Type:     &generator.ArrayType{ItemType: &generator.PrimitiveType{Name: "int64"}},
						Required: true,
					},
				},
				ContainsValidations: []generator.FieldContainsDef{
					{
						FieldName: "Nums",
						JSONName:  "nums",
						Contains:  &generator.ContainsDef{IsFalse: true},
					},
				},
			},
		},
	}

	out, err := e.Emit(f)
	if err != nil {
		t.Fatalf("Emit() error: %v", err)
	}
	src := string(out)

	if !containsNormalized(src, "if _containsCount < 1 {") {
		t.Fatalf("contains: false must go through the count, not an unconditional return:\n%s", src)
	}
	// The literal the unconditional-return form reported through, and the only
	// place it was ever written. Matching on the block shape instead does not
	// work: containsNormalized collapses runs of spaces but keeps newlines, and
	// the emitted `{` and `return` are on separate lines, so such a pattern
	// would never match whatever the template did.
	if strings.Contains(src, "no element matches (schema is false)") {
		t.Fatalf("contains: false emitted an unconditional return; the rest of Validate is unreachable:\n%s", src)
	}
}

// allFormatKeywords is every "format" this repository has an opinion about,
// listed once so the two halves of that opinion can be checked against each
// other. The list is what a schema may write; which of them are asserted is
// generator.FormatCheckableOnString's answer, and which have code to assert
// them is formatHelperNameFunc's.
var allFormatKeywords = []string{
	"date", "date-time", "time", "duration",
	"email", "idn-email",
	"hostname", "idn-hostname",
	"ipv4", "ipv6",
	"uri", "uri-reference", "uri-template",
	"iri", "iri-reference",
	"uuid", "json-pointer", "relative-json-pointer", "regex",
	// Not asserted, and here to prove the pair agree about that too.
	"unknown-format", "byte", "int32",
}

// TestFormatHelperNamesCoverCheckableFormats holds the generator's list of
// assertable formats and the emitter's list of helper functions together.
//
// They are two halves of one decision and they live in different packages. A
// format the generator admits but the emitter cannot name builds a rule that
// renders nothing -- the schema looks checked and is not, which is the exact
// shape of the defect this area keeps producing. A format the emitter can name
// but the generator does not admit is dead code, which is cheaper but still a
// lie about what is enforced.
func TestFormatHelperNamesCoverCheckableFormats(t *testing.T) {
	for _, format := range allFormatKeywords {
		checkable := generator.FormatCheckableOnString(format)
		named := formatHelperNameFunc(format, true) != ""
		if checkable != named {
			t.Errorf("format %q: generator says checkable=%v, emitter says it has a helper=%v", format, checkable, named)
		}
	}
}

// TestFormatHelpersAreDefinedForEveryName renders the helper block once and
// checks that every function formatHelperNameFunc can emit a call to is
// actually declared in it.
//
// The call and the declaration are in different templates, and nothing else
// connects them: a renamed helper would emit a call to a function that does not
// exist, and the failure would surface as a compile error in whatever someone
// generated next rather than here.
func TestFormatHelpersAreDefinedForEveryName(t *testing.T) {
	e, err := New()
	if err != nil {
		t.Fatalf("New() error: %v", err)
	}
	// Both blocks: the hostname checks live in their own, so that a package
	// naming no hostname does not import x/net/idna.
	src, ok, err := e.EmitHelpers("testpkg", generator.HelperSet{Format: true, FormatHostname: true})
	if err != nil || !ok {
		t.Fatalf("EmitHelpers() error: %v (ok=%v)", err, ok)
	}
	body := string(src)
	for _, format := range allFormatKeywords {
		for _, stringBacked := range []bool{true, false} {
			name := formatHelperNameFunc(format, stringBacked)
			if name == "" {
				continue
			}
			if !strings.Contains(body, "func "+name+"(") {
				t.Errorf("format %q (stringBacked=%v) emits a call to %s, which the helper block does not declare", format, stringBacked, name)
			}
		}
	}
}

// TestHostnameHelpersAreConfinedToSchemasThatNeedThem pins the one thing the
// helper-set split exists for: a package whose schemas name no hostname does not
// import golang.org/x/net/idna.
//
// Generated code putting a dependency on its caller is a real imposition, and
// the two hostname checks are the only ones that need one. Nothing else would
// notice if the split collapsed -- the code would compile and the tests would
// pass -- so this is the only thing standing between "a schema with a date-time
// in it" and "every consumer of that schema now depends on x/net and x/text".
func TestHostnameHelpersAreConfinedToSchemasThatNeedThem(t *testing.T) {
	e, err := New()
	if err != nil {
		t.Fatalf("New() error: %v", err)
	}

	general, _, err := e.EmitHelpers("testpkg", generator.HelperSet{Format: true})
	if err != nil {
		t.Fatalf("EmitHelpers(Format) error: %v", err)
	}
	if strings.Contains(string(general), "golang.org/x/net/idna") {
		t.Errorf("the general format block imports x/net/idna:\n%s", general)
	}
	if strings.Contains(string(general), "func schemagenFormatHostname(") {
		t.Errorf("the general format block declares the hostname check")
	}

	withHostname, _, err := e.EmitHelpers("testpkg", generator.HelperSet{Format: true, FormatHostname: true})
	if err != nil {
		t.Fatalf("EmitHelpers(Format+FormatHostname) error: %v", err)
	}
	if !strings.Contains(string(withHostname), "golang.org/x/net/idna") {
		t.Errorf("the hostname block does not import x/net/idna:\n%s", withHostname)
	}
	if !strings.Contains(string(withHostname), "func schemagenFormatHostname(") {
		t.Errorf("the hostname block does not declare the hostname check")
	}
}

// TestFormatHelperSetTracksTheFormatsUsed checks the generator half of the same
// split: which block a file needs is read off the rules it carries, and `email`
// counts as a hostname because an address's domain is judged by that check.
func TestFormatHelperSetTracksTheFormatsUsed(t *testing.T) {
	fileWith := func(format string) *generator.File {
		return &generator.File{TypeDefs: []generator.TypeDef{
			&generator.AliasDef{
				Name:        "X",
				Underlying:  &generator.PrimitiveType{Name: "string"},
				Validations: []generator.ValidationRule{{RuleType: "format", Value: format}},
			},
		}}
	}
	for _, tc := range []struct {
		format            string
		wantFmt, wantHost bool
	}{
		{"uuid", true, false},
		{"date-time", true, false},
		{"ipv4", true, false},
		{"hostname", true, true},
		{"idn-hostname", true, true},
		{"email", true, true},
		{"idn-email", true, true},
	} {
		set := fileWith(tc.format).Helpers()
		if set.Format != tc.wantFmt || set.FormatHostname != tc.wantHost {
			t.Errorf("format %q: got Format=%v FormatHostname=%v, want %v/%v",
				tc.format, set.Format, set.FormatHostname, tc.wantFmt, tc.wantHost)
		}
	}
}
