package tests

// Known failures for external JSON Schema Test Suite tests.
//
// Keys are formatted as "draft/filename/group_description" for parsing and codegen tests,
// and "draft/filename/group_description/test_description" for round-trip tests.
//
// Values are short reason strings explaining why the test is expected to fail.
//
// Bidirectional checking ensures:
//   - A known failure that fails -> skipped (expected)
//   - A known failure that passes -> test error (remove from list)
//   - An unknown test that fails -> test error (regression or needs adding to list)
//   - An unknown test that passes -> pass (expected)
//
// Failure categories:
//   - "boolean schema in sub-position not supported" - JSON Schema allows true/false as schemas
//   - "float-encoded integer not supported for int fields" - e.g. minItems: 2.0
//   - "draft3 required-as-boolean not supported" - Draft 3 had required: true on properties
//   - "draft3 type-as-schema-array not supported" - Draft 3 allowed type: [{schema}, ...]
//   - "parse: schema feature not supported by parser" - cascaded parse failures in codegen/roundtrip
//   - "emit: invalid Go identifier from schema naming" - $ref paths, URNs, special chars in names
//   - "compile: generated code does not compile" - IR issues (oneOf without parent, recursive refs)
//   - "round-trip: compilation or execution error" - generated code compiles but round-trip fails
//   - "no root struct type in generated code" - schema produces no struct (e.g. type: "object" only)

// knownParseFailures tracks schemas that our parser cannot handle yet.
// Total: 192 known failures
var knownParseFailures = map[string]string{
	"draft2019-09/allOf/allOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft2019-09/allOf/allOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft2019-09/allOf/allOf with boolean schemas, some false": "boolean schema in sub-position not supported",
	"draft2019-09/anyOf/anyOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft2019-09/anyOf/anyOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft2019-09/anyOf/anyOf with boolean schemas, some true": "boolean schema in sub-position not supported",
	"draft2019-09/contains/contains keyword with boolean schema false": "boolean schema in sub-position not supported",
	"draft2019-09/contains/contains keyword with boolean schema true": "boolean schema in sub-position not supported",
	"draft2019-09/contains/contains with false if subschema": "boolean schema in sub-position not supported",
	"draft2019-09/if-then-else/else: false fails when condition does not match": "boolean schema in sub-position not supported",
	"draft2019-09/if-then-else/if with boolean schema false": "boolean schema in sub-position not supported",
	"draft2019-09/if-then-else/if with boolean schema true": "boolean schema in sub-position not supported",
	"draft2019-09/if-then-else/then: false fails when condition matches": "boolean schema in sub-position not supported",
	"draft2019-09/items/items with boolean schema (false)": "boolean schema in items/prefixItems not supported",
	"draft2019-09/items/items with boolean schema (true)": "boolean schema in items/prefixItems not supported",
	"draft2019-09/items/items with boolean schemas": "boolean schema in items/prefixItems not supported",
	"draft2019-09/maxItems/maxItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2019-09/maxLength/maxLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2019-09/maxProperties/maxProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2019-09/minItems/minItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2019-09/minLength/minLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2019-09/minProperties/minProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2019-09/not/allow everything with boolean schema false": "boolean schema in sub-position not supported",
	"draft2019-09/not/collect annotations inside a 'not', even if collection is disabled": "boolean schema in sub-position not supported",
	"draft2019-09/not/forbid everything with boolean schema true": "boolean schema in sub-position not supported",
	"draft2019-09/oneOf/oneOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft2019-09/oneOf/oneOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft2019-09/oneOf/oneOf with boolean schemas, more than one true": "boolean schema in sub-position not supported",
	"draft2019-09/oneOf/oneOf with boolean schemas, one true": "boolean schema in sub-position not supported",
	"draft2019-09/oneOf/oneOf with missing optional property": "boolean schema in sub-position not supported",
	"draft2019-09/patternProperties/patternProperties with boolean schemas": "boolean schema in sub-position not supported",
	"draft2019-09/properties/properties with boolean schema": "boolean schema in sub-position not supported",
	"draft2019-09/ref/$ref to boolean schema false": "boolean schema in sub-position not supported",
	"draft2019-09/ref/$ref to boolean schema true": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedItems/Evaluated items collection needs to consider instance location": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/item is evaluated in an uncle schema to unevaluatedItems": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems before $ref": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems can't see inside cousins": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with $recursiveRef": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with $ref": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with anyOf": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with boolean schemas": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with if/then/else": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with nested items": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with nested tuple": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with not": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedItems/unevaluatedItems with oneOf": "boolean schema in items/prefixItems not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/in-place applicator siblings, allOf has unevaluated": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/in-place applicator siblings, anyOf has unevaluated": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties can't see inside cousins": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties can't see inside cousins (reverse order)": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with $recursiveRef": "boolean schema in sub-position not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with boolean schemas": "boolean schema in sub-position not supported",
	"draft2019-09/vocabulary/schema that uses custom metaschema with with no validation vocabulary": "boolean schema in sub-position not supported",
	"draft2020-12/allOf/allOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft2020-12/allOf/allOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft2020-12/allOf/allOf with boolean schemas, some false": "boolean schema in sub-position not supported",
	"draft2020-12/anyOf/anyOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft2020-12/anyOf/anyOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft2020-12/anyOf/anyOf with boolean schemas, some true": "boolean schema in sub-position not supported",
	"draft2020-12/contains/contains keyword with boolean schema false": "boolean schema in sub-position not supported",
	"draft2020-12/contains/contains keyword with boolean schema true": "boolean schema in sub-position not supported",
	"draft2020-12/contains/contains with false if subschema": "boolean schema in sub-position not supported",
	"draft2020-12/dynamicRef/$dynamicRef points to a boolean schema": "boolean schema in sub-position not supported",
	"draft2020-12/dynamicRef/$ref and $dynamicAnchor are independent of order - $defs first": "boolean schema in sub-position not supported",
	"draft2020-12/dynamicRef/$ref and $dynamicAnchor are independent of order - $ref first": "boolean schema in sub-position not supported",
	"draft2020-12/dynamicRef/tests for implementation dynamic anchor and reference link": "boolean schema in sub-position not supported",
	"draft2020-12/if-then-else/else: false fails when condition does not match": "boolean schema in sub-position not supported",
	"draft2020-12/if-then-else/if with boolean schema false": "boolean schema in sub-position not supported",
	"draft2020-12/if-then-else/if with boolean schema true": "boolean schema in sub-position not supported",
	"draft2020-12/if-then-else/then: false fails when condition matches": "boolean schema in sub-position not supported",
	"draft2020-12/items/items and subitems": "boolean schema in items/prefixItems not supported",
	"draft2020-12/items/items with boolean schema (false)": "boolean schema in items/prefixItems not supported",
	"draft2020-12/items/items with boolean schema (true)": "boolean schema in items/prefixItems not supported",
	"draft2020-12/items/items with heterogeneous array": "boolean schema in items/prefixItems not supported",
	"draft2020-12/items/prefixItems with no additional items allowed": "boolean schema in items/prefixItems not supported",
	"draft2020-12/maxItems/maxItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2020-12/maxLength/maxLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2020-12/maxProperties/maxProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2020-12/minItems/minItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2020-12/minLength/minLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2020-12/minProperties/minProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft2020-12/not/allow everything with boolean schema false": "boolean schema in sub-position not supported",
	"draft2020-12/not/collect annotations inside a 'not', even if collection is disabled": "boolean schema in sub-position not supported",
	"draft2020-12/not/forbid everything with boolean schema true": "boolean schema in sub-position not supported",
	"draft2020-12/oneOf/oneOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft2020-12/oneOf/oneOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft2020-12/oneOf/oneOf with boolean schemas, more than one true": "boolean schema in sub-position not supported",
	"draft2020-12/oneOf/oneOf with boolean schemas, one true": "boolean schema in sub-position not supported",
	"draft2020-12/oneOf/oneOf with missing optional property": "boolean schema in sub-position not supported",
	"draft2020-12/patternProperties/patternProperties with boolean schemas": "boolean schema in sub-position not supported",
	"draft2020-12/prefixItems/prefixItems with boolean schemas": "boolean schema in sub-position not supported",
	"draft2020-12/properties/properties with boolean schema": "boolean schema in sub-position not supported",
	"draft2020-12/ref/$ref to boolean schema false": "boolean schema in sub-position not supported",
	"draft2020-12/ref/$ref to boolean schema true": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/Evaluated items collection needs to consider instance location": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/item is evaluated in an uncle schema to unevaluatedItems": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems before $ref": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems can't see inside cousins": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems depends on adjacent contains": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with $dynamicRef": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with $ref": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with anyOf": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with boolean schemas": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with if/then/else": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with items and prefixItems": "boolean schema in items/prefixItems not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with nested items": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with nested prefixItems and items": "boolean schema in items/prefixItems not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with nested tuple": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with not": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedItems/unevaluatedItems with oneOf": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/in-place applicator siblings, allOf has unevaluated": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/in-place applicator siblings, anyOf has unevaluated": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties can't see inside cousins": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties can't see inside cousins (reverse order)": "boolean schema in sub-position not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with boolean schemas": "boolean schema in sub-position not supported",
	"draft2020-12/uniqueItems/uniqueItems with an array of items and additionalItems=false": "boolean schema in items/prefixItems not supported",
	"draft2020-12/uniqueItems/uniqueItems=false with an array of items and additionalItems=false": "boolean schema in items/prefixItems not supported",
	"draft2020-12/vocabulary/schema that uses custom metaschema with with no validation vocabulary": "boolean schema in sub-position not supported",
	"draft3/enum/enums in properties": "draft3 required-as-boolean not supported",
	"draft3/extends/extends": "draft3 required-as-boolean not supported",
	"draft3/extends/multiple extends": "draft3 required-as-boolean not supported",
	"draft3/required/required explicitly false validation": "draft3 required-as-boolean not supported",
	"draft3/required/required validation": "draft3 required-as-boolean not supported",
	"draft3/type/applies a nested schema": "draft3 type-as-schema-array not supported",
	"draft3/type/types can include schemas": "draft3 type-as-schema-array not supported",
	"draft3/type/types from separate schemas are merged": "draft3 type-as-schema-array not supported",
	"draft6/allOf/allOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft6/allOf/allOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft6/allOf/allOf with boolean schemas, some false": "boolean schema in sub-position not supported",
	"draft6/anyOf/anyOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft6/anyOf/anyOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft6/anyOf/anyOf with boolean schemas, some true": "boolean schema in sub-position not supported",
	"draft6/contains/contains keyword with boolean schema false": "boolean schema in sub-position not supported",
	"draft6/contains/contains keyword with boolean schema true": "boolean schema in sub-position not supported",
	"draft6/items/items with boolean schema (false)": "boolean schema in items/prefixItems not supported",
	"draft6/items/items with boolean schema (true)": "boolean schema in items/prefixItems not supported",
	"draft6/items/items with boolean schemas": "boolean schema in items/prefixItems not supported",
	"draft6/maxItems/maxItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft6/maxLength/maxLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft6/maxProperties/maxProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft6/minItems/minItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft6/minLength/minLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft6/minProperties/minProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft6/not/allow everything with boolean schema false": "boolean schema in sub-position not supported",
	"draft6/not/forbid everything with boolean schema true": "boolean schema in sub-position not supported",
	"draft6/oneOf/oneOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft6/oneOf/oneOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft6/oneOf/oneOf with boolean schemas, more than one true": "boolean schema in sub-position not supported",
	"draft6/oneOf/oneOf with boolean schemas, one true": "boolean schema in sub-position not supported",
	"draft6/oneOf/oneOf with missing optional property": "boolean schema in sub-position not supported",
	"draft6/patternProperties/patternProperties with boolean schemas": "boolean schema in sub-position not supported",
	"draft6/properties/properties with boolean schema": "boolean schema in sub-position not supported",
	"draft6/ref/$ref to boolean schema false": "boolean schema in sub-position not supported",
	"draft6/ref/$ref to boolean schema true": "boolean schema in sub-position not supported",
	"draft7/allOf/allOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft7/allOf/allOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft7/allOf/allOf with boolean schemas, some false": "boolean schema in sub-position not supported",
	"draft7/anyOf/anyOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft7/anyOf/anyOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft7/anyOf/anyOf with boolean schemas, some true": "boolean schema in sub-position not supported",
	"draft7/contains/contains keyword with boolean schema false": "boolean schema in sub-position not supported",
	"draft7/contains/contains keyword with boolean schema true": "boolean schema in sub-position not supported",
	"draft7/contains/contains with false if subschema": "boolean schema in sub-position not supported",
	"draft7/if-then-else/else: false fails when condition does not match": "boolean schema in sub-position not supported",
	"draft7/if-then-else/if with boolean schema false": "boolean schema in sub-position not supported",
	"draft7/if-then-else/if with boolean schema true": "boolean schema in sub-position not supported",
	"draft7/if-then-else/then: false fails when condition matches": "boolean schema in sub-position not supported",
	"draft7/items/items with boolean schema (false)": "boolean schema in items/prefixItems not supported",
	"draft7/items/items with boolean schema (true)": "boolean schema in items/prefixItems not supported",
	"draft7/items/items with boolean schemas": "boolean schema in items/prefixItems not supported",
	"draft7/maxItems/maxItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft7/maxLength/maxLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft7/maxProperties/maxProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft7/minItems/minItems validation with a decimal": "float-encoded integer not supported for int fields",
	"draft7/minLength/minLength validation with a decimal": "float-encoded integer not supported for int fields",
	"draft7/minProperties/minProperties validation with a decimal": "float-encoded integer not supported for int fields",
	"draft7/not/allow everything with boolean schema false": "boolean schema in sub-position not supported",
	"draft7/not/forbid everything with boolean schema true": "boolean schema in sub-position not supported",
	"draft7/oneOf/oneOf with boolean schemas, all false": "boolean schema in sub-position not supported",
	"draft7/oneOf/oneOf with boolean schemas, all true": "boolean schema in sub-position not supported",
	"draft7/oneOf/oneOf with boolean schemas, more than one true": "boolean schema in sub-position not supported",
	"draft7/oneOf/oneOf with boolean schemas, one true": "boolean schema in sub-position not supported",
	"draft7/oneOf/oneOf with missing optional property": "boolean schema in sub-position not supported",
	"draft7/patternProperties/patternProperties with boolean schemas": "boolean schema in sub-position not supported",
	"draft7/properties/properties with boolean schema": "boolean schema in sub-position not supported",
	"draft7/ref/$ref to boolean schema false": "boolean schema in sub-position not supported",
	"draft7/ref/$ref to boolean schema true": "boolean schema in sub-position not supported",
}

// knownCodeGenFailures tracks schemas that fail during IR generation,
// code emission, or compilation.
// Total: 201 known failures
var knownCodeGenFailures = map[string]string{
	"draft2019-09/allOf/allOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft2019-09/allOf/allOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft2019-09/allOf/allOf with boolean schemas, some false": "parse: schema feature not supported by parser",
	"draft2019-09/anyOf/anyOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft2019-09/anyOf/anyOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft2019-09/anyOf/anyOf with boolean schemas, some true": "parse: schema feature not supported by parser",
	"draft2019-09/oneOf/oneOf": "compile: generated code does not compile",
	"draft2019-09/oneOf/oneOf complex types": "compile: generated code does not compile",
	"draft2019-09/oneOf/oneOf with base schema": "compile: generated code does not compile",
	"draft2019-09/oneOf/oneOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft2019-09/oneOf/oneOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft2019-09/oneOf/oneOf with boolean schemas, more than one true": "parse: schema feature not supported by parser",
	"draft2019-09/oneOf/oneOf with boolean schemas, one true": "parse: schema feature not supported by parser",
	"draft2019-09/oneOf/oneOf with empty schema": "compile: generated code does not compile",
	"draft2019-09/oneOf/oneOf with missing optional property": "parse: schema feature not supported by parser",
	"draft2019-09/oneOf/oneOf with required": "compile: generated code does not compile",
	"draft2019-09/properties/properties with boolean schema": "parse: schema feature not supported by parser",
	"draft2019-09/properties/properties with escaped characters": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/Recursive references between schemas": "compile: generated code does not compile",
	"draft2019-09/ref/URN base URI with URN and anchor ref": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/empty tokens in $ref json-pointer": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/escaped pointer ref": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/property named $ref that is not a reference": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/property named $ref, containing an actual $ref": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/refs with quote": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/refs with relative uris and defs": "compile: generated code does not compile",
	"draft2019-09/ref/relative pointer ref to object": "compile: generated code does not compile",
	"draft2019-09/ref/relative refs with absolute uris and defs": "compile: generated code does not compile",
	"draft2019-09/ref/root pointer ref": "emit: invalid Go identifier from schema naming",
	"draft2019-09/ref/simple URN base URI with $ref via the URN": "emit: invalid Go identifier from schema naming",
	"draft2019-09/refRemote/base URI change - change folder": "compile: generated code does not compile",
	"draft2019-09/refRemote/base URI change - change folder in subschema": "compile: generated code does not compile",
	"draft2019-09/refRemote/retrieved nested refs resolve relative to their URI not $id": "compile: generated code does not compile",
	"draft2019-09/refRemote/root ref in remote ref": "compile: generated code does not compile",
	"draft2019-09/unevaluatedItems/item is evaluated in an uncle schema to unevaluatedItems": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedItems/unevaluatedItems can't see inside cousins": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedItems/unevaluatedItems with anyOf": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedItems/unevaluatedItems with boolean schemas": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedItems/unevaluatedItems with nested items": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedItems/unevaluatedItems with nested tuple": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedItems/unevaluatedItems with oneOf": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/in-place applicator siblings, allOf has unevaluated": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/in-place applicator siblings, anyOf has unevaluated": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + single cyclic ref": "emit: invalid Go identifier from schema naming",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties can't see inside cousins": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties can't see inside cousins (reverse order)": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with $recursiveRef": "parse: schema feature not supported by parser",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with boolean schemas": "parse: schema feature not supported by parser",
	"draft2019-09/vocabulary/schema that uses custom metaschema with with no validation vocabulary": "parse: schema feature not supported by parser",
	"draft2020-12/allOf/allOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft2020-12/allOf/allOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft2020-12/allOf/allOf with boolean schemas, some false": "parse: schema feature not supported by parser",
	"draft2020-12/anyOf/anyOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft2020-12/anyOf/anyOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft2020-12/anyOf/anyOf with boolean schemas, some true": "parse: schema feature not supported by parser",
	"draft2020-12/dynamicRef/$dynamicRef points to a boolean schema": "parse: schema feature not supported by parser",
	"draft2020-12/dynamicRef/$dynamicRef skips over intermediate resources - direct reference": "compile: generated code does not compile",
	"draft2020-12/dynamicRef/$ref and $dynamicAnchor are independent of order - $defs first": "parse: schema feature not supported by parser",
	"draft2020-12/dynamicRef/$ref and $dynamicAnchor are independent of order - $ref first": "parse: schema feature not supported by parser",
	"draft2020-12/oneOf/oneOf": "compile: generated code does not compile",
	"draft2020-12/oneOf/oneOf complex types": "compile: generated code does not compile",
	"draft2020-12/oneOf/oneOf with base schema": "compile: generated code does not compile",
	"draft2020-12/oneOf/oneOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft2020-12/oneOf/oneOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft2020-12/oneOf/oneOf with boolean schemas, more than one true": "parse: schema feature not supported by parser",
	"draft2020-12/oneOf/oneOf with boolean schemas, one true": "parse: schema feature not supported by parser",
	"draft2020-12/oneOf/oneOf with empty schema": "compile: generated code does not compile",
	"draft2020-12/oneOf/oneOf with missing optional property": "parse: schema feature not supported by parser",
	"draft2020-12/oneOf/oneOf with required": "compile: generated code does not compile",
	"draft2020-12/properties/properties with boolean schema": "parse: schema feature not supported by parser",
	"draft2020-12/properties/properties with escaped characters": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/Recursive references between schemas": "compile: generated code does not compile",
	"draft2020-12/ref/URN base URI with URN and anchor ref": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/empty tokens in $ref json-pointer": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/escaped pointer ref": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/property named $ref that is not a reference": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/property named $ref, containing an actual $ref": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/refs with quote": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/refs with relative uris and defs": "compile: generated code does not compile",
	"draft2020-12/ref/relative pointer ref to object": "compile: generated code does not compile",
	"draft2020-12/ref/relative refs with absolute uris and defs": "compile: generated code does not compile",
	"draft2020-12/ref/root pointer ref": "emit: invalid Go identifier from schema naming",
	"draft2020-12/ref/simple URN base URI with $ref via the URN": "emit: invalid Go identifier from schema naming",
	"draft2020-12/refRemote/base URI change - change folder": "compile: generated code does not compile",
	"draft2020-12/refRemote/base URI change - change folder in subschema": "compile: generated code does not compile",
	"draft2020-12/refRemote/retrieved nested refs resolve relative to their URI not $id": "compile: generated code does not compile",
	"draft2020-12/refRemote/root ref in remote ref": "compile: generated code does not compile",
	"draft2020-12/unevaluatedItems/item is evaluated in an uncle schema to unevaluatedItems": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems can't see inside cousins": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems with anyOf": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems with boolean schemas": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems with nested items": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems with nested prefixItems and items": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems with nested tuple": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedItems/unevaluatedItems with oneOf": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/in-place applicator siblings, allOf has unevaluated": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/in-place applicator siblings, anyOf has unevaluated": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + single cyclic ref": "emit: invalid Go identifier from schema naming",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties can't see inside cousins": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties can't see inside cousins (reverse order)": "parse: schema feature not supported by parser",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with boolean schemas": "parse: schema feature not supported by parser",
	"draft2020-12/vocabulary/schema that uses custom metaschema with with no validation vocabulary": "parse: schema feature not supported by parser",
	"draft3/enum/enums in properties": "parse: schema feature not supported by parser",
	"draft3/extends/extends": "parse: schema feature not supported by parser",
	"draft3/extends/multiple extends": "parse: schema feature not supported by parser",
	"draft3/ref/escaped pointer ref": "emit: invalid Go identifier from schema naming",
	"draft3/ref/property named $ref, containing an actual $ref": "emit: invalid Go identifier from schema naming",
	"draft3/ref/relative pointer ref to object": "compile: generated code does not compile",
	"draft3/ref/root pointer ref": "emit: invalid Go identifier from schema naming",
	"draft3/required/required explicitly false validation": "parse: schema feature not supported by parser",
	"draft3/required/required validation": "parse: schema feature not supported by parser",
	"draft4/oneOf/oneOf": "compile: generated code does not compile",
	"draft4/oneOf/oneOf complex types": "compile: generated code does not compile",
	"draft4/oneOf/oneOf with base schema": "compile: generated code does not compile",
	"draft4/oneOf/oneOf with empty schema": "compile: generated code does not compile",
	"draft4/oneOf/oneOf with missing optional property": "compile: generated code does not compile",
	"draft4/oneOf/oneOf with required": "compile: generated code does not compile",
	"draft4/properties/properties with escaped characters": "emit: invalid Go identifier from schema naming",
	"draft4/ref/Recursive references between schemas": "compile: generated code does not compile",
	"draft4/ref/empty tokens in $ref json-pointer": "emit: invalid Go identifier from schema naming",
	"draft4/ref/escaped pointer ref": "emit: invalid Go identifier from schema naming",
	"draft4/ref/property named $ref that is not a reference": "emit: invalid Go identifier from schema naming",
	"draft4/ref/property named $ref, containing an actual $ref": "emit: invalid Go identifier from schema naming",
	"draft4/ref/refs with quote": "emit: invalid Go identifier from schema naming",
	"draft4/ref/relative pointer ref to object": "compile: generated code does not compile",
	"draft4/ref/root pointer ref": "emit: invalid Go identifier from schema naming",
	"draft4/refRemote/base URI change - change folder": "compile: generated code does not compile",
	"draft4/refRemote/base URI change - change folder in subschema": "compile: generated code does not compile",
	"draft4/refRemote/root ref in remote ref": "compile: generated code does not compile",
	"draft6/allOf/allOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft6/allOf/allOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft6/allOf/allOf with boolean schemas, some false": "parse: schema feature not supported by parser",
	"draft6/anyOf/anyOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft6/anyOf/anyOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft6/anyOf/anyOf with boolean schemas, some true": "parse: schema feature not supported by parser",
	"draft6/oneOf/oneOf": "compile: generated code does not compile",
	"draft6/oneOf/oneOf complex types": "compile: generated code does not compile",
	"draft6/oneOf/oneOf with base schema": "compile: generated code does not compile",
	"draft6/oneOf/oneOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft6/oneOf/oneOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft6/oneOf/oneOf with boolean schemas, more than one true": "parse: schema feature not supported by parser",
	"draft6/oneOf/oneOf with boolean schemas, one true": "parse: schema feature not supported by parser",
	"draft6/oneOf/oneOf with empty schema": "compile: generated code does not compile",
	"draft6/oneOf/oneOf with missing optional property": "parse: schema feature not supported by parser",
	"draft6/oneOf/oneOf with required": "compile: generated code does not compile",
	"draft6/properties/properties with boolean schema": "parse: schema feature not supported by parser",
	"draft6/properties/properties with escaped characters": "emit: invalid Go identifier from schema naming",
	"draft6/ref/$ref to boolean schema false": "parse: schema feature not supported by parser",
	"draft6/ref/$ref to boolean schema true": "parse: schema feature not supported by parser",
	"draft6/ref/Recursive references between schemas": "compile: generated code does not compile",
	"draft6/ref/URN base URI with URN and anchor ref": "emit: invalid Go identifier from schema naming",
	"draft6/ref/empty tokens in $ref json-pointer": "emit: invalid Go identifier from schema naming",
	"draft6/ref/escaped pointer ref": "emit: invalid Go identifier from schema naming",
	"draft6/ref/property named $ref that is not a reference": "emit: invalid Go identifier from schema naming",
	"draft6/ref/property named $ref, containing an actual $ref": "emit: invalid Go identifier from schema naming",
	"draft6/ref/refs with quote": "emit: invalid Go identifier from schema naming",
	"draft6/ref/relative pointer ref to object": "compile: generated code does not compile",
	"draft6/ref/root pointer ref": "emit: invalid Go identifier from schema naming",
	"draft6/ref/simple URN base URI with $ref via the URN": "emit: invalid Go identifier from schema naming",
	"draft6/refRemote/base URI change - change folder": "compile: generated code does not compile",
	"draft6/refRemote/base URI change - change folder in subschema": "compile: generated code does not compile",
	"draft6/refRemote/retrieved nested refs resolve relative to their URI not $id": "compile: generated code does not compile",
	"draft6/refRemote/root ref in remote ref": "compile: generated code does not compile",
	"draft7/allOf/allOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft7/allOf/allOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft7/allOf/allOf with boolean schemas, some false": "parse: schema feature not supported by parser",
	"draft7/anyOf/anyOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft7/anyOf/anyOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft7/anyOf/anyOf with boolean schemas, some true": "parse: schema feature not supported by parser",
	"draft7/oneOf/oneOf": "compile: generated code does not compile",
	"draft7/oneOf/oneOf complex types": "compile: generated code does not compile",
	"draft7/oneOf/oneOf with base schema": "compile: generated code does not compile",
	"draft7/oneOf/oneOf with boolean schemas, all false": "parse: schema feature not supported by parser",
	"draft7/oneOf/oneOf with boolean schemas, all true": "parse: schema feature not supported by parser",
	"draft7/oneOf/oneOf with boolean schemas, more than one true": "parse: schema feature not supported by parser",
	"draft7/oneOf/oneOf with boolean schemas, one true": "parse: schema feature not supported by parser",
	"draft7/oneOf/oneOf with empty schema": "compile: generated code does not compile",
	"draft7/oneOf/oneOf with missing optional property": "parse: schema feature not supported by parser",
	"draft7/oneOf/oneOf with required": "compile: generated code does not compile",
	"draft7/properties/properties with boolean schema": "parse: schema feature not supported by parser",
	"draft7/properties/properties with escaped characters": "emit: invalid Go identifier from schema naming",
	"draft7/ref/$ref to boolean schema false": "parse: schema feature not supported by parser",
	"draft7/ref/$ref to boolean schema true": "parse: schema feature not supported by parser",
	"draft7/ref/Recursive references between schemas": "compile: generated code does not compile",
	"draft7/ref/URN base URI with URN and anchor ref": "emit: invalid Go identifier from schema naming",
	"draft7/ref/empty tokens in $ref json-pointer": "emit: invalid Go identifier from schema naming",
	"draft7/ref/escaped pointer ref": "emit: invalid Go identifier from schema naming",
	"draft7/ref/property named $ref that is not a reference": "emit: invalid Go identifier from schema naming",
	"draft7/ref/property named $ref, containing an actual $ref": "emit: invalid Go identifier from schema naming",
	"draft7/ref/refs with quote": "emit: invalid Go identifier from schema naming",
	"draft7/ref/relative pointer ref to object": "compile: generated code does not compile",
	"draft7/ref/root pointer ref": "emit: invalid Go identifier from schema naming",
	"draft7/ref/simple URN base URI with $ref via the URN": "emit: invalid Go identifier from schema naming",
	"draft7/refRemote/base URI change - change folder": "compile: generated code does not compile",
	"draft7/refRemote/base URI change - change folder in subschema": "compile: generated code does not compile",
	"draft7/refRemote/retrieved nested refs resolve relative to their URI not $id": "compile: generated code does not compile",
	"draft7/refRemote/root ref in remote ref": "compile: generated code does not compile",
}

// knownRoundTripFailures tracks valid data instances that fail the
// unmarshal -> marshal -> compare round-trip through generated code.
// Total: 324 known failures
var knownRoundTripFailures = map[string]string{
	"draft2019-09/additionalProperties/additionalProperties are allowed by default/additional properties are allowed": "round-trip: compilation or execution error",
	"draft2019-09/additionalProperties/additionalProperties being false does not allow other properties/patternProperties are not additional properties": "round-trip: compilation or execution error",
	"draft2019-09/anyOf/anyOf complex types/both anyOf valid (complex)": "no root struct type in generated code",
	"draft2019-09/anyOf/anyOf complex types/first anyOf valid (complex)": "no root struct type in generated code",
	"draft2019-09/anyOf/anyOf complex types/second anyOf valid (complex)": "no root struct type in generated code",
	"draft2019-09/dependentSchemas/dependent subschema incompatible with root/matches dependency": "round-trip: compilation or execution error",
	"draft2019-09/dependentSchemas/dependent subschema incompatible with root/no dependency": "round-trip: compilation or execution error",
	"draft2019-09/not/forbidden property/property absent": "round-trip: compilation or execution error",
	"draft2019-09/oneOf/oneOf complex types/first oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft2019-09/oneOf/oneOf complex types/second oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft2019-09/oneOf/oneOf with missing optional property/first oneOf valid": "parse: schema feature not supported",
	"draft2019-09/oneOf/oneOf with missing optional property/second oneOf valid": "parse: schema feature not supported",
	"draft2019-09/oneOf/oneOf with required/first valid - valid": "round-trip: compilation or execution error",
	"draft2019-09/oneOf/oneOf with required/second valid - valid": "round-trip: compilation or execution error",
	"draft2019-09/properties/object properties validation/doesn't invalidate other properties": "round-trip: compilation or execution error",
	"draft2019-09/properties/properties with boolean schema/no property present is valid": "parse: schema feature not supported",
	"draft2019-09/properties/properties with boolean schema/only 'true' property present is valid": "parse: schema feature not supported",
	"draft2019-09/properties/properties with escaped characters/object with all numbers is valid": "emit: code generation error",
	"draft2019-09/properties/properties with null valued instance properties/allows null values": "round-trip: compilation or execution error",
	"draft2019-09/properties/properties, patternProperties, additionalProperties interaction/additionalProperty ignores property": "round-trip: compilation or execution error",
	"draft2019-09/properties/properties, patternProperties, additionalProperties interaction/patternProperty validates nonproperty": "round-trip: compilation or execution error",
	"draft2019-09/recursiveRef/$recursiveRef with $recursiveAnchor: false works like $ref/single level match": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with $recursiveAnchor: false works like $ref/two levels, properties match with inner definition": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with nesting/integer now matches as a property value": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with nesting/single level match": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with nesting/two levels, properties match with $recursiveRef": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with nesting/two levels, properties match with inner definition": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with no $recursiveAnchor in the initial target schema resource/leaf node matches: recursion uses the inner schema": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with no $recursiveAnchor in the outer schema resource/leaf node matches: recursion only uses inner schema": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with no $recursiveAnchor works like $ref/single level match": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef with no $recursiveAnchor works like $ref/two levels, properties match with inner definition": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef without using nesting/single level match": "no root struct type in generated code",
	"draft2019-09/recursiveRef/$recursiveRef without using nesting/two levels, properties match with inner definition": "no root struct type in generated code",
	"draft2019-09/ref/Recursive references between schemas/valid tree": "round-trip: compilation or execution error",
	"draft2019-09/ref/URN base URI with URN and anchor ref/a string is valid": "emit: code generation error",
	"draft2019-09/ref/escaped pointer ref/percent valid": "emit: code generation error",
	"draft2019-09/ref/escaped pointer ref/slash valid": "emit: code generation error",
	"draft2019-09/ref/escaped pointer ref/tilde valid": "emit: code generation error",
	"draft2019-09/ref/property named $ref that is not a reference/property named $ref valid": "emit: code generation error",
	"draft2019-09/ref/property named $ref, containing an actual $ref/property named $ref valid": "emit: code generation error",
	"draft2019-09/ref/ref applies alongside sibling keywords/ref valid, maxItems valid": "round-trip: compilation or execution error",
	"draft2019-09/ref/refs with quote/object with numbers is valid": "emit: code generation error",
	"draft2019-09/ref/refs with relative uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft2019-09/ref/relative pointer ref to object/match": "round-trip: compilation or execution error",
	"draft2019-09/ref/relative refs with absolute uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft2019-09/ref/root pointer ref/match": "emit: code generation error",
	"draft2019-09/ref/root pointer ref/recursive match": "emit: code generation error",
	"draft2019-09/ref/simple URN base URI with $ref via the URN/valid under the URN IDed schema": "emit: code generation error",
	"draft2019-09/refRemote/base URI change - change folder in subschema/number is valid": "round-trip: compilation or execution error",
	"draft2019-09/refRemote/base URI change - change folder/number is valid": "round-trip: compilation or execution error",
	"draft2019-09/refRemote/retrieved nested refs resolve relative to their URI not $id/string is valid": "round-trip: compilation or execution error",
	"draft2019-09/refRemote/root ref in remote ref/null is valid": "round-trip: compilation or execution error",
	"draft2019-09/refRemote/root ref in remote ref/string is valid": "round-trip: compilation or execution error",
	"draft2019-09/type/object type matches objects/an object is an object": "no root struct type in generated code",
	"draft2019-09/unevaluatedItems/item is evaluated in an uncle schema to unevaluatedItems/no extra items": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dependentSchemas with unevaluatedProperties/unevaluatedProperties sees bar when foo2 is present": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/a is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/all + foo is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/all is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/b is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/c is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/d is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/xx + foox is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/dynamic evalation inside nested refs/xx is valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/in-place applicator siblings, allOf has unevaluated/in place applicator siblings, bar is missing": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/in-place applicator siblings, anyOf has unevaluated/in place applicator siblings, foo is missing": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/nested unevaluatedProperties, outer false, inner true, properties inside/with nested unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/nested unevaluatedProperties, outer false, inner true, properties outside/with nested unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and b and x are valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and b and y are valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and x are valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and y are valid": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Deep nested is valid": "emit: code generation error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Empty is valid": "emit: code generation error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Nested is valid": "emit: code generation error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Single is valid": "emit: code generation error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties before $ref/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties false/with no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties schema/with no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties schema/with valid unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties true/with no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties true/with unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with $recursiveRef/with no unevaluated properties": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with $ref/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with adjacent patternProperties/with no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with anyOf/when one matches and has no unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with anyOf/when two match and has no unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with boolean schemas/with no unevaluated properties": "parse: schema feature not supported",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with dependentSchemas/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with if/then/else, else not defined/when if is true and has no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with if/then/else, then not defined/when if is false and has no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with if/then/else, then not defined/when if is true and has no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with if/then/else/when if is false and has no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with if/then/else/when if is true and has no unevaluated properties": "no root struct type in generated code",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with nested additionalProperties/with additional properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with nested patternProperties/with no additional properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with nested unevaluatedProperties/with nested unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/unevaluatedProperties/unevaluatedProperties with oneOf/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2019-09/vocabulary/schema that uses custom metaschema with with no validation vocabulary/no validation: invalid number, but it still validates": "parse: schema feature not supported",
	"draft2019-09/vocabulary/schema that uses custom metaschema with with no validation vocabulary/no validation: valid number": "parse: schema feature not supported",
	"draft2020-12/additionalProperties/additionalProperties are allowed by default/additional properties are allowed": "round-trip: compilation or execution error",
	"draft2020-12/additionalProperties/additionalProperties being false does not allow other properties/patternProperties are not additional properties": "round-trip: compilation or execution error",
	"draft2020-12/anyOf/anyOf complex types/both anyOf valid (complex)": "no root struct type in generated code",
	"draft2020-12/anyOf/anyOf complex types/first anyOf valid (complex)": "no root struct type in generated code",
	"draft2020-12/anyOf/anyOf complex types/second anyOf valid (complex)": "no root struct type in generated code",
	"draft2020-12/dependentSchemas/dependent subschema incompatible with root/matches dependency": "round-trip: compilation or execution error",
	"draft2020-12/dependentSchemas/dependent subschema incompatible with root/no dependency": "round-trip: compilation or execution error",
	"draft2020-12/dynamicRef/$dynamicRef points to a boolean schema/follow $dynamicRef to a true schema": "parse: schema feature not supported",
	"draft2020-12/dynamicRef/$dynamicRef skips over intermediate resources - direct reference/integer property passes": "round-trip: compilation or execution error",
	"draft2020-12/dynamicRef/$ref and $dynamicAnchor are independent of order - $defs first/correct extended schema": "parse: schema feature not supported",
	"draft2020-12/dynamicRef/$ref and $dynamicAnchor are independent of order - $ref first/correct extended schema": "parse: schema feature not supported",
	"draft2020-12/dynamicRef/A $dynamicRef that initially resolves to a schema with a matching $dynamicAnchor resolves to the first $dynamicAnchor in the dynamic scope/The recursive part is valid against the root": "round-trip: compilation or execution error",
	"draft2020-12/dynamicRef/A $dynamicRef that initially resolves to a schema without a matching $dynamicAnchor behaves like a normal $ref to $anchor/The recursive part doesn't need to validate against the root": "round-trip: compilation or execution error",
	"draft2020-12/not/forbidden property/property absent": "round-trip: compilation or execution error",
	"draft2020-12/oneOf/oneOf complex types/first oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft2020-12/oneOf/oneOf complex types/second oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft2020-12/oneOf/oneOf with missing optional property/first oneOf valid": "parse: schema feature not supported",
	"draft2020-12/oneOf/oneOf with missing optional property/second oneOf valid": "parse: schema feature not supported",
	"draft2020-12/oneOf/oneOf with required/first valid - valid": "round-trip: compilation or execution error",
	"draft2020-12/oneOf/oneOf with required/second valid - valid": "round-trip: compilation or execution error",
	"draft2020-12/properties/object properties validation/doesn't invalidate other properties": "round-trip: compilation or execution error",
	"draft2020-12/properties/properties with boolean schema/no property present is valid": "parse: schema feature not supported",
	"draft2020-12/properties/properties with boolean schema/only 'true' property present is valid": "parse: schema feature not supported",
	"draft2020-12/properties/properties with escaped characters/object with all numbers is valid": "emit: code generation error",
	"draft2020-12/properties/properties with null valued instance properties/allows null values": "round-trip: compilation or execution error",
	"draft2020-12/properties/properties, patternProperties, additionalProperties interaction/additionalProperty ignores property": "round-trip: compilation or execution error",
	"draft2020-12/properties/properties, patternProperties, additionalProperties interaction/patternProperty validates nonproperty": "round-trip: compilation or execution error",
	"draft2020-12/ref/Recursive references between schemas/valid tree": "round-trip: compilation or execution error",
	"draft2020-12/ref/URN base URI with URN and anchor ref/a string is valid": "emit: code generation error",
	"draft2020-12/ref/escaped pointer ref/percent valid": "emit: code generation error",
	"draft2020-12/ref/escaped pointer ref/slash valid": "emit: code generation error",
	"draft2020-12/ref/escaped pointer ref/tilde valid": "emit: code generation error",
	"draft2020-12/ref/property named $ref that is not a reference/property named $ref valid": "emit: code generation error",
	"draft2020-12/ref/property named $ref, containing an actual $ref/property named $ref valid": "emit: code generation error",
	"draft2020-12/ref/ref applies alongside sibling keywords/ref valid, maxItems valid": "round-trip: compilation or execution error",
	"draft2020-12/ref/refs with quote/object with numbers is valid": "emit: code generation error",
	"draft2020-12/ref/refs with relative uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft2020-12/ref/relative pointer ref to object/match": "round-trip: compilation or execution error",
	"draft2020-12/ref/relative refs with absolute uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft2020-12/ref/root pointer ref/match": "emit: code generation error",
	"draft2020-12/ref/root pointer ref/recursive match": "emit: code generation error",
	"draft2020-12/ref/simple URN base URI with $ref via the URN/valid under the URN IDed schema": "emit: code generation error",
	"draft2020-12/refRemote/base URI change - change folder in subschema/number is valid": "round-trip: compilation or execution error",
	"draft2020-12/refRemote/base URI change - change folder/number is valid": "round-trip: compilation or execution error",
	"draft2020-12/refRemote/retrieved nested refs resolve relative to their URI not $id/string is valid": "round-trip: compilation or execution error",
	"draft2020-12/refRemote/root ref in remote ref/null is valid": "round-trip: compilation or execution error",
	"draft2020-12/refRemote/root ref in remote ref/string is valid": "round-trip: compilation or execution error",
	"draft2020-12/type/object type matches objects/an object is an object": "no root struct type in generated code",
	"draft2020-12/unevaluatedItems/item is evaluated in an uncle schema to unevaluatedItems/no extra items": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dependentSchemas with unevaluatedProperties/unevaluatedProperties sees bar when foo2 is present": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/a is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/all + foo is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/all is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/b is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/c is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/d is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/xx + foox is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/dynamic evalation inside nested refs/xx is valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/in-place applicator siblings, allOf has unevaluated/in place applicator siblings, bar is missing": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/in-place applicator siblings, anyOf has unevaluated/in place applicator siblings, foo is missing": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/nested unevaluatedProperties, outer false, inner true, properties inside/with nested unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/nested unevaluatedProperties, outer false, inner true, properties outside/with nested unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and b and x are valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and b and y are valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and x are valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + ref inside allOf / oneOf/a and y are valid": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Deep nested is valid": "emit: code generation error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Empty is valid": "emit: code generation error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Nested is valid": "emit: code generation error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties + single cyclic ref/Single is valid": "emit: code generation error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties before $ref/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with $ref/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with anyOf/when one matches and has no unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with anyOf/when two match and has no unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with boolean schemas/with no unevaluated properties": "parse: schema feature not supported",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with dependentSchemas/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with nested additionalProperties/with additional properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with nested patternProperties/with no additional properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with nested unevaluatedProperties/with nested unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/unevaluatedProperties/unevaluatedProperties with oneOf/with no unevaluated properties": "round-trip: compilation or execution error",
	"draft2020-12/vocabulary/schema that uses custom metaschema with with no validation vocabulary/no validation: invalid number, but it still validates": "parse: schema feature not supported",
	"draft2020-12/vocabulary/schema that uses custom metaschema with with no validation vocabulary/no validation: valid number": "parse: schema feature not supported",
	"draft3/additionalProperties/additionalProperties are allowed by default/additional properties are allowed": "round-trip: compilation or execution error",
	"draft3/additionalProperties/additionalProperties being false does not allow other properties/patternProperties are not additional properties": "round-trip: compilation or execution error",
	"draft3/enum/enums in properties/both properties are valid": "parse: schema feature not supported",
	"draft3/enum/enums in properties/missing optional property is valid": "parse: schema feature not supported",
	"draft3/extends/extends/extends": "parse: schema feature not supported",
	"draft3/extends/multiple extends/valid": "parse: schema feature not supported",
	"draft3/properties/object properties validation/doesn't invalidate other properties": "round-trip: compilation or execution error",
	"draft3/properties/properties with null valued instance properties/allows null values": "round-trip: compilation or execution error",
	"draft3/properties/properties, patternProperties, additionalProperties interaction/additionalProperty ignores property": "round-trip: compilation or execution error",
	"draft3/properties/properties, patternProperties, additionalProperties interaction/patternProperty validates nonproperty": "round-trip: compilation or execution error",
	"draft3/ref/escaped pointer ref/percent valid": "emit: code generation error",
	"draft3/ref/escaped pointer ref/slash valid": "emit: code generation error",
	"draft3/ref/escaped pointer ref/tilde valid": "emit: code generation error",
	"draft3/ref/property named $ref, containing an actual $ref/property named $ref valid": "emit: code generation error",
	"draft3/ref/ref overrides any sibling keywords/remote ref valid": "round-trip: compilation or execution error",
	"draft3/ref/relative pointer ref to object/match": "round-trip: compilation or execution error",
	"draft3/ref/root pointer ref/match": "emit: code generation error",
	"draft3/ref/root pointer ref/recursive match": "emit: code generation error",
	"draft3/required/required explicitly false validation/not required if required is false": "parse: schema feature not supported",
	"draft3/required/required validation/present required property is valid": "parse: schema feature not supported",
	"draft3/type/object type matches objects/an object is an object": "no root struct type in generated code",
	"draft4/additionalProperties/additionalProperties are allowed by default/additional properties are allowed": "round-trip: compilation or execution error",
	"draft4/additionalProperties/additionalProperties being false does not allow other properties/patternProperties are not additional properties": "round-trip: compilation or execution error",
	"draft4/anyOf/anyOf complex types/both anyOf valid (complex)": "no root struct type in generated code",
	"draft4/anyOf/anyOf complex types/first anyOf valid (complex)": "no root struct type in generated code",
	"draft4/anyOf/anyOf complex types/second anyOf valid (complex)": "no root struct type in generated code",
	"draft4/dependencies/dependent subschema incompatible with root/matches dependency": "round-trip: compilation or execution error",
	"draft4/dependencies/dependent subschema incompatible with root/no dependency": "round-trip: compilation or execution error",
	"draft4/not/forbidden property/property absent": "round-trip: compilation or execution error",
	"draft4/oneOf/oneOf complex types/first oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft4/oneOf/oneOf complex types/second oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft4/oneOf/oneOf with missing optional property/first oneOf valid": "round-trip: compilation or execution error",
	"draft4/oneOf/oneOf with missing optional property/second oneOf valid": "round-trip: compilation or execution error",
	"draft4/oneOf/oneOf with required/first valid - valid": "round-trip: compilation or execution error",
	"draft4/oneOf/oneOf with required/second valid - valid": "round-trip: compilation or execution error",
	"draft4/properties/object properties validation/doesn't invalidate other properties": "round-trip: compilation or execution error",
	"draft4/properties/properties with escaped characters/object with all numbers is valid": "emit: code generation error",
	"draft4/properties/properties with null valued instance properties/allows null values": "round-trip: compilation or execution error",
	"draft4/properties/properties, patternProperties, additionalProperties interaction/additionalProperty ignores property": "round-trip: compilation or execution error",
	"draft4/properties/properties, patternProperties, additionalProperties interaction/patternProperty validates nonproperty": "round-trip: compilation or execution error",
	"draft4/ref/Recursive references between schemas/valid tree": "round-trip: compilation or execution error",
	"draft4/ref/escaped pointer ref/percent valid": "emit: code generation error",
	"draft4/ref/escaped pointer ref/slash valid": "emit: code generation error",
	"draft4/ref/escaped pointer ref/tilde valid": "emit: code generation error",
	"draft4/ref/property named $ref that is not a reference/property named $ref valid": "emit: code generation error",
	"draft4/ref/property named $ref, containing an actual $ref/property named $ref valid": "emit: code generation error",
	"draft4/ref/ref overrides any sibling keywords/ref valid": "round-trip: compilation or execution error",
	"draft4/ref/refs with quote/object with numbers is valid": "emit: code generation error",
	"draft4/ref/relative pointer ref to object/match": "round-trip: compilation or execution error",
	"draft4/ref/root pointer ref/match": "emit: code generation error",
	"draft4/ref/root pointer ref/recursive match": "emit: code generation error",
	"draft4/refRemote/base URI change - change folder in subschema/number is valid": "round-trip: compilation or execution error",
	"draft4/refRemote/base URI change - change folder/number is valid": "round-trip: compilation or execution error",
	"draft4/refRemote/root ref in remote ref/null is valid": "round-trip: compilation or execution error",
	"draft4/refRemote/root ref in remote ref/string is valid": "round-trip: compilation or execution error",
	"draft4/type/object type matches objects/an object is an object": "no root struct type in generated code",
	"draft6/additionalProperties/additionalProperties are allowed by default/additional properties are allowed": "round-trip: compilation or execution error",
	"draft6/additionalProperties/additionalProperties being false does not allow other properties/patternProperties are not additional properties": "round-trip: compilation or execution error",
	"draft6/anyOf/anyOf complex types/both anyOf valid (complex)": "no root struct type in generated code",
	"draft6/anyOf/anyOf complex types/first anyOf valid (complex)": "no root struct type in generated code",
	"draft6/anyOf/anyOf complex types/second anyOf valid (complex)": "no root struct type in generated code",
	"draft6/dependencies/dependent subschema incompatible with root/matches dependency": "round-trip: compilation or execution error",
	"draft6/dependencies/dependent subschema incompatible with root/no dependency": "round-trip: compilation or execution error",
	"draft6/not/forbidden property/property absent": "round-trip: compilation or execution error",
	"draft6/oneOf/oneOf complex types/first oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft6/oneOf/oneOf complex types/second oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft6/oneOf/oneOf with missing optional property/first oneOf valid": "parse: schema feature not supported",
	"draft6/oneOf/oneOf with missing optional property/second oneOf valid": "parse: schema feature not supported",
	"draft6/oneOf/oneOf with required/first valid - valid": "round-trip: compilation or execution error",
	"draft6/oneOf/oneOf with required/second valid - valid": "round-trip: compilation or execution error",
	"draft6/properties/object properties validation/doesn't invalidate other properties": "round-trip: compilation or execution error",
	"draft6/properties/properties with boolean schema/no property present is valid": "parse: schema feature not supported",
	"draft6/properties/properties with boolean schema/only 'true' property present is valid": "parse: schema feature not supported",
	"draft6/properties/properties with escaped characters/object with all numbers is valid": "emit: code generation error",
	"draft6/properties/properties with null valued instance properties/allows null values": "round-trip: compilation or execution error",
	"draft6/properties/properties, patternProperties, additionalProperties interaction/additionalProperty ignores property": "round-trip: compilation or execution error",
	"draft6/properties/properties, patternProperties, additionalProperties interaction/patternProperty validates nonproperty": "round-trip: compilation or execution error",
	"draft6/ref/Recursive references between schemas/valid tree": "round-trip: compilation or execution error",
	"draft6/ref/URN base URI with URN and anchor ref/a string is valid": "emit: code generation error",
	"draft6/ref/escaped pointer ref/percent valid": "emit: code generation error",
	"draft6/ref/escaped pointer ref/slash valid": "emit: code generation error",
	"draft6/ref/escaped pointer ref/tilde valid": "emit: code generation error",
	"draft6/ref/property named $ref that is not a reference/property named $ref valid": "emit: code generation error",
	"draft6/ref/property named $ref, containing an actual $ref/property named $ref valid": "emit: code generation error",
	"draft6/ref/ref overrides any sibling keywords/ref valid": "round-trip: compilation or execution error",
	"draft6/ref/refs with quote/object with numbers is valid": "emit: code generation error",
	"draft6/ref/refs with relative uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft6/ref/relative pointer ref to object/match": "round-trip: compilation or execution error",
	"draft6/ref/relative refs with absolute uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft6/ref/root pointer ref/match": "emit: code generation error",
	"draft6/ref/root pointer ref/recursive match": "emit: code generation error",
	"draft6/ref/simple URN base URI with $ref via the URN/valid under the URN IDed schema": "emit: code generation error",
	"draft6/refRemote/base URI change - change folder in subschema/number is valid": "round-trip: compilation or execution error",
	"draft6/refRemote/base URI change - change folder/number is valid": "round-trip: compilation or execution error",
	"draft6/refRemote/remote ref with ref to definitions/valid": "round-trip: compilation or execution error",
	"draft6/refRemote/retrieved nested refs resolve relative to their URI not $id/string is valid": "round-trip: compilation or execution error",
	"draft6/refRemote/root ref in remote ref/null is valid": "round-trip: compilation or execution error",
	"draft6/refRemote/root ref in remote ref/string is valid": "round-trip: compilation or execution error",
	"draft6/type/object type matches objects/an object is an object": "no root struct type in generated code",
	"draft7/additionalProperties/additionalProperties are allowed by default/additional properties are allowed": "round-trip: compilation or execution error",
	"draft7/additionalProperties/additionalProperties being false does not allow other properties/patternProperties are not additional properties": "round-trip: compilation or execution error",
	"draft7/anyOf/anyOf complex types/both anyOf valid (complex)": "no root struct type in generated code",
	"draft7/anyOf/anyOf complex types/first anyOf valid (complex)": "no root struct type in generated code",
	"draft7/anyOf/anyOf complex types/second anyOf valid (complex)": "no root struct type in generated code",
	"draft7/dependencies/dependent subschema incompatible with root/matches dependency": "round-trip: compilation or execution error",
	"draft7/dependencies/dependent subschema incompatible with root/no dependency": "round-trip: compilation or execution error",
	"draft7/not/forbidden property/property absent": "round-trip: compilation or execution error",
	"draft7/oneOf/oneOf complex types/first oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft7/oneOf/oneOf complex types/second oneOf valid (complex)": "round-trip: compilation or execution error",
	"draft7/oneOf/oneOf with missing optional property/first oneOf valid": "parse: schema feature not supported",
	"draft7/oneOf/oneOf with missing optional property/second oneOf valid": "parse: schema feature not supported",
	"draft7/oneOf/oneOf with required/first valid - valid": "round-trip: compilation or execution error",
	"draft7/oneOf/oneOf with required/second valid - valid": "round-trip: compilation or execution error",
	"draft7/properties/object properties validation/doesn't invalidate other properties": "round-trip: compilation or execution error",
	"draft7/properties/properties with boolean schema/no property present is valid": "parse: schema feature not supported",
	"draft7/properties/properties with boolean schema/only 'true' property present is valid": "parse: schema feature not supported",
	"draft7/properties/properties with escaped characters/object with all numbers is valid": "emit: code generation error",
	"draft7/properties/properties with null valued instance properties/allows null values": "round-trip: compilation or execution error",
	"draft7/properties/properties, patternProperties, additionalProperties interaction/additionalProperty ignores property": "round-trip: compilation or execution error",
	"draft7/properties/properties, patternProperties, additionalProperties interaction/patternProperty validates nonproperty": "round-trip: compilation or execution error",
	"draft7/ref/Recursive references between schemas/valid tree": "round-trip: compilation or execution error",
	"draft7/ref/URN base URI with URN and anchor ref/a string is valid": "emit: code generation error",
	"draft7/ref/escaped pointer ref/percent valid": "emit: code generation error",
	"draft7/ref/escaped pointer ref/slash valid": "emit: code generation error",
	"draft7/ref/escaped pointer ref/tilde valid": "emit: code generation error",
	"draft7/ref/property named $ref that is not a reference/property named $ref valid": "emit: code generation error",
	"draft7/ref/property named $ref, containing an actual $ref/property named $ref valid": "emit: code generation error",
	"draft7/ref/ref overrides any sibling keywords/ref valid": "round-trip: compilation or execution error",
	"draft7/ref/refs with quote/object with numbers is valid": "emit: code generation error",
	"draft7/ref/refs with relative uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft7/ref/relative pointer ref to object/match": "round-trip: compilation or execution error",
	"draft7/ref/relative refs with absolute uris and defs/valid on both fields": "round-trip: compilation or execution error",
	"draft7/ref/root pointer ref/match": "emit: code generation error",
	"draft7/ref/root pointer ref/recursive match": "emit: code generation error",
	"draft7/ref/simple URN base URI with $ref via the URN/valid under the URN IDed schema": "emit: code generation error",
	"draft7/refRemote/base URI change - change folder in subschema/number is valid": "round-trip: compilation or execution error",
	"draft7/refRemote/base URI change - change folder/number is valid": "round-trip: compilation or execution error",
	"draft7/refRemote/remote ref with ref to definitions/valid": "round-trip: compilation or execution error",
	"draft7/refRemote/retrieved nested refs resolve relative to their URI not $id/string is valid": "round-trip: compilation or execution error",
	"draft7/refRemote/root ref in remote ref/null is valid": "round-trip: compilation or execution error",
	"draft7/refRemote/root ref in remote ref/string is valid": "round-trip: compilation or execution error",
	"draft7/type/object type matches objects/an object is an object": "no root struct type in generated code",
}
