// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type Employee struct {
	Department           string                     `json:"department,omitempty"`
	Email                string                     `json:"email,omitempty"`
	EmployeeID           string                     `json:"employee_id"`
	Name                 string                     `json:"name"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (e *Employee) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Employee")
	}
	type Alias Employee
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(e),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"employee_id", "name"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"department":  true,
			"email":       true,
			"employee_id": true,
			"name":        true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if e.AdditionalProperties == nil {
				e.AdditionalProperties = make(map[string]json.RawMessage)
			}
			e.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (e Employee) MarshalJSON() ([]byte, error) {
	type Alias Employee
	aux := struct {
		Alias
	}{
		Alias: (Alias)(e),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range e.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks Employee against its JSON Schema constraints.
func (e Employee) Validate() error {
	return nil
}
