// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
	rt "github.com/mgilbir/schemagen/runtime"
)

// This file needs the runtime module github.com/mgilbir/schemagen/runtime at API
// level 1 or newer. If the compiler reports rt.API1 undefined, the release the
// build resolved is older than the schemagen that generated this file: update it
// with go get github.com/mgilbir/schemagen/runtime@latest.
var _ rt.API1

type SearchResultResult struct {
	Description          *string                    `json:"description,omitempty"`
	Name                 *string                    `json:"name,omitempty"`
	Title                *string                    `json:"title,omitempty"`
	URL                  *string                    `json:"url,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
	_doc                 *rt.Doc                    // set by UnmarshalJSON: the document the raw members are views of, which Validate reads them through
}

// UnmarshalJSON replaces s with the value the document holds. See
// decodeJSONAt.
func (s *SearchResultResult) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(s.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks SearchResultResult as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (s *SearchResultResult) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into s, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever s held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (s *SearchResultResult) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*s = SearchResultResult{}
	s._doc = _d
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*SearchResultResult)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["description"]; _ok {
		if _err := func(_p **string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[*string](_p, _d, _s, rt.DecodeValue[*string])
		}(&s.Description, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "description")
		}
	}
	if _v, _ok := _raw["name"]; _ok {
		if _err := func(_p **string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[*string](_p, _d, _s, rt.DecodeValue[*string])
		}(&s.Name, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "name")
		}
	}
	if _v, _ok := _raw["title"]; _ok {
		if _err := func(_p **string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[*string](_p, _d, _s, rt.DecodeValue[*string])
		}(&s.Title, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "title")
		}
	}
	if _v, _ok := _raw["url"]; _ok {
		if _err := func(_p **string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[*string](_p, _d, _s, rt.DecodeValue[*string])
		}(&s.URL, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "url")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"description",
		"name",
		"title",
		"url",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	s._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		s._jsonKeys[_k] = true
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See rt.Doc.Keep.
	if _d.First(_sp) == '{' {
		s._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			s._jsonRawProps[_k] = _d.Keep(_v)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "description", "name", "title", "url":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	s.AdditionalProperties = _apFiled

	return nil
}
func (s SearchResultResult) MarshalJSON() ([]byte, error) {
	_b, _err := s.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends s to _b as JSON. See rt.Enc.
func (s SearchResultResult) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := s.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range s.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, s.appendMemberJSON)
}

// encodeFieldsJSON gathers the members s's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (s SearchResultResult) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(s.Description)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("description", _v)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitEmpty(s.Name)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("name", _v)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitEmpty(s.Title)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("title", _v)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitEmpty(s.URL)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("url", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of s numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (s SearchResultResult) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks SearchResultResult against its JSON Schema constraints.
func (s SearchResultResult) Validate() error {
	// object-level anyOf: at least one flattened variant must match.
	// This check depends on JSON key presence (_jsonKeys), so it is skipped
	// for hand-constructed values (nil _jsonKeys), consistent with how the
	// required-property check above treats untracked presence.
	if s._jsonKeys != nil {
		_anyOfMatches := 0
		{
			_branchMatches := true
			if _branchMatches {
				if _raw, _ok := s._jsonRawProps["title"]; _ok {
					_jt := rt.RawKind(_raw, false)
					if _jt != "string" {
						_branchMatches = false
					}
				}
			}
			if _branchMatches {
				if _raw, _ok := s._jsonRawProps["url"]; _ok {
					_jt := rt.RawKind(_raw, false)
					if _jt != "string" {
						_branchMatches = false
					}
				}
			}
			if _branchMatches {
				_anyOfMatches++
			}
		}
		{
			_branchMatches := true
			if _branchMatches {
				if _raw, _ok := s._jsonRawProps["description"]; _ok {
					_jt := rt.RawKind(_raw, false)
					if _jt != "string" {
						_branchMatches = false
					}
				}
			}
			if _branchMatches {
				if _raw, _ok := s._jsonRawProps["name"]; _ok {
					_jt := rt.RawKind(_raw, false)
					if _jt != "string" {
						_branchMatches = false
					}
				}
			}
			if _branchMatches {
				_anyOfMatches++
			}
		}
		if _anyOfMatches < 1 {
			return fmt.Errorf("anyOf: no variant matched")
		}
	}
	return nil
}

type SearchResult struct {
	Result               *SearchResultResult        `json:"result,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	ID                   string                     `json:"id"`
}

// UnmarshalJSON replaces s with the value the document holds. See
// decodeJSONAt.
func (s *SearchResult) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(s.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks SearchResult as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (s *SearchResult) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into s, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever s held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (s *SearchResult) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*s = SearchResult{}
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*SearchResult)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["id"]; _ok {
		if _err := func(_p *string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[string](_p, _d, _s, rt.DecodeValue[string])
		}(&s.ID, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "id")
		}
	}
	if _v, _ok := _raw["result"]; _ok {
		if _err := func(_p **SearchResultResult, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **SearchResultResult, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(SearchResultResult)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&s.Result, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "result")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"id",
		"result",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	s._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		s._jsonKeys[_k] = true
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "id", "result":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	s.AdditionalProperties = _apFiled

	return nil
}
func (s SearchResult) MarshalJSON() ([]byte, error) {
	_b, _err := s.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends s to _b as JSON. See rt.Enc.
func (s SearchResult) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := s.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range s.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, s.appendMemberJSON)
}

// encodeFieldsJSON gathers the members s's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (s SearchResult) encodeFieldsJSON(_o *rt.Obj) error {
	{
		if !rt.IsEmpty(s.Result) {
			_o.Deferred("result", 0)
		}
	}
	{
		_v, _err := rt.AppendLeaf(s.ID, nil)
		if _err != nil {
			return _err
		}
		_o.Encoded("id", _v)
	}
	return nil
}

// appendMemberJSON writes the member of s numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (s SearchResult) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	case 0:
		return (func(_v *SearchResultResult, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*SearchResultResult)(nil), true)
			}
			return _out, nil
		})(s.Result, _b)
	}
	return _b, nil
}

// Validate checks SearchResult against its JSON Schema constraints.
func (s SearchResult) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if s._jsonKeys != nil {
		for _, _req := range []string{"id"} {
			if !s._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	if s.Result != nil {
		if err := s.Result.Validate(); err != nil {
			return rt.Pathf(err, "result")
		}
	}
	return nil
}
