// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type EmailTarget struct {
	EmailAddress         string                     `json:"email_address"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (e *EmailTarget) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type EmailTarget")
	}
	type Alias EmailTarget
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(e),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"email_address"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"email_address": true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if e.AdditionalProperties == nil {
				e.AdditionalProperties = make(map[string]json.RawMessage)
			}
			e.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (e EmailTarget) MarshalJSON() ([]byte, error) {
	type Alias EmailTarget
	aux := struct {
		Alias
	}{
		Alias: (Alias)(e),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range e.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks EmailTarget against its JSON Schema constraints.
func (e EmailTarget) Validate() error {
	return nil
}

type HTMLContent struct {
	HTML                 string                     `json:"html"`
	Subject              string                     `json:"subject,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (h *HTMLContent) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type HTMLContent")
	}
	type Alias HTMLContent
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(h),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"html"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"html":    true,
			"subject": true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if h.AdditionalProperties == nil {
				h.AdditionalProperties = make(map[string]json.RawMessage)
			}
			h.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (h HTMLContent) MarshalJSON() ([]byte, error) {
	type Alias HTMLContent
	aux := struct {
		Alias
	}{
		Alias: (Alias)(h),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range h.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks HTMLContent against its JSON Schema constraints.
func (h HTMLContent) Validate() error {
	return nil
}

type SmsTarget struct {
	PhoneNumber          string                     `json:"phone_number"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (s *SmsTarget) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type SmsTarget")
	}
	type Alias SmsTarget
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(s),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"phone_number"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"phone_number": true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if s.AdditionalProperties == nil {
				s.AdditionalProperties = make(map[string]json.RawMessage)
			}
			s.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (s SmsTarget) MarshalJSON() ([]byte, error) {
	type Alias SmsTarget
	aux := struct {
		Alias
	}{
		Alias: (Alias)(s),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range s.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks SmsTarget against its JSON Schema constraints.
func (s SmsTarget) Validate() error {
	return nil
}

type TextContent struct {
	Body                 string                     `json:"body"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (t *TextContent) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type TextContent")
	}
	type Alias TextContent
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(t),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"body"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"body": true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if t.AdditionalProperties == nil {
				t.AdditionalProperties = make(map[string]json.RawMessage)
			}
			t.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (t TextContent) MarshalJSON() ([]byte, error) {
	type Alias TextContent
	aux := struct {
		Alias
	}{
		Alias: (Alias)(t),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range t.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks TextContent against its JSON Schema constraints.
func (t TextContent) Validate() error {
	return nil
}

type Notification struct {
	ID                   string                     `json:"id"`
	Content              isNotification_Content     `json:"-"`
	Target               isNotification_Target      `json:"-"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// isNotification_Content is a sealed interface for the Content field of Notification.
// Exactly one variant must be set.
type isNotification_Content interface {
	isNotification_Content()
}

// Notification_TextContent wraps *TextContent as a Content variant.
type Notification_TextContent struct {
	TextContent *TextContent
}

func (*Notification_TextContent) isNotification_Content() {}

// Notification_HTMLContent wraps *HTMLContent as a Content variant.
type Notification_HTMLContent struct {
	HTMLContent *HTMLContent
}

func (*Notification_HTMLContent) isNotification_Content() {}

// GetTextContent returns the TextContent variant value, or the zero value if not set.
func (n *Notification) GetTextContent() *TextContent {
	if n != nil {
		if v, ok := n.Content.(*Notification_TextContent); ok {
			return v.TextContent
		}
	}
	var zero *TextContent
	return zero
}

// GetHTMLContent returns the HTMLContent variant value, or the zero value if not set.
func (n *Notification) GetHTMLContent() *HTMLContent {
	if n != nil {
		if v, ok := n.Content.(*Notification_HTMLContent); ok {
			return v.HTMLContent
		}
	}
	var zero *HTMLContent
	return zero
}

// isNotification_Target is a sealed interface for the Target field of Notification.
// Exactly one variant must be set.
type isNotification_Target interface {
	isNotification_Target()
}

// Notification_EmailTarget wraps *EmailTarget as a Target variant.
type Notification_EmailTarget struct {
	EmailTarget *EmailTarget
}

func (*Notification_EmailTarget) isNotification_Target() {}

// Notification_SmsTarget wraps *SmsTarget as a Target variant.
type Notification_SmsTarget struct {
	SmsTarget *SmsTarget
}

func (*Notification_SmsTarget) isNotification_Target() {}

// GetEmailTarget returns the EmailTarget variant value, or the zero value if not set.
func (n *Notification) GetEmailTarget() *EmailTarget {
	if n != nil {
		if v, ok := n.Target.(*Notification_EmailTarget); ok {
			return v.EmailTarget
		}
	}
	var zero *EmailTarget
	return zero
}

// GetSmsTarget returns the SmsTarget variant value, or the zero value if not set.
func (n *Notification) GetSmsTarget() *SmsTarget {
	if n != nil {
		if v, ok := n.Target.(*Notification_SmsTarget); ok {
			return v.SmsTarget
		}
	}
	var zero *SmsTarget
	return zero
}

func (n *Notification) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Notification")
	}
	type Alias Notification
	aux := &struct {
		*Alias
		Content json.RawMessage `json:"content"`
		Target  json.RawMessage `json:"target"`
	}{
		Alias: (*Alias)(n),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	{
		oneofData := aux.Content
		if len(oneofData) > 0 && string(oneofData) != "null" {
			var oneofMatched int
			var oneofLastErr error

			// Try variant: TextContent
			{
				if oneofHasRequiredFields(oneofData, "body") {
					var candidate *TextContent
					if err := json.Unmarshal(oneofData, &candidate); err == nil {
						n.Content = &Notification_TextContent{TextContent: candidate}
						oneofMatched++
					} else {
						oneofLastErr = err
					}
				}
			}

			// Try variant: HTMLContent
			{
				if oneofHasRequiredFields(oneofData, "html") {
					var candidate *HTMLContent
					if err := json.Unmarshal(oneofData, &candidate); err == nil {
						n.Content = &Notification_HTMLContent{HTMLContent: candidate}
						oneofMatched++
					} else {
						oneofLastErr = err
					}
				}
			}

			if oneofMatched == 0 {
				return fmt.Errorf("Notification.Content: no matching oneOf variant: %w", oneofLastErr)
			}
			if oneofMatched > 1 {
				return fmt.Errorf("Notification.Content: multiple oneOf variants matched (%d), expected exactly 1", oneofMatched)
			}
		}
	}

	{
		oneofData := aux.Target
		if len(oneofData) > 0 && string(oneofData) != "null" {
			var oneofMatched int
			var oneofLastErr error

			// Try variant: EmailTarget
			{
				if oneofHasRequiredFields(oneofData, "email_address") {
					var candidate *EmailTarget
					if err := json.Unmarshal(oneofData, &candidate); err == nil {
						n.Target = &Notification_EmailTarget{EmailTarget: candidate}
						oneofMatched++
					} else {
						oneofLastErr = err
					}
				}
			}

			// Try variant: SmsTarget
			{
				if oneofHasRequiredFields(oneofData, "phone_number") {
					var candidate *SmsTarget
					if err := json.Unmarshal(oneofData, &candidate); err == nil {
						n.Target = &Notification_SmsTarget{SmsTarget: candidate}
						oneofMatched++
					} else {
						oneofLastErr = err
					}
				}
			}

			if oneofMatched == 0 {
				return fmt.Errorf("Notification.Target: no matching oneOf variant: %w", oneofLastErr)
			}
			if oneofMatched > 1 {
				return fmt.Errorf("Notification.Target: multiple oneOf variants matched (%d), expected exactly 1", oneofMatched)
			}
		}
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"id"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"id":      true,
			"content": true,
			"target":  true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if n.AdditionalProperties == nil {
				n.AdditionalProperties = make(map[string]json.RawMessage)
			}
			n.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (n Notification) MarshalJSON() ([]byte, error) {
	type Alias Notification
	aux := struct {
		Alias
		Content json.RawMessage `json:"content,omitempty"`
		Target  json.RawMessage `json:"target,omitempty"`
	}{
		Alias: (Alias)(n),
	}

	if n.Content != nil {
		switch v := n.Content.(type) {
		case *Notification_TextContent:
			raw, err := json.Marshal(v.TextContent)
			if err != nil {
				return nil, fmt.Errorf("marshaling Notification.Content: %w", err)
			}
			aux.Content = raw
		case *Notification_HTMLContent:
			raw, err := json.Marshal(v.HTMLContent)
			if err != nil {
				return nil, fmt.Errorf("marshaling Notification.Content: %w", err)
			}
			aux.Content = raw
		}
	}

	if n.Target != nil {
		switch v := n.Target.(type) {
		case *Notification_EmailTarget:
			raw, err := json.Marshal(v.EmailTarget)
			if err != nil {
				return nil, fmt.Errorf("marshaling Notification.Target: %w", err)
			}
			aux.Target = raw
		case *Notification_SmsTarget:
			raw, err := json.Marshal(v.SmsTarget)
			if err != nil {
				return nil, fmt.Errorf("marshaling Notification.Target: %w", err)
			}
			aux.Target = raw
		}
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range n.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks Notification against its JSON Schema constraints.
func (n Notification) Validate() error {
	return nil
}

// oneofHasRequiredFields checks if a JSON object contains all the specified field names.
func oneofHasRequiredFields(data json.RawMessage, fields ...string) bool {
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return false
	}
	for _, f := range fields {
		if _, ok := obj[f]; !ok {
			return false
		}
	}
	return true
}
