// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type FieldBase struct {
	Label                *string                    `json:"label,omitempty"`
	Name                 string                     `json:"name"`
	Type_                string                     `json:"type"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (f *FieldBase) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type FieldBase")
	}
	type Alias FieldBase
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(f),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"name", "type"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"label": true,
			"name":  true,
			"type":  true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if f.AdditionalProperties == nil {
				f.AdditionalProperties = make(map[string]json.RawMessage)
			}
			f.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (f FieldBase) MarshalJSON() ([]byte, error) {
	type Alias FieldBase
	aux := struct {
		Alias
	}{
		Alias: (Alias)(f),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range f.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks FieldBase against its JSON Schema constraints.
func (f FieldBase) Validate() error {
	return nil
}

type DiaryFieldWidget string

const (
	DiaryFieldWidgetSlider DiaryFieldWidget = "slider"
	DiaryFieldWidgetHours  DiaryFieldWidget = "hours"
)

// Validate checks DiaryFieldWidget against its JSON Schema constraints.
func (d DiaryFieldWidget) Validate() error {
	switch d {
	case DiaryFieldWidgetSlider, DiaryFieldWidgetHours:
		return nil
	default:
		return fmt.Errorf("invalid DiaryFieldWidget value: %v", d)
	}
}

type DiaryField struct {
	Choices              *[]string                  `json:"choices,omitempty"`
	Default_             any                        `json:"default,omitempty"`
	Label                *string                    `json:"label,omitempty"`
	Max                  *float64                   `json:"max,omitempty"`
	Min                  *float64                   `json:"min,omitempty"`
	Name                 string                     `json:"name"`
	Type_                string                     `json:"type"`
	Widget               DiaryFieldWidget           `json:"widget,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (d *DiaryField) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type DiaryField")
	}
	type Alias DiaryField
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(d),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"name", "type"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"choices": true,
			"default": true,
			"label":   true,
			"max":     true,
			"min":     true,
			"name":    true,
			"type":    true,
			"widget":  true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if d.AdditionalProperties == nil {
				d.AdditionalProperties = make(map[string]json.RawMessage)
			}
			d.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (d DiaryField) MarshalJSON() ([]byte, error) {
	type Alias DiaryField
	aux := struct {
		Alias
	}{
		Alias: (Alias)(d),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range d.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks DiaryField against its JSON Schema constraints.
func (d DiaryField) Validate() error {
	if d.Widget != "" {
		if err := d.Widget.Validate(); err != nil {
			return fmt.Errorf("widget.%w", err)
		}
	}
	return nil
}
