// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type NarrowingAllOf string

const (
	NarrowingAllOfC NarrowingAllOf = "c"
)

// Validate checks NarrowingAllOf against its JSON Schema constraints.
func (n NarrowingAllOf) Validate() error {
	switch n {
	case NarrowingAllOfC:
		return nil
	default:
		return fmt.Errorf("invalid NarrowingAllOf value: %v", n)
	}
}

type OnlyB string

const (
	OnlyBB OnlyB = "b"
)

// Validate checks OnlyB against its JSON Schema constraints.
func (o OnlyB) Validate() error {
	switch o {
	case OnlyBB:
		return nil
	default:
		return fmt.Errorf("invalid OnlyB value: %v", o)
	}
}

type AllOfSiblingValuesAgrees string

const (
	AllOfSiblingValuesAgreesA AllOfSiblingValuesAgrees = "a"
	AllOfSiblingValuesAgreesB AllOfSiblingValuesAgrees = "b"
)

// Validate checks AllOfSiblingValuesAgrees against its JSON Schema constraints.
func (a AllOfSiblingValuesAgrees) Validate() error {
	switch a {
	case AllOfSiblingValuesAgreesA, AllOfSiblingValuesAgreesB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesAgrees value: %v", a)
	}
}

type AllOfSiblingValuesAllOfThroughRef string

const (
	AllOfSiblingValuesAllOfThroughRefC AllOfSiblingValuesAllOfThroughRef = "c"
)

// Validate checks AllOfSiblingValuesAllOfThroughRef against its JSON Schema constraints.
func (a AllOfSiblingValuesAllOfThroughRef) Validate() error {
	switch a {
	case AllOfSiblingValuesAllOfThroughRefC:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesAllOfThroughRef value: %v", a)
	}
}

type AllOfSiblingValuesBranchNarrows string

const (
	AllOfSiblingValuesBranchNarrowsB AllOfSiblingValuesBranchNarrows = "b"
)

// Validate checks AllOfSiblingValuesBranchNarrows against its JSON Schema constraints.
func (a AllOfSiblingValuesBranchNarrows) Validate() error {
	switch a {
	case AllOfSiblingValuesBranchNarrowsB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesBranchNarrows value: %v", a)
	}
}

type AllOfSiblingValuesChain string

const (
	AllOfSiblingValuesChainB AllOfSiblingValuesChain = "b"
)

// Validate checks AllOfSiblingValuesChain against its JSON Schema constraints.
func (a AllOfSiblingValuesChain) Validate() error {
	switch a {
	case AllOfSiblingValuesChainB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesChain value: %v", a)
	}
}

type AllOfSiblingValuesConstInBranch string

const (
	AllOfSiblingValuesConstInBranchQ AllOfSiblingValuesConstInBranch = "q"
)

// Validate checks AllOfSiblingValuesConstInBranch against its JSON Schema constraints.
func (a AllOfSiblingValuesConstInBranch) Validate() error {
	switch a {
	case AllOfSiblingValuesConstInBranchQ:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesConstInBranch value: %v", a)
	}
}

type AllOfSiblingValuesLaterBranchNarrows string

const (
	AllOfSiblingValuesLaterBranchNarrowsB AllOfSiblingValuesLaterBranchNarrows = "b"
)

// Validate checks AllOfSiblingValuesLaterBranchNarrows against its JSON Schema constraints.
func (a AllOfSiblingValuesLaterBranchNarrows) Validate() error {
	switch a {
	case AllOfSiblingValuesLaterBranchNarrowsB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesLaterBranchNarrows value: %v", a)
	}
}

type AllOfSiblingValuesListItemsItem string

const (
	AllOfSiblingValuesListItemsItemB AllOfSiblingValuesListItemsItem = "b"
)

// Validate checks AllOfSiblingValuesListItemsItem against its JSON Schema constraints.
func (a AllOfSiblingValuesListItemsItem) Validate() error {
	switch a {
	case AllOfSiblingValuesListItemsItemB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesListItemsItem value: %v", a)
	}
}

type AllOfSiblingValuesMapValuesValue string

const (
	AllOfSiblingValuesMapValuesValueB AllOfSiblingValuesMapValuesValue = "b"
)

// Validate checks AllOfSiblingValuesMapValuesValue against its JSON Schema constraints.
func (a AllOfSiblingValuesMapValuesValue) Validate() error {
	switch a {
	case AllOfSiblingValuesMapValuesValueB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesMapValuesValue value: %v", a)
	}
}

type AllOfSiblingValuesNestedChain string

const (
	AllOfSiblingValuesNestedChainC AllOfSiblingValuesNestedChain = "c"
)

// Validate checks AllOfSiblingValuesNestedChain against its JSON Schema constraints.
func (a AllOfSiblingValuesNestedChain) Validate() error {
	switch a {
	case AllOfSiblingValuesNestedChainC:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesNestedChain value: %v", a)
	}
}

type AllOfSiblingValuesNumberSpelling float64

const (
	AllOfSiblingValuesNumberSpelling1 AllOfSiblingValuesNumberSpelling = 1
)

// Validate checks AllOfSiblingValuesNumberSpelling against its JSON Schema constraints.
func (a AllOfSiblingValuesNumberSpelling) Validate() error {
	switch a {
	case AllOfSiblingValuesNumberSpelling1:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesNumberSpelling value: %v", a)
	}
}

type AllOfSiblingValuesRootNarrows string

const (
	AllOfSiblingValuesRootNarrowsB AllOfSiblingValuesRootNarrows = "b"
)

// Validate checks AllOfSiblingValuesRootNarrows against its JSON Schema constraints.
func (a AllOfSiblingValuesRootNarrows) Validate() error {
	switch a {
	case AllOfSiblingValuesRootNarrowsB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesRootNarrows value: %v", a)
	}
}

type AllOfSiblingValuesSilentBranch string

const (
	AllOfSiblingValuesSilentBranchA AllOfSiblingValuesSilentBranch = "a"
	AllOfSiblingValuesSilentBranchB AllOfSiblingValuesSilentBranch = "b"
)

// Validate checks AllOfSiblingValuesSilentBranch against its JSON Schema constraints.
func (a AllOfSiblingValuesSilentBranch) Validate() error {
	switch a {
	case AllOfSiblingValuesSilentBranchA, AllOfSiblingValuesSilentBranchB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesSilentBranch value: %v", a)
	}
}

type AllOfSiblingValuesViaRef string

const (
	AllOfSiblingValuesViaRefB AllOfSiblingValuesViaRef = "b"
)

// Validate checks AllOfSiblingValuesViaRef against its JSON Schema constraints.
func (a AllOfSiblingValuesViaRef) Validate() error {
	switch a {
	case AllOfSiblingValuesViaRefB:
		return nil
	default:
		return fmt.Errorf("invalid AllOfSiblingValuesViaRef value: %v", a)
	}
}

type AllOfSiblingValues struct {
	Agrees               *AllOfSiblingValuesAgrees                   `json:"agrees,omitempty"`
	AllOfThroughRef      *AllOfSiblingValuesAllOfThroughRef          `json:"allOfThroughRef,omitempty"`
	BranchNarrows        *AllOfSiblingValuesBranchNarrows            `json:"branchNarrows,omitempty"`
	Chain                *AllOfSiblingValuesChain                    `json:"chain,omitempty"`
	ConstInBranch        *AllOfSiblingValuesConstInBranch            `json:"constInBranch,omitempty"`
	ConstOnProperty      *string                                     `json:"constOnProperty,omitempty"`
	LaterBranchNarrows   *AllOfSiblingValuesLaterBranchNarrows       `json:"laterBranchNarrows,omitempty"`
	ListItems            []AllOfSiblingValuesListItemsItem           `json:"listItems,omitzero"`
	MapValues            map[string]AllOfSiblingValuesMapValuesValue `json:"mapValues,omitzero"`
	NestedChain          *AllOfSiblingValuesNestedChain              `json:"nestedChain,omitempty"`
	NumberSpelling       *AllOfSiblingValuesNumberSpelling           `json:"numberSpelling,omitempty"`
	RootNarrows          *AllOfSiblingValuesRootNarrows              `json:"rootNarrows,omitempty"`
	SilentBranch         *AllOfSiblingValuesSilentBranch             `json:"silentBranch,omitempty"`
	ViaRef               *AllOfSiblingValuesViaRef                   `json:"viaRef,omitempty"`
	AdditionalProperties map[string]json.RawMessage                  `json:"-"`
	_jsonKeys            map[string]bool                             // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (a *AllOfSiblingValues) UnmarshalJSON(data []byte) error {
	a.AdditionalProperties = nil
	a._jsonKeys = nil
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type AllOfSiblingValues")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"agrees",
			"allOfThroughRef",
			"branchNarrows",
			"chain",
			"constInBranch",
			"constOnProperty",
			"laterBranchNarrows",
			"listItems",
			"mapValues",
			"nestedChain",
			"numberSpelling",
			"rootNarrows",
			"silentBranch",
			"viaRef",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias AllOfSiblingValues
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(a),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return err
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"agrees",
			"allOfThroughRef",
			"branchNarrows",
			"chain",
			"constInBranch",
			"constOnProperty",
			"laterBranchNarrows",
			"nestedChain",
			"numberSpelling",
			"rootNarrows",
			"silentBranch",
			"viaRef",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return fmt.Errorf("%s: null is not allowed", _nullKey)
			}
		}
		if _v, ok := raw["listItems"]; ok {
			if err := checkJSONNulls(_v, "listItems", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["mapValues"]; ok {
			if err := checkJSONNulls(_v, "mapValues", &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		a._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			a._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"agrees":             true,
			"allOfThroughRef":    true,
			"branchNarrows":      true,
			"chain":              true,
			"constInBranch":      true,
			"constOnProperty":    true,
			"laterBranchNarrows": true,
			"listItems":          true,
			"mapValues":          true,
			"nestedChain":        true,
			"numberSpelling":     true,
			"rootNarrows":        true,
			"silentBranch":       true,
			"viaRef":             true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if a.AdditionalProperties == nil {
				a.AdditionalProperties = make(map[string]json.RawMessage)
			}
			a.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (a AllOfSiblingValues) MarshalJSON() ([]byte, error) {
	type Alias AllOfSiblingValues
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range a.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks AllOfSiblingValues against its JSON Schema constraints.
func (a AllOfSiblingValues) Validate() error {
	if a._jsonKeys["constOnProperty"] {
		{
			_constGot, _constErr := json.Marshal(a.ConstOnProperty)
			if _constErr != nil {
				return fmt.Errorf("constOnProperty: failed to marshal for const check: %w", _constErr)
			}
			if string(_constGot) != "\"q\"" {
				return fmt.Errorf("constOnProperty: value must be %s, got %s", "\"q\"", string(_constGot))
			}
		}
	}
	if a.Agrees != nil {
		if err := a.Agrees.Validate(); err != nil {
			return fmt.Errorf("agrees.%w", err)
		}
	}
	if a.AllOfThroughRef != nil {
		if err := a.AllOfThroughRef.Validate(); err != nil {
			return fmt.Errorf("allOfThroughRef.%w", err)
		}
	}
	if a.BranchNarrows != nil {
		if err := a.BranchNarrows.Validate(); err != nil {
			return fmt.Errorf("branchNarrows.%w", err)
		}
	}
	if a.Chain != nil {
		if err := a.Chain.Validate(); err != nil {
			return fmt.Errorf("chain.%w", err)
		}
	}
	if a.ConstInBranch != nil {
		if err := a.ConstInBranch.Validate(); err != nil {
			return fmt.Errorf("constInBranch.%w", err)
		}
	}
	if a.LaterBranchNarrows != nil {
		if err := a.LaterBranchNarrows.Validate(); err != nil {
			return fmt.Errorf("laterBranchNarrows.%w", err)
		}
	}
	for _i, _item := range a.ListItems {
		if err := _item.Validate(); err != nil {
			return fmt.Errorf("listItems[%d].%w", _i, err)
		}
	}
	for _k, _val := range a.MapValues {
		if err := _val.Validate(); err != nil {
			return fmt.Errorf("mapValues[%q].%w", _k, err)
		}
	}
	if a.NestedChain != nil {
		if err := a.NestedChain.Validate(); err != nil {
			return fmt.Errorf("nestedChain.%w", err)
		}
	}
	if a.NumberSpelling != nil {
		if err := a.NumberSpelling.Validate(); err != nil {
			return fmt.Errorf("numberSpelling.%w", err)
		}
	}
	if a.RootNarrows != nil {
		if err := a.RootNarrows.Validate(); err != nil {
			return fmt.Errorf("rootNarrows.%w", err)
		}
	}
	if a.SilentBranch != nil {
		if err := a.SilentBranch.Validate(); err != nil {
			return fmt.Errorf("silentBranch.%w", err)
		}
	}
	if a.ViaRef != nil {
		if err := a.ViaRef.Validate(); err != nil {
			return fmt.Errorf("viaRef.%w", err)
		}
	}
	return nil
}
