// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
	rt "github.com/mgilbir/schemagen/runtime"
)

// This file needs the runtime module github.com/mgilbir/schemagen/runtime at API
// level 1 or newer. If the compiler reports rt.API1 undefined, the release the
// build resolved is older than the schemagen that generated this file: update it
// with go get github.com/mgilbir/schemagen/runtime@latest.
var _ rt.API1

type Pair json.RawMessage

// The members as the schema wrote them, read at package initialisation: the
// identity every JSON value equal to each shares, and its tree, which is what
// Validate compares the instance with. See rt.MatchesConstRaw.
var pairAllowedJSON = rt.ConstOf(false,
	"{\"k\":1}",
	"{\"k\":2}",
)

// UnmarshalJSON keeps the document's bytes, in a buffer of the value's own.
//
// encoding/json's contract for an Unmarshaler is that it copies what it keeps,
// and this one kept the caller's slice: a caller that reused its read buffer --
// a json.Decoder over a stream does, for every document -- rewrote a value it had
// already decoded, which then validated as whatever the next document held
// there. A value that is not JSON at all is refused in encoding/json's words;
// encoding/json never hands one over, so only a direct caller reaches that.
func (p *Pair) UnmarshalJSON(data []byte) error {
	*p = nil
	if !json.Valid(data) {
		var _v json.RawMessage
		return rt.DecodeRefusal(json.Unmarshal(data, &_v))
	}
	*p = Pair(append([]byte(nil), data...))
	return nil
}

// SchemagenGenerated marks Pair as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (p *Pair) SchemagenGenerated() {}

// MarshalJSON writes the value back as the document wrote it, in a buffer of
// its own: the value's bytes, handed out, are bytes a caller can rewrite it
// through.
func (p Pair) MarshalJSON() ([]byte, error) {
	if len(p) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), p...), nil
}

// Validate checks Pair against its JSON Schema constraints.
func (p Pair) Validate() error {
	// Compared as JSON (see rt.MatchesConstRaw): whitespace, member order and
	// number spelling are not what an enum is decided on. It used to reduce the
	// value to canonical text, re-encoding every string and key in it, to decide.
	_ok, _okErr := rt.MatchesConstRaw(p, pairAllowedJSON)
	if _okErr != nil {
		return rt.ValueErrorf("invalid Pair value: %s", rt.ClipText(string(p)))
	}
	if _ok {
		return nil
	}
	_canon, _ := rt.Canonical([]byte(p))
	return rt.ValueErrorf("invalid Pair value: %s", _canon)
}

type AllOfObjectEnumConstMember struct {
	K                    *int64                     `json:"k,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
	_doc                 *rt.Doc                    // set by UnmarshalJSON: the document the raw members are views of, which Validate reads them through
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnumConstMember) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnumConstMember as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumConstMember) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnumConstMember) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnumConstMember{}
	a._doc = _d
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnumConstMember)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv *rt.Integer
			if _err := func(_p **rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[*rt.Integer](_p, _d, _s, rt.DecodeValue[*rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "k")
			}
			a.K = rt.IntegerPtr(_iv, func(_ix0 rt.Integer) int64 { return int64(_ix0) })
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See rt.Doc.Keep.
	if _d.First(_sp) == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.Keep(_v)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "k":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnumConstMember) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnumConstMember) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnumConstMember) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(a.K)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("k", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnumConstMember) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks AllOfObjectEnumConstMember against its JSON Schema constraints.
func (a AllOfObjectEnumConstMember) Validate() error {
	// enum: the object as a whole must be one of the permitted documents.
	if a._jsonRawProps != nil {
		_enumProps := a._jsonRawProps
		_enumOK, _enumErr := rt.MatchesConstAt(&_enumProps, rt.ConstOf(false,
			"{\"k\":1}",
		))
		if _enumErr != nil {
			return fmt.Errorf("enum: cannot encode value: %w", rt.MarshalError(&_enumProps, _enumErr))
		}
		if !_enumOK {
			_enumCanon, _ := rt.Canonical([]byte(rt.MarshalText(&_enumProps)))
			return fmt.Errorf("enum: value %s is not one of the permitted values", rt.ClipText(_enumCanon))
		}
	}
	return nil
}

type AllOfObjectEnumInline struct {
	K                    *int64                     `json:"k,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
	_doc                 *rt.Doc                    // set by UnmarshalJSON: the document the raw members are views of, which Validate reads them through
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnumInline) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnumInline as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumInline) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnumInline) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnumInline{}
	a._doc = _d
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnumInline)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv *rt.Integer
			if _err := func(_p **rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[*rt.Integer](_p, _d, _s, rt.DecodeValue[*rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "k")
			}
			a.K = rt.IntegerPtr(_iv, func(_ix0 rt.Integer) int64 { return int64(_ix0) })
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See rt.Doc.Keep.
	if _d.First(_sp) == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.Keep(_v)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "k":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnumInline) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnumInline) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnumInline) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(a.K)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("k", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnumInline) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks AllOfObjectEnumInline against its JSON Schema constraints.
func (a AllOfObjectEnumInline) Validate() error {
	// enum: the object as a whole must be one of the permitted documents.
	if a._jsonRawProps != nil {
		_enumProps := a._jsonRawProps
		_enumOK, _enumErr := rt.MatchesConstAt(&_enumProps, rt.ConstOf(false,
			"{\"k\":1}",
			"{\"k\":2}",
		))
		if _enumErr != nil {
			return fmt.Errorf("enum: cannot encode value: %w", rt.MarshalError(&_enumProps, _enumErr))
		}
		if !_enumOK {
			_enumCanon, _ := rt.Canonical([]byte(rt.MarshalText(&_enumProps)))
			return fmt.Errorf("enum: value %s is not one of the permitted values", rt.ClipText(_enumCanon))
		}
	}
	return nil
}

type AllOfObjectEnumNested struct {
	K                    map[string]any             `json:"k,omitzero"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
	_doc                 *rt.Doc                    // set by UnmarshalJSON: the document the raw members are views of, which Validate reads them through
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnumNested) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnumNested as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumNested) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnumNested) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnumNested{}
	a._doc = _d
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnumNested)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		if _err := func(_p *map[string]any, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[map[string]any](_p, _d, _s, rt.DecodeValues(rt.DecodeValue[any]))
		}(&a.K, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "k")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See rt.Doc.Keep.
	if _d.First(_sp) == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.Keep(_v)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "k":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnumNested) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnumNested) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnumNested) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitZero(a.K)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("k", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnumNested) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks AllOfObjectEnumNested against its JSON Schema constraints.
func (a AllOfObjectEnumNested) Validate() error {
	// enum: the object as a whole must be one of the permitted documents.
	if a._jsonRawProps != nil {
		_enumProps := a._jsonRawProps
		_enumOK, _enumErr := rt.MatchesConstAt(&_enumProps, rt.ConstOf(false,
			"{\"k\":{\"n\":[1,2]}}",
		))
		if _enumErr != nil {
			return fmt.Errorf("enum: cannot encode value: %w", rt.MarshalError(&_enumProps, _enumErr))
		}
		if !_enumOK {
			_enumCanon, _ := rt.Canonical([]byte(rt.MarshalText(&_enumProps)))
			return fmt.Errorf("enum: value %s is not one of the permitted values", rt.ClipText(_enumCanon))
		}
	}
	return nil
}

type AllOfObjectEnumPlain struct {
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	K                    int64                      `json:"k"`
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnumPlain) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnumPlain as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumPlain) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnumPlain) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnumPlain{}
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnumPlain)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv rt.Integer
			if _err := func(_p *rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[rt.Integer](_p, _d, _s, rt.DecodeValue[rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "k")
			}
			a.K = int64(_iv)
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	a._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		a._jsonKeys[_k] = true
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "k":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnumPlain) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnumPlain) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnumPlain) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _err := rt.AppendLeaf(a.K, nil)
		if _err != nil {
			return _err
		}
		_o.Encoded("k", _v)
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnumPlain) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks AllOfObjectEnumPlain against its JSON Schema constraints.
func (a AllOfObjectEnumPlain) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if a._jsonKeys != nil {
		for _, _req := range []string{"k"} {
			if !a._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

type AllOfObjectEnumReordered struct {
	A                    *int64                     `json:"a,omitempty"`
	B                    *int64                     `json:"b,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
	_doc                 *rt.Doc                    // set by UnmarshalJSON: the document the raw members are views of, which Validate reads them through
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnumReordered) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnumReordered as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumReordered) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnumReordered) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnumReordered{}
	a._doc = _d
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnumReordered)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["a"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv *rt.Integer
			if _err := func(_p **rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[*rt.Integer](_p, _d, _s, rt.DecodeValue[*rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "a")
			}
			a.A = rt.IntegerPtr(_iv, func(_ix0 rt.Integer) int64 { return int64(_ix0) })
		}
	}
	if _v, _ok := _raw["b"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv *rt.Integer
			if _err := func(_p **rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[*rt.Integer](_p, _d, _s, rt.DecodeValue[*rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "b")
			}
			a.B = rt.IntegerPtr(_iv, func(_ix0 rt.Integer) int64 { return int64(_ix0) })
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"a",
		"b",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See rt.Doc.Keep.
	if _d.First(_sp) == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.Keep(_v)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "a", "b":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnumReordered) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnumReordered) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnumReordered) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(a.A)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("a", _v)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitEmpty(a.B)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("b", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnumReordered) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks AllOfObjectEnumReordered against its JSON Schema constraints.
func (a AllOfObjectEnumReordered) Validate() error {
	// enum: the object as a whole must be one of the permitted documents.
	if a._jsonRawProps != nil {
		_enumProps := a._jsonRawProps
		_enumOK, _enumErr := rt.MatchesConstAt(&_enumProps, rt.ConstOf(false,
			"{\"a\":1,\"b\":2}",
		))
		if _enumErr != nil {
			return fmt.Errorf("enum: cannot encode value: %w", rt.MarshalError(&_enumProps, _enumErr))
		}
		if !_enumOK {
			_enumCanon, _ := rt.Canonical([]byte(rt.MarshalText(&_enumProps)))
			return fmt.Errorf("enum: value %s is not one of the permitted values", rt.ClipText(_enumCanon))
		}
	}
	return nil
}

type AllOfObjectEnumStandalone json.RawMessage

// The members as the schema wrote them, read at package initialisation: the
// identity every JSON value equal to each shares, and its tree, which is what
// Validate compares the instance with. See rt.MatchesConstRaw.
var allOfObjectEnumStandaloneAllowedJSON = rt.ConstOf(false,
	"{\"k\":1}",
	"{\"k\":2}",
)

// UnmarshalJSON keeps the document's bytes, in a buffer of the value's own.
//
// encoding/json's contract for an Unmarshaler is that it copies what it keeps,
// and this one kept the caller's slice: a caller that reused its read buffer --
// a json.Decoder over a stream does, for every document -- rewrote a value it had
// already decoded, which then validated as whatever the next document held
// there. A value that is not JSON at all is refused in encoding/json's words;
// encoding/json never hands one over, so only a direct caller reaches that.
func (a *AllOfObjectEnumStandalone) UnmarshalJSON(data []byte) error {
	*a = nil
	if !json.Valid(data) {
		var _v json.RawMessage
		return rt.DecodeRefusal(json.Unmarshal(data, &_v))
	}
	*a = AllOfObjectEnumStandalone(append([]byte(nil), data...))
	return nil
}

// SchemagenGenerated marks AllOfObjectEnumStandalone as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumStandalone) SchemagenGenerated() {}

// MarshalJSON writes the value back as the document wrote it, in a buffer of
// its own: the value's bytes, handed out, are bytes a caller can rewrite it
// through.
func (a AllOfObjectEnumStandalone) MarshalJSON() ([]byte, error) {
	if len(a) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), a...), nil
}

// Validate checks AllOfObjectEnumStandalone against its JSON Schema constraints.
func (a AllOfObjectEnumStandalone) Validate() error {
	// Compared as JSON (see rt.MatchesConstRaw): whitespace, member order and
	// number spelling are not what an enum is decided on. It used to reduce the
	// value to canonical text, re-encoding every string and key in it, to decide.
	_ok, _okErr := rt.MatchesConstRaw(a, allOfObjectEnumStandaloneAllowedJSON)
	if _okErr != nil {
		return rt.ValueErrorf("invalid AllOfObjectEnumStandalone value: %s", rt.ClipText(string(a)))
	}
	if _ok {
		return nil
	}
	_canon, _ := rt.Canonical([]byte(a))
	return rt.ValueErrorf("invalid AllOfObjectEnumStandalone value: %s", _canon)
}

type AllOfObjectEnumViaRef struct {
	K                    *int64                     `json:"k,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
	_doc                 *rt.Doc                    // set by UnmarshalJSON: the document the raw members are views of, which Validate reads them through
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnumViaRef) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnumViaRef as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnumViaRef) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnumViaRef) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnumViaRef{}
	a._doc = _d
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnumViaRef)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv *rt.Integer
			if _err := func(_p **rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[*rt.Integer](_p, _d, _s, rt.DecodeValue[*rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "k")
			}
			a.K = rt.IntegerPtr(_iv, func(_ix0 rt.Integer) int64 { return int64(_ix0) })
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See rt.Doc.Keep.
	if _d.First(_sp) == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.Keep(_v)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "k":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnumViaRef) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnumViaRef) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnumViaRef) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(a.K)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("k", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnumViaRef) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks AllOfObjectEnumViaRef against its JSON Schema constraints.
func (a AllOfObjectEnumViaRef) Validate() error {
	// enum: the object as a whole must be one of the permitted documents.
	if a._jsonRawProps != nil {
		_enumProps := a._jsonRawProps
		_enumOK, _enumErr := rt.MatchesConstAt(&_enumProps, rt.ConstOf(false,
			"{\"k\":1}",
			"{\"k\":2}",
		))
		if _enumErr != nil {
			return fmt.Errorf("enum: cannot encode value: %w", rt.MarshalError(&_enumProps, _enumErr))
		}
		if !_enumOK {
			_enumCanon, _ := rt.Canonical([]byte(rt.MarshalText(&_enumProps)))
			return fmt.Errorf("enum: value %s is not one of the permitted values", rt.ClipText(_enumCanon))
		}
	}
	return nil
}

type AllOfObjectEnum struct {
	ConstMember          *AllOfObjectEnumConstMember `json:"constMember,omitempty"`
	Inline               *AllOfObjectEnumInline      `json:"inline,omitempty"`
	Nested               *AllOfObjectEnumNested      `json:"nested,omitempty"`
	Plain                *AllOfObjectEnumPlain       `json:"plain,omitempty"`
	Reordered            *AllOfObjectEnumReordered   `json:"reordered,omitempty"`
	ViaRef               *AllOfObjectEnumViaRef      `json:"viaRef,omitempty"`
	AdditionalProperties map[string]json.RawMessage  `json:"-"`
	_jsonKeys            map[string]bool             // set by UnmarshalJSON for optional field / dependentSchemas validation
	Standalone           AllOfObjectEnumStandalone   `json:"standalone,omitempty"`
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AllOfObjectEnum) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(a.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks AllOfObjectEnum as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (a *AllOfObjectEnum) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AllOfObjectEnum) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*a = AllOfObjectEnum{}
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*AllOfObjectEnum)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["constMember"]; _ok {
		if _err := func(_p **AllOfObjectEnumConstMember, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **AllOfObjectEnumConstMember, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(AllOfObjectEnumConstMember)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&a.ConstMember, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "constMember")
		}
	}
	if _v, _ok := _raw["inline"]; _ok {
		if _err := func(_p **AllOfObjectEnumInline, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **AllOfObjectEnumInline, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(AllOfObjectEnumInline)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&a.Inline, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "inline")
		}
	}
	if _v, _ok := _raw["nested"]; _ok {
		if _err := func(_p **AllOfObjectEnumNested, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **AllOfObjectEnumNested, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(AllOfObjectEnumNested)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&a.Nested, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "nested")
		}
	}
	if _v, _ok := _raw["plain"]; _ok {
		if _err := func(_p **AllOfObjectEnumPlain, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **AllOfObjectEnumPlain, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(AllOfObjectEnumPlain)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&a.Plain, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "plain")
		}
	}
	if _v, _ok := _raw["reordered"]; _ok {
		if _err := func(_p **AllOfObjectEnumReordered, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **AllOfObjectEnumReordered, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(AllOfObjectEnumReordered)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&a.Reordered, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "reordered")
		}
	}
	if _v, _ok := _raw["standalone"]; _ok {
		if _err := func(_p *AllOfObjectEnumStandalone, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[AllOfObjectEnumStandalone](_p, _d, _s, rt.DecodeValue[AllOfObjectEnumStandalone])
		}(&a.Standalone, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "standalone")
		}
	}
	if _v, _ok := _raw["viaRef"]; _ok {
		if _err := func(_p **AllOfObjectEnumViaRef, _d *rt.Doc, _s rt.Span) error {
			return rt.DecodeRefusal(func(_p **AllOfObjectEnumViaRef, _d *rt.Doc, _s rt.Span) error {
				if _d.IsNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(AllOfObjectEnumViaRef)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&a.ViaRef, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "viaRef")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"constMember",
		"inline",
		"nested",
		"plain",
		"reordered",
		"standalone",
		"viaRef",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	a._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		a._jsonKeys[_k] = true
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "constMember", "inline", "nested", "plain", "reordered", "standalone", "viaRef":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	a.AdditionalProperties = _apFiled

	return nil
}
func (a AllOfObjectEnum) MarshalJSON() ([]byte, error) {
	_b, _err := a.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends a to _b as JSON. See rt.Enc.
func (a AllOfObjectEnum) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := a.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range a.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, a.appendMemberJSON)
}

// encodeFieldsJSON gathers the members a's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (a AllOfObjectEnum) encodeFieldsJSON(_o *rt.Obj) error {
	{
		if !rt.IsEmpty(a.ConstMember) {
			_o.Deferred("constMember", 0)
		}
	}
	{
		if !rt.IsEmpty(a.Inline) {
			_o.Deferred("inline", 1)
		}
	}
	{
		if !rt.IsEmpty(a.Nested) {
			_o.Deferred("nested", 2)
		}
	}
	{
		if !rt.IsEmpty(a.Plain) {
			_o.Deferred("plain", 3)
		}
	}
	{
		if !rt.IsEmpty(a.Reordered) {
			_o.Deferred("reordered", 4)
		}
	}
	{
		if !rt.IsEmpty(a.ViaRef) {
			_o.Deferred("viaRef", 5)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitEmpty(a.Standalone)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("standalone", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of a numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (a AllOfObjectEnum) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	case 0:
		return (func(_v *AllOfObjectEnumConstMember, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*AllOfObjectEnumConstMember)(nil), true)
			}
			return _out, nil
		})(a.ConstMember, _b)
	case 1:
		return (func(_v *AllOfObjectEnumInline, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*AllOfObjectEnumInline)(nil), true)
			}
			return _out, nil
		})(a.Inline, _b)
	case 2:
		return (func(_v *AllOfObjectEnumNested, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*AllOfObjectEnumNested)(nil), true)
			}
			return _out, nil
		})(a.Nested, _b)
	case 3:
		return (func(_v *AllOfObjectEnumPlain, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*AllOfObjectEnumPlain)(nil), true)
			}
			return _out, nil
		})(a.Plain, _b)
	case 4:
		return (func(_v *AllOfObjectEnumReordered, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*AllOfObjectEnumReordered)(nil), true)
			}
			return _out, nil
		})(a.Reordered, _b)
	case 5:
		return (func(_v *AllOfObjectEnumViaRef, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, rt.MarshalerErrFor(_err, (*AllOfObjectEnumViaRef)(nil), true)
			}
			return _out, nil
		})(a.ViaRef, _b)
	}
	return _b, nil
}

// Validate checks AllOfObjectEnum against its JSON Schema constraints.
func (a AllOfObjectEnum) Validate() error {
	if a.ConstMember != nil {
		if err := a.ConstMember.Validate(); err != nil {
			return rt.Pathf(err, "constMember")
		}
	}
	if a.Inline != nil {
		if err := a.Inline.Validate(); err != nil {
			return rt.Pathf(err, "inline")
		}
	}
	if a.Nested != nil {
		if err := a.Nested.Validate(); err != nil {
			return rt.Pathf(err, "nested")
		}
	}
	if a.Plain != nil {
		if err := a.Plain.Validate(); err != nil {
			return rt.Pathf(err, "plain")
		}
	}
	if a.Reordered != nil {
		if err := a.Reordered.Validate(); err != nil {
			return rt.Pathf(err, "reordered")
		}
	}
	if a.Standalone != nil {
		if err := a.Standalone.Validate(); err != nil {
			return rt.Pathf(err, "standalone")
		}
	}
	if a.ViaRef != nil {
		if err := a.ViaRef.Validate(); err != nil {
			return rt.Pathf(err, "viaRef")
		}
	}
	return nil
}
