// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type AnyOfRequiredOnly struct {
	A                    any                        `json:"a,omitempty"`
	B                    any                        `json:"b,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
}

func (a *AnyOfRequiredOnly) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type AnyOfRequiredOnly")
	}
	type Alias AnyOfRequiredOnly
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(a),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		a._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			a._jsonKeys[_k] = true
		}
		a._jsonRawProps = raw
		knownFields := map[string]bool{
			"a": true,
			"b": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if a.AdditionalProperties == nil {
				a.AdditionalProperties = make(map[string]json.RawMessage)
			}
			a.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (a AnyOfRequiredOnly) MarshalJSON() ([]byte, error) {
	type Alias AnyOfRequiredOnly
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range a.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks AnyOfRequiredOnly against its JSON Schema constraints.
func (a AnyOfRequiredOnly) Validate() error {
	// object-level anyOf: at least one flattened variant must match.
	{
		_anyOfMatches := 0
		{
			_branchMatches := true
			if !a._jsonKeys["a"] {
				_branchMatches = false
			}
			if _branchMatches {
				_anyOfMatches++
			}
		}
		{
			_branchMatches := true
			if !a._jsonKeys["b"] {
				_branchMatches = false
			}
			if _branchMatches {
				_anyOfMatches++
			}
		}
		if _anyOfMatches < 1 {
			return fmt.Errorf("anyOf: no variant matched")
		}
	}
	return nil
}
