// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// AnyOfBooleanAndScalarBranchesBareObjectBranch accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type AnyOfBooleanAndScalarBranchesBareObjectBranch struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesBareObjectBranch) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever a held.
func (a *AnyOfBooleanAndScalarBranchesBareObjectBranch) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesBareObjectBranch{}
	a._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (a AnyOfBooleanAndScalarBranchesBareObjectBranch) MarshalJSON() ([]byte, error) {
	if len(a._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), a._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (a AnyOfBooleanAndScalarBranchesBareObjectBranch) Raw() json.RawMessage {
	return append(json.RawMessage(nil), a._raw...)
}

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (a AnyOfBooleanAndScalarBranchesBareObjectBranch) IsZero() bool { return len(a._raw) == 0 }

func (a AnyOfBooleanAndScalarBranchesBareObjectBranch) String() string { return string(a._raw) }

// AnyOfBooleanAndScalarBranchesBareObjectBranchSchema is the schema AnyOfBooleanAndScalarBranchesBareObjectBranch validates against.
var AnyOfBooleanAndScalarBranchesBareObjectBranchSchema = _schemaNode{
	AnyOf: []_schemaNode{
		_schemaNode{
			Properties: []_schemaMember{
				{Key: "k", Node: _schemaNode{
					Type: []string{"string"},
				}},
			},
			Required: []string{"k"},
			Type:     []string{"object"},
		},
		_schemaNode{
			Type: []string{"object"},
		},
	},
}

// Validate checks AnyOfBooleanAndScalarBranchesBareObjectBranch against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesBareObjectBranch) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(a._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(a._raw, &_v); _err != nil {
		// A sentence about the value, joined by the same rule as the verdict
		// below. Structural: the raw bytes came from a decoder that had already
		// accepted them as JSON, so nothing has been seen to reach this.
		return jsonValueErrorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&AnyOfBooleanAndScalarBranchesBareObjectBranchSchema, _v); !_res.ok {
		return _evalError(_res)
	}
	return nil
}

// AnyOfBooleanAndScalarBranchesConstBranch accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type AnyOfBooleanAndScalarBranchesConstBranch struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesConstBranch) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever a held.
func (a *AnyOfBooleanAndScalarBranchesConstBranch) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesConstBranch{}
	a._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (a AnyOfBooleanAndScalarBranchesConstBranch) MarshalJSON() ([]byte, error) {
	if len(a._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), a._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (a AnyOfBooleanAndScalarBranchesConstBranch) Raw() json.RawMessage {
	return append(json.RawMessage(nil), a._raw...)
}

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (a AnyOfBooleanAndScalarBranchesConstBranch) IsZero() bool { return len(a._raw) == 0 }

func (a AnyOfBooleanAndScalarBranchesConstBranch) String() string { return string(a._raw) }

// AnyOfBooleanAndScalarBranchesConstBranchSchema is the schema AnyOfBooleanAndScalarBranchesConstBranch validates against.
var AnyOfBooleanAndScalarBranchesConstBranchSchema = _schemaNode{
	AnyOf: []_schemaNode{
		_schemaNode{
			Properties: []_schemaMember{
				{Key: "k", Node: _schemaNode{
					Type: []string{"string"},
				}},
			},
			Required: []string{"k"},
			Type:     []string{"object"},
		},
		_schemaNode{
			Const: _strPtr("\"x\""),
		},
	},
}

// Validate checks AnyOfBooleanAndScalarBranchesConstBranch against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesConstBranch) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(a._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(a._raw, &_v); _err != nil {
		// A sentence about the value, joined by the same rule as the verdict
		// below. Structural: the raw bytes came from a decoder that had already
		// accepted them as JSON, so nothing has been seen to reach this.
		return jsonValueErrorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&AnyOfBooleanAndScalarBranchesConstBranchSchema, _v); !_res.ok {
		return _evalError(_res)
	}
	return nil
}

type AnyOfBooleanAndScalarBranchesFalseBranch struct {
	K                    *string                    `json:"k,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesFalseBranch) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AnyOfBooleanAndScalarBranchesFalseBranch) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesFalseBranch{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[AnyOfBooleanAndScalarBranchesFalseBranch](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&a.K, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "k")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See jsonDoc.keep.
	if _d.data[_sp.start] == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.keep(_v)
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "k":
			continue
		}
		if a.AdditionalProperties == nil {
			a.AdditionalProperties = make(map[string]json.RawMessage)
		}
		a.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (a AnyOfBooleanAndScalarBranchesFalseBranch) MarshalJSON() ([]byte, error) {
	type Alias AnyOfBooleanAndScalarBranchesFalseBranch
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range a.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks AnyOfBooleanAndScalarBranchesFalseBranch against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesFalseBranch) Validate() error {
	// Keywords the generated checks cannot state in full, held as schema data and
	// evaluated against the document.
	if a._jsonRawProps != nil {
		_rbInstance := make(map[string]any, len(a._jsonRawProps))
		{
			var _least string
			var _failed error
			for _rbKey, _rbRaw := range a._jsonRawProps { // refused for the least failing key
				if _failed != nil && _rbKey >= _least {
					continue
				}
				if _err := func() error {
					var _rbVal any
					if _rbErr := json.Unmarshal(_rbRaw, &_rbVal); _rbErr != nil {
						return jsonValueErrorf("cannot decode property %s: %w", _schemagenQuote(_rbKey), _rbErr)
					}
					_rbInstance[_rbKey] = _rbVal
					return nil
				}(); _err != nil {
					_least, _failed = _rbKey, _err
				}
			}
			if _failed != nil {
				return _failed
			}
		}
		{
			_rbNode0 := _schemaNode{
				AnyOf: []_schemaNode{
					_schemaNode{
						Properties: []_schemaMember{
							{Key: "k", Node: _schemaNode{
								Type: []string{"string"},
							}},
						},
						Required: []string{"k"},
						Type:     []string{"object"},
					},
					_schemaNode{Boolean: _boolPtr(false)},
				},
			}
			if _rbRes := _evalNode(&_rbNode0, _rbInstance); !_rbRes.ok {
				if _rbRes.reason == "" {
					return fmt.Errorf("anyOf: value does not satisfy the schema")
				}
				return fmt.Errorf("anyOf: %s", _rbRes.reason)
			}
		}
	}
	return nil
}

// AnyOfBooleanAndScalarBranchesMixed accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type AnyOfBooleanAndScalarBranchesMixed struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesMixed) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever a held.
func (a *AnyOfBooleanAndScalarBranchesMixed) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesMixed{}
	a._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (a AnyOfBooleanAndScalarBranchesMixed) MarshalJSON() ([]byte, error) {
	if len(a._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), a._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (a AnyOfBooleanAndScalarBranchesMixed) Raw() json.RawMessage {
	return append(json.RawMessage(nil), a._raw...)
}

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (a AnyOfBooleanAndScalarBranchesMixed) IsZero() bool { return len(a._raw) == 0 }

func (a AnyOfBooleanAndScalarBranchesMixed) String() string { return string(a._raw) }

// AnyOfBooleanAndScalarBranchesMixedSchema is the schema AnyOfBooleanAndScalarBranchesMixed validates against.
var AnyOfBooleanAndScalarBranchesMixedSchema = _schemaNode{
	AnyOf: []_schemaNode{
		_schemaNode{
			Properties: []_schemaMember{
				{Key: "k", Node: _schemaNode{
					Type: []string{"string"},
				}},
			},
			Required: []string{"k"},
			Type:     []string{"object"},
		},
		_schemaNode{
			Type: []string{"string"},
		},
	},
}

// Validate checks AnyOfBooleanAndScalarBranchesMixed against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesMixed) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(a._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(a._raw, &_v); _err != nil {
		// A sentence about the value, joined by the same rule as the verdict
		// below. Structural: the raw bytes came from a decoder that had already
		// accepted them as JSON, so nothing has been seen to reach this.
		return jsonValueErrorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&AnyOfBooleanAndScalarBranchesMixedSchema, _v); !_res.ok {
		return _evalError(_res)
	}
	return nil
}

// AnyOfBooleanAndScalarBranchesNotBranch accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type AnyOfBooleanAndScalarBranchesNotBranch struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesNotBranch) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever a held.
func (a *AnyOfBooleanAndScalarBranchesNotBranch) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesNotBranch{}
	a._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (a AnyOfBooleanAndScalarBranchesNotBranch) MarshalJSON() ([]byte, error) {
	if len(a._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), a._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (a AnyOfBooleanAndScalarBranchesNotBranch) Raw() json.RawMessage {
	return append(json.RawMessage(nil), a._raw...)
}

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (a AnyOfBooleanAndScalarBranchesNotBranch) IsZero() bool { return len(a._raw) == 0 }

func (a AnyOfBooleanAndScalarBranchesNotBranch) String() string { return string(a._raw) }

// AnyOfBooleanAndScalarBranchesNotBranchSchema is the schema AnyOfBooleanAndScalarBranchesNotBranch validates against.
var AnyOfBooleanAndScalarBranchesNotBranchSchema = _schemaNode{
	AnyOf: []_schemaNode{
		_schemaNode{
			Properties: []_schemaMember{
				{Key: "k", Node: _schemaNode{
					Type: []string{"string"},
				}},
			},
			Required: []string{"k"},
			Type:     []string{"object"},
		},
		_schemaNode{
			Not: _node(_schemaNode{
				Type: []string{"object"},
			}),
		},
	},
}

// Validate checks AnyOfBooleanAndScalarBranchesNotBranch against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesNotBranch) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(a._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(a._raw, &_v); _err != nil {
		// A sentence about the value, joined by the same rule as the verdict
		// below. Structural: the raw bytes came from a decoder that had already
		// accepted them as JSON, so nothing has been seen to reach this.
		return jsonValueErrorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&AnyOfBooleanAndScalarBranchesNotBranchSchema, _v); !_res.ok {
		return _evalError(_res)
	}
	return nil
}

type AnyOfBooleanAndScalarBranchesObjectsOnly struct {
	J                    *string                    `json:"j,omitempty"`
	K                    *string                    `json:"k,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	_jsonRawProps        map[string]json.RawMessage // set by UnmarshalJSON for runtime conditional evaluation (if/then/else, anyOf const checks)
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesObjectsOnly) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AnyOfBooleanAndScalarBranchesObjectsOnly) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesObjectsOnly{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[AnyOfBooleanAndScalarBranchesObjectsOnly](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["j"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&a.J, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "j")
		}
	}
	if _v, _ok := _raw["k"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&a.K, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "k")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"j",
		"k",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	a._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		a._jsonKeys[_k] = true
	}
	// The members a Validate check reads back as JSON. Each is a view of the
	// document's own copy rather than a copy of its own: at every depth of a
	// recursive document these hold the member below, and a copy each was the
	// whole subtree held once per level. See jsonDoc.keep.
	if _d.data[_sp.start] == '{' {
		a._jsonRawProps = make(map[string]json.RawMessage, len(_raw))
		for _k, _v := range _raw {
			a._jsonRawProps[_k] = _d.keep(_v)
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "j", "k":
			continue
		}
		if a.AdditionalProperties == nil {
			a.AdditionalProperties = make(map[string]json.RawMessage)
		}
		a.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (a AnyOfBooleanAndScalarBranchesObjectsOnly) MarshalJSON() ([]byte, error) {
	type Alias AnyOfBooleanAndScalarBranchesObjectsOnly
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range a.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks AnyOfBooleanAndScalarBranchesObjectsOnly against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesObjectsOnly) Validate() error {
	// object-level anyOf: at least one flattened variant must match.
	// This check depends on JSON key presence (_jsonKeys), so it is skipped
	// for hand-constructed values (nil _jsonKeys), consistent with how the
	// required-property check above treats untracked presence.
	if a._jsonKeys != nil {
		_anyOfMatches := 0
		{
			_branchMatches := true
			if !a._jsonKeys["k"] {
				_branchMatches = false
			}
			if _branchMatches {
				if _raw, _ok := a._jsonRawProps["k"]; _ok {
					_jt := "unknown"
					_b := bytes.TrimSpace(_raw)
					if len(_b) > 0 {
						switch _b[0] {
						case '"':
							_jt = "string"
						case '{':
							_jt = "object"
						case '[':
							_jt = "array"
						case 't', 'f':
							_jt = "boolean"
						case 'n':
							_jt = "null"
						default:
							_jt = "number"
							_isInt := true
							for _, _c := range _b {
								if _c == '.' || _c == 'e' || _c == 'E' {
									_isInt = false
									break
								}
							}
							if _isInt {
								_jt = "integer"
							}
						}
					}
					if _jt != "string" {
						_branchMatches = false
					}
				}
			}
			if _branchMatches {
				_anyOfMatches++
			}
		}
		{
			_branchMatches := true
			if !a._jsonKeys["j"] {
				_branchMatches = false
			}
			if _branchMatches {
				if _raw, _ok := a._jsonRawProps["j"]; _ok {
					_jt := "unknown"
					_b := bytes.TrimSpace(_raw)
					if len(_b) > 0 {
						switch _b[0] {
						case '"':
							_jt = "string"
						case '{':
							_jt = "object"
						case '[':
							_jt = "array"
						case 't', 'f':
							_jt = "boolean"
						case 'n':
							_jt = "null"
						default:
							_jt = "number"
							_isInt := true
							for _, _c := range _b {
								if _c == '.' || _c == 'e' || _c == 'E' {
									_isInt = false
									break
								}
							}
							if _isInt {
								_jt = "integer"
							}
						}
					}
					if _jt != "string" {
						_branchMatches = false
					}
				}
			}
			if _branchMatches {
				_anyOfMatches++
			}
		}
		if _anyOfMatches < 1 {
			return fmt.Errorf("anyOf: no variant matched")
		}
	}
	return nil
}

// AnyOfBooleanAndScalarBranchesTrueBranch accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type AnyOfBooleanAndScalarBranchesTrueBranch struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranchesTrueBranch) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever a held.
func (a *AnyOfBooleanAndScalarBranchesTrueBranch) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranchesTrueBranch{}
	a._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (a AnyOfBooleanAndScalarBranchesTrueBranch) MarshalJSON() ([]byte, error) {
	if len(a._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), a._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (a AnyOfBooleanAndScalarBranchesTrueBranch) Raw() json.RawMessage {
	return append(json.RawMessage(nil), a._raw...)
}

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (a AnyOfBooleanAndScalarBranchesTrueBranch) IsZero() bool { return len(a._raw) == 0 }

func (a AnyOfBooleanAndScalarBranchesTrueBranch) String() string { return string(a._raw) }

// AnyOfBooleanAndScalarBranchesTrueBranchSchema is the schema AnyOfBooleanAndScalarBranchesTrueBranch validates against.
var AnyOfBooleanAndScalarBranchesTrueBranchSchema = _schemaNode{
	AnyOf: []_schemaNode{
		_schemaNode{
			Properties: []_schemaMember{
				{Key: "k", Node: _schemaNode{
					Type: []string{"string"},
				}},
			},
			Required: []string{"k"},
			Type:     []string{"object"},
		},
		_schemaNode{Boolean: _boolPtr(true)},
	},
}

// Validate checks AnyOfBooleanAndScalarBranchesTrueBranch against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranchesTrueBranch) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(a._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(a._raw, &_v); _err != nil {
		// A sentence about the value, joined by the same rule as the verdict
		// below. Structural: the raw bytes came from a decoder that had already
		// accepted them as JSON, so nothing has been seen to reach this.
		return jsonValueErrorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&AnyOfBooleanAndScalarBranchesTrueBranchSchema, _v); !_res.ok {
		return _evalError(_res)
	}
	return nil
}

// AnyOfBooleanAndScalarBranches - An anyOf mixing an object branch with branches the merged struct cannot place, or that the object-shape summary cannot judge. The merge is a Go struct, so a branch admitting a scalar had nowhere to decode into and the document was refused before a branch was tried; a bare "type":"object" branch admits every object, including the ones the merged field types refuse; and the summary drops the whole "at least one branch matches" assertion as soon as one branch states neither a required key nor a property check, so a `false` branch -- which matches nothing -- was read as one matching everything. The all-object group is the control: it selects on required keys and must keep the merge it already judges correctly.
type AnyOfBooleanAndScalarBranches struct {
	FalseBranch          *AnyOfBooleanAndScalarBranchesFalseBranch     `json:"falseBranch,omitempty"`
	ObjectsOnly          *AnyOfBooleanAndScalarBranchesObjectsOnly     `json:"objectsOnly,omitempty"`
	AdditionalProperties map[string]json.RawMessage                    `json:"-"`
	_jsonKeys            map[string]bool                               // set by UnmarshalJSON for optional field / dependentSchemas validation
	BareObjectBranch     AnyOfBooleanAndScalarBranchesBareObjectBranch `json:"bareObjectBranch,omitzero"`
	ConstBranch          AnyOfBooleanAndScalarBranchesConstBranch      `json:"constBranch,omitzero"`
	Mixed                AnyOfBooleanAndScalarBranchesMixed            `json:"mixed,omitzero"`
	NotBranch            AnyOfBooleanAndScalarBranchesNotBranch        `json:"notBranch,omitzero"`
	TrueBranch           AnyOfBooleanAndScalarBranchesTrueBranch       `json:"trueBranch,omitzero"`
}

// UnmarshalJSON replaces a with the value the document holds. See
// decodeJSONAt.
func (a *AnyOfBooleanAndScalarBranches) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(a.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into a, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever a held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (a *AnyOfBooleanAndScalarBranches) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*a = AnyOfBooleanAndScalarBranches{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[AnyOfBooleanAndScalarBranches](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["bareObjectBranch"]; _ok {
		if _err := func(_p *AnyOfBooleanAndScalarBranchesBareObjectBranch, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal((*AnyOfBooleanAndScalarBranchesBareObjectBranch).decodeJSONAt(_p, _d, _s))
		}(&a.BareObjectBranch, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "bareObjectBranch")
		}
	}
	if _v, _ok := _raw["constBranch"]; _ok {
		if _err := func(_p *AnyOfBooleanAndScalarBranchesConstBranch, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal((*AnyOfBooleanAndScalarBranchesConstBranch).decodeJSONAt(_p, _d, _s))
		}(&a.ConstBranch, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "constBranch")
		}
	}
	if _v, _ok := _raw["falseBranch"]; _ok {
		if _err := func(_p **AnyOfBooleanAndScalarBranchesFalseBranch, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal(func(_p **AnyOfBooleanAndScalarBranchesFalseBranch, _d *jsonDoc, _s jsonSpan) error {
				return jsonDecodePtr[*AnyOfBooleanAndScalarBranchesFalseBranch, AnyOfBooleanAndScalarBranchesFalseBranch](_p, _d, _s, (*AnyOfBooleanAndScalarBranchesFalseBranch).decodeJSONAt)
			}(_p, _d, _s))
		}(&a.FalseBranch, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "falseBranch")
		}
	}
	if _v, _ok := _raw["mixed"]; _ok {
		if _err := func(_p *AnyOfBooleanAndScalarBranchesMixed, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal((*AnyOfBooleanAndScalarBranchesMixed).decodeJSONAt(_p, _d, _s))
		}(&a.Mixed, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "mixed")
		}
	}
	if _v, _ok := _raw["notBranch"]; _ok {
		if _err := func(_p *AnyOfBooleanAndScalarBranchesNotBranch, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal((*AnyOfBooleanAndScalarBranchesNotBranch).decodeJSONAt(_p, _d, _s))
		}(&a.NotBranch, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "notBranch")
		}
	}
	if _v, _ok := _raw["objectsOnly"]; _ok {
		if _err := func(_p **AnyOfBooleanAndScalarBranchesObjectsOnly, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal(func(_p **AnyOfBooleanAndScalarBranchesObjectsOnly, _d *jsonDoc, _s jsonSpan) error {
				return jsonDecodePtr[*AnyOfBooleanAndScalarBranchesObjectsOnly, AnyOfBooleanAndScalarBranchesObjectsOnly](_p, _d, _s, (*AnyOfBooleanAndScalarBranchesObjectsOnly).decodeJSONAt)
			}(_p, _d, _s))
		}(&a.ObjectsOnly, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "objectsOnly")
		}
	}
	if _v, _ok := _raw["trueBranch"]; _ok {
		if _err := func(_p *AnyOfBooleanAndScalarBranchesTrueBranch, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal((*AnyOfBooleanAndScalarBranchesTrueBranch).decodeJSONAt(_p, _d, _s))
		}(&a.TrueBranch, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "trueBranch")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"bareObjectBranch",
		"constBranch",
		"falseBranch",
		"mixed",
		"objectsOnly",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	a._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		a._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "bareObjectBranch", "constBranch", "falseBranch", "mixed", "notBranch", "objectsOnly", "trueBranch":
			continue
		}
		if a.AdditionalProperties == nil {
			a.AdditionalProperties = make(map[string]json.RawMessage)
		}
		a.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (a AnyOfBooleanAndScalarBranches) MarshalJSON() ([]byte, error) {
	type Alias AnyOfBooleanAndScalarBranches
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range a.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks AnyOfBooleanAndScalarBranches against its JSON Schema constraints.
func (a AnyOfBooleanAndScalarBranches) Validate() error {
	// An optional property the source JSON did not carry left its Go zero
	// behind, which is not a value the schema ever saw. _jsonKeys records the
	// keys the JSON had; when nil the value was not built from JSON and
	// presence is unknowable, so the check still runs.
	if a._jsonKeys == nil || a._jsonKeys["bareObjectBranch"] {
		if err := a.BareObjectBranch.Validate(); err != nil {
			return jsonPathf(err, "bareObjectBranch")
		}
	}
	// An optional property the source JSON did not carry left its Go zero
	// behind, which is not a value the schema ever saw. _jsonKeys records the
	// keys the JSON had; when nil the value was not built from JSON and
	// presence is unknowable, so the check still runs.
	if a._jsonKeys == nil || a._jsonKeys["constBranch"] {
		if err := a.ConstBranch.Validate(); err != nil {
			return jsonPathf(err, "constBranch")
		}
	}
	if a.FalseBranch != nil {
		if err := a.FalseBranch.Validate(); err != nil {
			return jsonPathf(err, "falseBranch")
		}
	}
	// An optional property the source JSON did not carry left its Go zero
	// behind, which is not a value the schema ever saw. _jsonKeys records the
	// keys the JSON had; when nil the value was not built from JSON and
	// presence is unknowable, so the check still runs.
	if a._jsonKeys == nil || a._jsonKeys["mixed"] {
		if err := a.Mixed.Validate(); err != nil {
			return jsonPathf(err, "mixed")
		}
	}
	// An optional property the source JSON did not carry left its Go zero
	// behind, which is not a value the schema ever saw. _jsonKeys records the
	// keys the JSON had; when nil the value was not built from JSON and
	// presence is unknowable, so the check still runs.
	if a._jsonKeys == nil || a._jsonKeys["notBranch"] {
		if err := a.NotBranch.Validate(); err != nil {
			return jsonPathf(err, "notBranch")
		}
	}
	if a.ObjectsOnly != nil {
		if err := a.ObjectsOnly.Validate(); err != nil {
			return jsonPathf(err, "objectsOnly")
		}
	}
	// An optional property the source JSON did not carry left its Go zero
	// behind, which is not a value the schema ever saw. _jsonKeys records the
	// keys the JSON had; when nil the value was not built from JSON and
	// presence is unknowable, so the check still runs.
	if a._jsonKeys == nil || a._jsonKeys["trueBranch"] {
		if err := a.TrueBranch.Validate(); err != nil {
			return jsonPathf(err, "trueBranch")
		}
	}
	return nil
}
