// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	rt "github.com/mgilbir/schemagen/runtime"
)

// This file needs the runtime module github.com/mgilbir/schemagen/runtime at API
// level 1 or newer. If the compiler reports rt.API1 undefined, the release the
// build resolved is older than the schemagen that generated this file: update it
// with go get github.com/mgilbir/schemagen/runtime@latest.
var _ rt.API1

type DefaultSoleKeyword struct {
	B                    *bool                      `json:"b,omitempty"`
	S                    *string                    `json:"s,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON replaces d with the value the document holds. See
// decodeJSONAt.
func (d *DefaultSoleKeyword) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(d.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks DefaultSoleKeyword as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (d *DefaultSoleKeyword) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into d, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever d held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (d *DefaultSoleKeyword) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*d = DefaultSoleKeyword{}
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*DefaultSoleKeyword)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["b"]; _ok {
		if _err := func(_p **bool, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[*bool](_p, _d, _s, rt.DecodeValue[*bool])
		}(&d.B, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "b")
		}
	}
	if _v, _ok := _raw["s"]; _ok {
		if _err := func(_p **string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[*string](_p, _d, _s, rt.DecodeValue[*string])
		}(&d.S, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "s")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"b",
		"s",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "b", "s":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	d.AdditionalProperties = _apFiled

	return nil
}
func (d DefaultSoleKeyword) MarshalJSON() ([]byte, error) {
	_b, _err := d.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends d to _b as JSON. See rt.Enc.
func (d DefaultSoleKeyword) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := d.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range d.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, d.appendMemberJSON)
}

// encodeFieldsJSON gathers the members d's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (d DefaultSoleKeyword) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(d.B)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("b", _v)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitEmpty(d.S)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("s", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of d numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (d DefaultSoleKeyword) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// SetDefaults writes each schema default into the properties this value does
// not already carry.
//
// What "does not carry" means depends on what the Go field can hold. A pointer
// is nil exactly when the property was absent, since the decode assigns only for
// a key the document wrote, and is asked directly. A field with no nil state has
// one value standing for both an absent property and an explicit "", 0, false or
// [] -- issue #248 -- so it is asked twice: of _jsonKeys, the key set
// UnmarshalJSON records from the document itself, and of the field, which must
// still be untouched. A value that was never decoded from JSON has no key set,
// and the second test is what then keeps the fields it was built with.
//
// Nothing here touches _jsonKeys. A default is not a property the document sent,
// so a required property still has to have been sent, and SetDefaults cannot
// make one satisfiable that was not.
//
// Only a default that is valid where it lands is written at all: one the
// generator could prove valid is written as it stands, one it could not decide
// is written only if the runtime evaluator accepts it against the property's
// schema, and one that is invalid is not here.
func (d *DefaultSoleKeyword) SetDefaults() {
	if d.B == nil {
		_default := true
		d.B = &_default
	}
	if d.S == nil {
		_default := "d"
		d.S = &_default
	}
}

// Validate checks DefaultSoleKeyword against its JSON Schema constraints.
func (d DefaultSoleKeyword) Validate() error {
	return nil
}
