// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type Label string

func (l *Label) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Label")
	}
	type Alias Label
	return json.Unmarshal(data, (*Alias)(l))
}

// Validate checks Label against its JSON Schema constraints.
func (l Label) Validate() error {
	return nil
}

type Leaf struct {
	Lb                   bool                       `json:"lb"`
	Ls                   string                     `json:"ls"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (l *Leaf) UnmarshalJSON(data []byte) error {
	l.AdditionalProperties = nil
	l._jsonKeys = nil
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Leaf")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"lb",
			"ls",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias Leaf
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(l),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return err
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"lb",
			"ls",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return fmt.Errorf("%s: null is not allowed", _nullKey)
			}
		}
		l._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			l._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"lb": true,
			"ls": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if l.AdditionalProperties == nil {
				l.AdditionalProperties = make(map[string]json.RawMessage)
			}
			l.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (l Leaf) MarshalJSON() ([]byte, error) {
	type Alias Leaf
	aux := struct {
		Alias
	}{
		Alias: (Alias)(l),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range l.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// SetDefaults writes each schema default into the properties this value does
// not already carry.
//
// What "does not carry" means depends on what the Go field can hold. A pointer
// is nil exactly when the property was absent, since the decode assigns only for
// a key the document wrote, and is asked directly. A field with no nil state has
// one value standing for both an absent property and an explicit "", 0, false or
// [] -- issue #248 -- so it is asked twice: of _jsonKeys, the key set
// UnmarshalJSON records from the document itself, and of the field, which must
// still be untouched. A value that was never decoded from JSON has no key set,
// and the second test is what then keeps the fields it was built with.
//
// Nothing here touches _jsonKeys. A default is not a property the document sent,
// so a required property still has to have been sent, and SetDefaults cannot
// make one satisfiable that was not.
func (l *Leaf) SetDefaults() {
	{
		var _zero bool
		if !l._jsonKeys["lb"] && l.Lb == _zero {
			l.Lb = true
		}
	}
	{
		var _zero string
		if !l._jsonKeys["ls"] && l.Ls == _zero {
			l.Ls = "leaf"
		}
	}
}

// Validate checks Leaf against its JSON Schema constraints.
func (l Leaf) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if l._jsonKeys != nil {
		for _, _req := range []string{"lb", "ls"} {
			if !l._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

type Tags []string

func (t *Tags) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Tags")
	}
	if _err := checkJSONNulls(data, "value", &jsonNullRule{Elem: &jsonNullRule{Reject: true}}); _err != nil {
		return _err
	}
	type Alias Tags
	return json.Unmarshal(data, (*Alias)(t))
}

// Validate checks Tags against its JSON Schema constraints.
func (t Tags) Validate() error {
	return nil
}

type DefaultPresencePositions struct {
	AnyArr               []any                      `json:"anyArr,omitzero"`
	AnyMap               map[string]any             `json:"anyMap,omitzero"`
	ArrMismatch          []string                   `json:"arrMismatch,omitzero"`
	ArrOfNamed           []Label                    `json:"arrOfNamed,omitzero"`
	Leaf                 *Leaf                      `json:"leaf,omitempty"`
	LeafArr              []Leaf                     `json:"leafArr,omitzero"`
	LeafMap              map[string]Leaf            `json:"leafMap,omitzero"`
	MapOfArr             map[string][]int64         `json:"mapOfArr,omitzero"`
	Mismatch             *int64                     `json:"mismatch,omitempty"`
	NamedArr             Tags                       `json:"namedArr,omitzero"`
	NullArr              []string                   `json:"nullArr,omitzero"`
	OptArr               []string                   `json:"optArr,omitzero"`
	OptBool              *bool                      `json:"optBool,omitempty"`
	OptInt               *int64                     `json:"optInt,omitempty"`
	OptMap               map[string]string          `json:"optMap,omitzero"`
	OptNum               *float64                   `json:"optNum,omitempty"`
	OptStr               *string                    `json:"optStr,omitempty"`
	ReqArr               []string                   `json:"reqArr"`
	ReqBool              bool                       `json:"reqBool"`
	ReqInt               int64                      `json:"reqInt"`
	ReqMap               map[string]string          `json:"reqMap"`
	ReqNamed             Label                      `json:"reqNamed"`
	ReqNum               float64                    `json:"reqNum"`
	ReqStr               string                     `json:"reqStr"`
	StructDflt           *Leaf                      `json:"structDflt,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	_jsonNulls           map[string]bool            // set by UnmarshalJSON for the properties written as null, which the decoded value cannot hold
}

func (d *DefaultPresencePositions) UnmarshalJSON(data []byte) error {
	d.AdditionalProperties = nil
	d._jsonKeys = nil
	d._jsonNulls = nil
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type DefaultPresencePositions")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"anyArr",
			"anyMap",
			"arrMismatch",
			"arrOfNamed",
			"leaf",
			"leafArr",
			"leafMap",
			"mapOfArr",
			"mismatch",
			"namedArr",
			"nullArr",
			"optArr",
			"optBool",
			"optInt",
			"optMap",
			"optNum",
			"optStr",
			"reqArr",
			"reqBool",
			"reqInt",
			"reqMap",
			"reqNamed",
			"reqNum",
			"reqStr",
			"structDflt",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias DefaultPresencePositions
	aux := &struct {
		*Alias
		MapOfArr *map[string][]jsonInteger `json:"mapOfArr"`
		Mismatch **jsonInteger             `json:"mismatch"`
		OptInt   **jsonInteger             `json:"optInt"`
		ReqInt   *jsonInteger              `json:"reqInt"`
	}{
		Alias: (*Alias)(d),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return err
	}

	// A number written 1.0 is the integer 1 from draft 6 on, and the shadows
	// above are what let encoding/json see it. Each outer pointer is nil when
	// the property was absent or null, both of which leave the field as it was.
	if aux.MapOfArr != nil {
		_iv := *aux.MapOfArr
		d.MapOfArr = jsonIntegerMap(_iv, func(_ix0 []jsonInteger) []int64 {
			return jsonIntegerSlice(_ix0, func(_ix1 jsonInteger) int64 { return int64(_ix1) })
		})
	}
	if aux.Mismatch != nil {
		_iv := *aux.Mismatch
		d.Mismatch = jsonIntegerPtr(_iv, func(_ix0 jsonInteger) int64 { return int64(_ix0) })
	}
	if aux.OptInt != nil {
		_iv := *aux.OptInt
		d.OptInt = jsonIntegerPtr(_iv, func(_ix0 jsonInteger) int64 { return int64(_ix0) })
	}
	if aux.ReqInt != nil {
		_iv := *aux.ReqInt
		d.ReqInt = int64(_iv)
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"anyArr",
			"anyMap",
			"leaf",
			"mismatch",
			"namedArr",
			"optBool",
			"optInt",
			"optNum",
			"optStr",
			"reqBool",
			"reqInt",
			"reqNamed",
			"reqNum",
			"reqStr",
			"structDflt",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return fmt.Errorf("%s: null is not allowed", _nullKey)
			}
		}
		if _v, ok := raw["arrMismatch"]; ok {
			if err := checkJSONNulls(_v, "arrMismatch", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["arrOfNamed"]; ok {
			if err := checkJSONNulls(_v, "arrOfNamed", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["leafArr"]; ok {
			if err := checkJSONNulls(_v, "leafArr", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["leafMap"]; ok {
			if err := checkJSONNulls(_v, "leafMap", &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["mapOfArr"]; ok {
			if err := checkJSONNulls(_v, "mapOfArr", &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["nullArr"]; ok {
			if err := checkJSONNulls(_v, "nullArr", &jsonNullRule{Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["optArr"]; ok {
			if err := checkJSONNulls(_v, "optArr", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["optMap"]; ok {
			if err := checkJSONNulls(_v, "optMap", &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["reqArr"]; ok {
			if err := checkJSONNulls(_v, "reqArr", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["reqMap"]; ok {
			if err := checkJSONNulls(_v, "reqMap", &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		d._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			d._jsonKeys[_k] = true
		}
		// The properties whose schema permits a null. The decode above has
		// already turned one into a nil pointer, a nil collection or an
		// untouched zero -- the same state an absent property leaves -- so the
		// document's own bytes are the only place the difference still exists.
		// Validate reads this to pass over the keywords a null satisfies
		// vacuously, and MarshalJSON to write the null back. See issue #110.
		for _, _nullKey := range []string{
			"nullArr",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				if d._jsonNulls == nil {
					d._jsonNulls = make(map[string]bool, 1)
				}
				d._jsonNulls[_nullKey] = true
			}
		}
		knownFields := map[string]bool{
			"anyArr":      true,
			"anyMap":      true,
			"arrMismatch": true,
			"arrOfNamed":  true,
			"leaf":        true,
			"leafArr":     true,
			"leafMap":     true,
			"mapOfArr":    true,
			"mismatch":    true,
			"namedArr":    true,
			"nullArr":     true,
			"optArr":      true,
			"optBool":     true,
			"optInt":      true,
			"optMap":      true,
			"optNum":      true,
			"optStr":      true,
			"reqArr":      true,
			"reqBool":     true,
			"reqInt":      true,
			"reqMap":      true,
			"reqNamed":    true,
			"reqNum":      true,
			"reqStr":      true,
			"structDflt":  true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if d.AdditionalProperties == nil {
				d.AdditionalProperties = make(map[string]json.RawMessage)
			}
			d.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (d DefaultPresencePositions) MarshalJSON() ([]byte, error) {
	type Alias DefaultPresencePositions
	aux := struct {
		Alias
	}{
		Alias: (Alias)(d),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	// The properties the source document wrote as null. Nothing left in the
	// decoded value says they were there -- a null leaves the nil pointer or the
	// untouched zero an absent property leaves -- so writing them back has to
	// come from the record UnmarshalJSON kept. See issue #110.
	//
	// Only where the field still holds what the null left it holding. A caller
	// who decoded a null and then assigned a value has said something newer than
	// the document did, and writing the null over it would discard the
	// assignment; the record is about a value nobody has touched. What the
	// untouched state looks like is read off a zero of this very struct rather
	// than from a per-field literal, so a field type's own MarshalJSON decides
	// for itself and nothing here has to know how it spells "empty".
	if len(d._jsonNulls) > 0 {
		var _zero Alias
		if _zeroData, _zeroErr := json.Marshal(_zero); _zeroErr == nil {
			var _zeroObj map[string]json.RawMessage
			if json.Unmarshal(_zeroData, &_zeroObj) == nil {
				for _k := range d._jsonNulls {
					if _cur, _present := obj[_k]; !_present || string(_cur) == string(_zeroObj[_k]) {
						obj[_k] = json.RawMessage("null")
					}
				}
			}
		}
	}
	for k, v := range d.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// SetDefaults writes each schema default into the properties this value does
// not already carry.
//
// What "does not carry" means depends on what the Go field can hold. A pointer
// is nil exactly when the property was absent, since the decode assigns only for
// a key the document wrote, and is asked directly. A field with no nil state has
// one value standing for both an absent property and an explicit "", 0, false or
// [] -- issue #248 -- so it is asked twice: of _jsonKeys, the key set
// UnmarshalJSON records from the document itself, and of the field, which must
// still be untouched. A value that was never decoded from JSON has no key set,
// and the second test is what then keeps the fields it was built with.
//
// Nothing here touches _jsonKeys. A default is not a property the document sent,
// so a required property still has to have been sent, and SetDefaults cannot
// make one satisfiable that was not.
func (d *DefaultPresencePositions) SetDefaults() {
	if !d._jsonKeys["anyArr"] && d.AnyArr == nil {
		d.AnyArr = []any{"z", float64(1), true}
	}
	if !d._jsonKeys["anyMap"] && d.AnyMap == nil {
		d.AnyMap = map[string]any{"a": "b", "k": "v"}
	}
	if !d._jsonKeys["arrOfNamed"] && d.ArrOfNamed == nil {
		d.ArrOfNamed = []Label{Label("q")}
	}
	if !d._jsonKeys["mapOfArr"] && d.MapOfArr == nil {
		d.MapOfArr = map[string][]int64{"a": {1, 2}}
	}
	if !d._jsonKeys["namedArr"] && d.NamedArr == nil {
		d.NamedArr = Tags{"t"}
	}
	if !d._jsonKeys["nullArr"] && d.NullArr == nil {
		d.NullArr = []string{"z"}
	}
	if !d._jsonKeys["optArr"] && d.OptArr == nil {
		d.OptArr = []string{"z"}
	}
	if d.OptBool == nil {
		_default := true
		d.OptBool = &_default
	}
	if d.OptInt == nil {
		_default := int64(7)
		d.OptInt = &_default
	}
	if !d._jsonKeys["optMap"] && d.OptMap == nil {
		d.OptMap = map[string]string{"k": "v"}
	}
	if d.OptNum == nil {
		_default := float64(1.5)
		d.OptNum = &_default
	}
	if d.OptStr == nil {
		_default := "dflt"
		d.OptStr = &_default
	}
	if !d._jsonKeys["reqArr"] && d.ReqArr == nil {
		d.ReqArr = []string{"z"}
	}
	{
		var _zero bool
		if !d._jsonKeys["reqBool"] && d.ReqBool == _zero {
			d.ReqBool = true
		}
	}
	{
		var _zero int64
		if !d._jsonKeys["reqInt"] && d.ReqInt == _zero {
			d.ReqInt = 7
		}
	}
	if !d._jsonKeys["reqMap"] && d.ReqMap == nil {
		d.ReqMap = map[string]string{"k": "v"}
	}
	{
		var _zero Label
		if !d._jsonKeys["reqNamed"] && d.ReqNamed == _zero {
			d.ReqNamed = Label("named")
		}
	}
	{
		var _zero float64
		if !d._jsonKeys["reqNum"] && d.ReqNum == _zero {
			d.ReqNum = 1.5
		}
	}
	{
		var _zero string
		if !d._jsonKeys["reqStr"] && d.ReqStr == _zero {
			d.ReqStr = "dflt"
		}
	}
}

// Validate checks DefaultPresencePositions against its JSON Schema constraints.
func (d DefaultPresencePositions) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if d._jsonKeys != nil {
		for _, _req := range []string{"reqArr", "reqBool", "reqInt", "reqMap", "reqNamed", "reqNum", "reqStr"} {
			if !d._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	for _i, _item := range d.ArrOfNamed {
		if err := _item.Validate(); err != nil {
			return fmt.Errorf("arrOfNamed[%d].%w", _i, err)
		}
	}
	if d.Leaf != nil {
		if err := d.Leaf.Validate(); err != nil {
			return fmt.Errorf("leaf.%w", err)
		}
	}
	for _i, _item := range d.LeafArr {
		if err := _item.Validate(); err != nil {
			return fmt.Errorf("leafArr[%d].%w", _i, err)
		}
	}
	for _k, _val := range d.LeafMap {
		if err := _val.Validate(); err != nil {
			return fmt.Errorf("leafMap[%q].%w", _k, err)
		}
	}
	if d.NamedArr != nil {
		if err := d.NamedArr.Validate(); err != nil {
			return fmt.Errorf("namedArr.%w", err)
		}
	}
	if err := d.ReqNamed.Validate(); err != nil {
		return fmt.Errorf("reqNamed.%w", err)
	}
	if d.StructDflt != nil {
		if err := d.StructDflt.Validate(); err != nil {
			return fmt.Errorf("structDflt.%w", err)
		}
	}
	return nil
}
