// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
	"math"
)

// Draft3typeUnion accepts any JSON value and validates that it is one of the allowed types.
type Draft3typeUnion struct {
	_raw json.RawMessage
}

func (d *Draft3typeUnion) UnmarshalJSON(data []byte) error {
	d._raw = append(d._raw[:0], data...)
	return nil
}

func (d Draft3typeUnion) MarshalJSON() ([]byte, error) {
	if len(d._raw) == 0 {
		return []byte("null"), nil
	}
	return d._raw, nil
}

func (d Draft3typeUnion) Raw() json.RawMessage { return d._raw }

func (d Draft3typeUnion) String() string { return string(d._raw) }

// Validate checks Draft3typeUnion against its JSON Schema type constraint.
func (d Draft3typeUnion) Validate() error {
	var _v any
	if _err := json.Unmarshal(d._raw, &_v); _err != nil {
		return fmt.Errorf("type: cannot decode value: %w", _err)
	}
	_typeBranchValid := false
	{
		_branchMatches := true
		if _, _ok := _v.(string); !_ok {
			_branchMatches = false
		}
		if _branchMatches {
			_typeBranchValid = true
		}
	}
	if _typeBranchValid {
		return nil
	}
	if _v == nil {
		return fmt.Errorf("type: null is not allowed")
	}
	switch _tv := _v.(type) {
	case float64:
		if _tv != math.Trunc(_tv) || math.IsInf(_tv, 0) {
			return fmt.Errorf("type: expected integer, got number")
		}
		return nil
	case string:
		_ = _tv
		return fmt.Errorf("type: string is not allowed")
	case bool:
		_ = _tv
		return fmt.Errorf("type: boolean is not allowed")
	case []any:
		_ = _tv
		return fmt.Errorf("type: array is not allowed")
	case map[string]any:
		_ = _tv
		return fmt.Errorf("type: object is not allowed")
	default:
		return fmt.Errorf("type: unexpected value type %T", _v)
	}
}
