// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// Draft3typeMulti accepts any JSON value and validates that it is one of the allowed types.
type Draft3typeMulti struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces d with the value the document holds. See
// decodeJSONAt.
func (d *Draft3typeMulti) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(d.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever d held.
func (d *Draft3typeMulti) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*d = Draft3typeMulti{}
	d._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (d Draft3typeMulti) MarshalJSON() ([]byte, error) {
	if len(d._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), d._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (d Draft3typeMulti) Raw() json.RawMessage { return append(json.RawMessage(nil), d._raw...) }

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (d Draft3typeMulti) IsZero() bool { return len(d._raw) == 0 }

func (d Draft3typeMulti) String() string { return string(d._raw) }

// Validate checks Draft3typeMulti against its JSON Schema type constraint.
func (d Draft3typeMulti) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(d._raw) == 0 {
		return nil
	}
	var _v any
	if _err := jsonDecodeNumbers(d._raw, &_v); _err != nil {
		return fmt.Errorf("type: cannot decode value: %w", _err)
	}
	_typeBranchValid := false
	{
		_branchMatches := true
		{
			// A schema-valued type branch lists one or more allowed JSON types;
			// the value matches when it is any one of them.
			_typeOk := false
			if _, _ok := _v.(string); _ok {
				_typeOk = true
			}
			if !_typeOk {
				_branchMatches = false
			}
		}
		if _branchMatches {
			_typeBranchValid = true
		}
	}
	{
		_branchMatches := true
		{
			// A schema-valued type branch lists one or more allowed JSON types;
			// the value matches when it is any one of them.
			_typeOk := false
			if _, _ok := _v.([]any); _ok {
				_typeOk = true
			}
			if _v == nil {
				_typeOk = true
			}
			if !_typeOk {
				_branchMatches = false
			}
		}
		if _branchMatches {
			_typeBranchValid = true
		}
	}
	if _typeBranchValid {
		return nil
	}
	if _v == nil {
		return fmt.Errorf("type: null is not allowed")
	}
	switch _tv := _v.(type) {
	case json.Number:
		_ = _tv
		return fmt.Errorf("type: number is not allowed")
	case string:
		_ = _tv
		return fmt.Errorf("type: string is not allowed")
	case bool:
		_ = _tv
		return fmt.Errorf("type: boolean is not allowed")
	case []any:
		_ = _tv
		return fmt.Errorf("type: array is not allowed")
	case map[string]any:
		_ = _tv
		return fmt.Errorf("type: object is not allowed")
	default:
		return fmt.Errorf("type: unexpected value type %T", _v)
	}
}
