// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// No accepts any JSON value and validates a root-level "not" constraint.
type No struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces n with the value the document holds. See
// decodeJSONAt.
func (n *No) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(n.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever n held.
func (n *No) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*n = No{}
	n._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (n No) MarshalJSON() ([]byte, error) {
	if len(n._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), n._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (n No) Raw() json.RawMessage { return append(json.RawMessage(nil), n._raw...) }

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (n No) IsZero() bool { return len(n._raw) == 0 }

func (n No) String() string { return string(n._raw) }

// Validate checks No against its JSON Schema "not" constraint.
func (n No) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(n._raw) == 0 {
		return nil
	}
	return fmt.Errorf("not: value is forbidden (not schema matches all values)")
}

type FalsePropertyExplicitNullListItem struct {
	Inner                any                        `json:"inner,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces f with the value the document holds. See
// decodeJSONAt.
func (f *FalsePropertyExplicitNullListItem) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(f.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into f, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever f held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (f *FalsePropertyExplicitNullListItem) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*f = FalsePropertyExplicitNullListItem{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[FalsePropertyExplicitNullListItem](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["inner"]; _ok {
		if _err := func(_p *any, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[any](_p, _d, _s, jsonDecodeValue[any])
		}(&f.Inner, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "inner")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"inner",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	f._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		f._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "inner":
			continue
		}
		if f.AdditionalProperties == nil {
			f.AdditionalProperties = make(map[string]json.RawMessage)
		}
		f.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (f FalsePropertyExplicitNullListItem) MarshalJSON() ([]byte, error) {
	type Alias FalsePropertyExplicitNullListItem
	aux := struct {
		Alias
	}{
		Alias: (Alias)(f),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range f.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks FalsePropertyExplicitNullListItem against its JSON Schema constraints.
func (f FalsePropertyExplicitNullListItem) Validate() error {
	if f.Inner != nil || f._jsonKeys["inner"] {
		return fmt.Errorf("inner: property is forbidden (no value satisfies its schema)")
	}
	return nil
}

type FalsePropertyExplicitNullNested struct {
	Inner                any                        `json:"inner,omitempty"`
	Ok                   *string                    `json:"ok,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces f with the value the document holds. See
// decodeJSONAt.
func (f *FalsePropertyExplicitNullNested) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(f.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into f, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever f held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (f *FalsePropertyExplicitNullNested) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*f = FalsePropertyExplicitNullNested{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[FalsePropertyExplicitNullNested](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["inner"]; _ok {
		if _err := func(_p *any, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[any](_p, _d, _s, jsonDecodeValue[any])
		}(&f.Inner, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "inner")
		}
	}
	if _v, _ok := _raw["ok"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&f.Ok, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "ok")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"inner",
		"ok",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	f._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		f._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "inner", "ok":
			continue
		}
		if f.AdditionalProperties == nil {
			f.AdditionalProperties = make(map[string]json.RawMessage)
		}
		f.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (f FalsePropertyExplicitNullNested) MarshalJSON() ([]byte, error) {
	type Alias FalsePropertyExplicitNullNested
	aux := struct {
		Alias
	}{
		Alias: (Alias)(f),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range f.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks FalsePropertyExplicitNullNested against its JSON Schema constraints.
func (f FalsePropertyExplicitNullNested) Validate() error {
	if f.Inner != nil || f._jsonKeys["inner"] {
		return fmt.Errorf("inner: property is forbidden (no value satisfies its schema)")
	}
	return nil
}

// FalsePropertyExplicitNull - A property whose schema is the boolean `false` must refuse the key however it is written. The rule was emitted as `field != nil`, and an explicit null decodes to exactly what an absent property leaves, so {"inline":null} passed a check whose whole job is to refuse the key's presence (issue #127). The $ref spelling beside it already refused both, through the forbidding wrapper its target generates.
type FalsePropertyExplicitNull struct {
	Inline               any                                 `json:"inline,omitempty"`
	Nested               *FalsePropertyExplicitNullNested    `json:"nested,omitempty"`
	Ok                   *string                             `json:"ok,omitempty"`
	AdditionalProperties map[string]json.RawMessage          `json:"-"`
	_jsonKeys            map[string]bool                     // set by UnmarshalJSON for optional field / dependentSchemas validation
	List                 []FalsePropertyExplicitNullListItem `json:"list,omitzero"`
	ViaRef               No                                  `json:"viaRef,omitzero"`
}

// UnmarshalJSON replaces f with the value the document holds. See
// decodeJSONAt.
func (f *FalsePropertyExplicitNull) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(f.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into f, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever f held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (f *FalsePropertyExplicitNull) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*f = FalsePropertyExplicitNull{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[FalsePropertyExplicitNull](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["inline"]; _ok {
		if _err := func(_p *any, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[any](_p, _d, _s, jsonDecodeValue[any])
		}(&f.Inline, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "inline")
		}
	}
	if _v, _ok := _raw["list"]; _ok {
		if _err := func(_p *[]FalsePropertyExplicitNullListItem, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeSlice[FalsePropertyExplicitNullListItem](_p, _d, _s, func(_p *FalsePropertyExplicitNullListItem, _d *jsonDoc, _s jsonSpan) error {
				return jsonDecodeRefusal((*FalsePropertyExplicitNullListItem).decodeJSONAt(_p, _d, _s))
			})
		}(&f.List, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "list")
		}
	}
	if _v, _ok := _raw["nested"]; _ok {
		if _err := func(_p **FalsePropertyExplicitNullNested, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal(func(_p **FalsePropertyExplicitNullNested, _d *jsonDoc, _s jsonSpan) error {
				return jsonDecodePtr[*FalsePropertyExplicitNullNested, FalsePropertyExplicitNullNested](_p, _d, _s, (*FalsePropertyExplicitNullNested).decodeJSONAt)
			}(_p, _d, _s))
		}(&f.Nested, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "nested")
		}
	}
	if _v, _ok := _raw["ok"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&f.Ok, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "ok")
		}
	}
	if _v, _ok := _raw["viaRef"]; _ok {
		if _err := func(_p *No, _d *jsonDoc, _s jsonSpan) error { return jsonDecodeRefusal((*No).decodeJSONAt(_p, _d, _s)) }(&f.ViaRef, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "viaRef")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"inline",
		"nested",
		"ok",
		"viaRef",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	if _v, ok := _raw["list"]; ok {
		if err := checkJSONNullsAt(_d, _v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
			return jsonPathf(err, "%s", "list")
		}
	}
	f._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		f._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "inline", "list", "nested", "ok", "viaRef":
			continue
		}
		if f.AdditionalProperties == nil {
			f.AdditionalProperties = make(map[string]json.RawMessage)
		}
		f.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (f FalsePropertyExplicitNull) MarshalJSON() ([]byte, error) {
	type Alias FalsePropertyExplicitNull
	aux := struct {
		Alias
	}{
		Alias: (Alias)(f),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range f.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks FalsePropertyExplicitNull against its JSON Schema constraints.
func (f FalsePropertyExplicitNull) Validate() error {
	if f.Inline != nil || f._jsonKeys["inline"] {
		return fmt.Errorf("inline: property is forbidden (no value satisfies its schema)")
	}
	for _i, _item := range f.List {
		if err := _item.Validate(); err != nil {
			return jsonPathf(err, "list[%d]", _i)
		}
	}
	if f.Nested != nil {
		if err := f.Nested.Validate(); err != nil {
			return jsonPathf(err, "nested")
		}
	}
	// An optional property the source JSON did not carry left its Go zero
	// behind, which is not a value the schema ever saw. _jsonKeys records the
	// keys the JSON had; when nil the value was not built from JSON and
	// presence is unknowable, so the check still runs.
	if f._jsonKeys == nil || f._jsonKeys["viaRef"] {
		if err := f.ViaRef.Validate(); err != nil {
			return jsonPathf(err, "viaRef")
		}
	}
	return nil
}
