// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type Addr string

func (a *Addr) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	type Alias Addr
	return jsonDecodeRefusal(json.Unmarshal(data, (*Alias)(a)))
}

// Validate checks Addr against its JSON Schema constraints.
func (a Addr) Validate() error {
	return nil
}

type Stamp string

func (s *Stamp) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	type Alias Stamp
	return jsonDecodeRefusal(json.Unmarshal(data, (*Alias)(s)))
}

// Validate checks Stamp against its JSON Schema constraints.
func (s Stamp) Validate() error {
	return nil
}

type StampAlias Stamp

func (s *StampAlias) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	var _target Stamp
	if _err := json.Unmarshal(data, &_target); _err != nil {
		return jsonDecodeRefusal(_err)
	}
	*s = StampAlias(_target)
	return nil
}

// Validate checks StampAlias against its JSON Schema constraints.
func (s StampAlias) Validate() error {
	// Returned as it stands: the type this delegates to answers for the very same
	// value, so there is no step of path between the two and nothing to put in
	// front of its message. Wrapping it also lost what the message had recorded
	// about how a container must join it. See issue #279.
	if _err := (Stamp(s)).Validate(); _err != nil {
		return _err
	}
	return nil
}

// FormatAliasPositions - Every position a format that maps to a self-marshalling Go type can reach through a named definition
type FormatAliasPositions struct {
	Addr                 *Addr                      `json:"addr,omitempty"`
	ChainedStamp         *StampAlias                `json:"chained_stamp,omitempty"`
	OptionalStamp        *Stamp                     `json:"optional_stamp,omitempty"`
	StampMap             map[string]Stamp           `json:"stamp_map,omitzero"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	RequiredStamp        Stamp                      `json:"required_stamp"`
	AddrList             []Addr                     `json:"addr_list,omitzero"`
	StampGrid            [][]Stamp                  `json:"stamp_grid,omitzero"`
	StampList            []Stamp                    `json:"stamp_list,omitzero"`
	Tuple                []any                      `json:"tuple,omitzero"`
}

func (f *FormatAliasPositions) UnmarshalJSON(data []byte) error {
	f.AdditionalProperties = nil
	f._jsonKeys = nil
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"addr",
			"addr_list",
			"chained_stamp",
			"optional_stamp",
			"required_stamp",
			"stamp_grid",
			"stamp_list",
			"stamp_map",
			"tuple",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias FormatAliasPositions
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(f),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return jsonDecodeMemberError(data, err, []jsonMemberDecode{
			{name: "addr", decode: jsonDecodeValue[*Addr]},
			{name: "addr_list", decode: jsonDecodeItems(jsonDecodeValue[Addr])},
			{name: "chained_stamp", decode: jsonDecodeValue[*StampAlias]},
			{name: "optional_stamp", decode: jsonDecodeValue[*Stamp]},
			{name: "required_stamp", decode: jsonDecodeValue[Stamp]},
			{name: "stamp_grid", decode: jsonDecodeItems(jsonDecodeItems(jsonDecodeValue[Stamp]))},
			{name: "stamp_list", decode: jsonDecodeItems(jsonDecodeValue[Stamp])},
			{name: "stamp_map", decode: jsonDecodeValues(jsonDecodeValue[Stamp])},
			{name: "tuple", decode: jsonDecodeItems(jsonDecodeValue[any])},
		})
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"addr",
			"chained_stamp",
			"optional_stamp",
			"required_stamp",
			"tuple",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
			}
		}
		if _v, ok := raw["addr_list"]; ok {
			if err := checkJSONNullsAt(_v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return jsonPathf(err, "%s", "addr_list")
			}
		}
		if _v, ok := raw["stamp_grid"]; ok {
			if err := checkJSONNullsAt(_v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}}); err != nil {
				return jsonPathf(err, "%s", "stamp_grid")
			}
		}
		if _v, ok := raw["stamp_list"]; ok {
			if err := checkJSONNullsAt(_v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return jsonPathf(err, "%s", "stamp_list")
			}
		}
		if _v, ok := raw["stamp_map"]; ok {
			if err := checkJSONNullsAt(_v, &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return jsonPathf(err, "%s", "stamp_map")
			}
		}
		f._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			f._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"addr":           true,
			"addr_list":      true,
			"chained_stamp":  true,
			"optional_stamp": true,
			"required_stamp": true,
			"stamp_grid":     true,
			"stamp_list":     true,
			"stamp_map":      true,
			"tuple":          true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if f.AdditionalProperties == nil {
				f.AdditionalProperties = make(map[string]json.RawMessage)
			}
			f.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (f FormatAliasPositions) MarshalJSON() ([]byte, error) {
	type Alias FormatAliasPositions
	aux := struct {
		Alias
	}{
		Alias: (Alias)(f),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range f.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks FormatAliasPositions against its JSON Schema constraints.
func (f FormatAliasPositions) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if f._jsonKeys != nil {
		for _, _req := range []string{"required_stamp"} {
			if !f._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	if f.Addr != nil {
		if err := f.Addr.Validate(); err != nil {
			return jsonPathf(err, "addr")
		}
	}
	for _i, _item := range f.AddrList {
		if err := _item.Validate(); err != nil {
			return jsonPathf(err, "addr_list[%d]", _i)
		}
	}
	if f.ChainedStamp != nil {
		if err := f.ChainedStamp.Validate(); err != nil {
			return jsonPathf(err, "chained_stamp")
		}
	}
	if f.OptionalStamp != nil {
		if err := f.OptionalStamp.Validate(); err != nil {
			return jsonPathf(err, "optional_stamp")
		}
	}
	if err := f.RequiredStamp.Validate(); err != nil {
		return jsonPathf(err, "required_stamp")
	}
	for _i, _item := range f.StampList {
		if err := _item.Validate(); err != nil {
			return jsonPathf(err, "stamp_list[%d]", _i)
		}
	}
	for _k, _val := range f.StampMap {
		if err := _val.Validate(); err != nil {
			return jsonPathf(err, "stamp_map[%q]", _k)
		}
	}
	for _i0, _e0 := range f.StampGrid {
		for _i1, _e1 := range _e0 {
			if _err := _e1.Validate(); _err != nil {
				return jsonPathf(_err, "stamp_grid[%d][%d]", _i0, _i1)
			}
		}
	}
	// Tuple items: validate each position against its schema type.
	for _idx, _elem := range f.Tuple {
		_ = _elem
		if _idx == 0 {
			_raw, _mErr := json.Marshal(_elem)
			if _mErr != nil {
				return fmt.Errorf("tuple: items[%d]: %w", _idx, _mErr)
			}
			var _typed Stamp
			if _uErr := json.Unmarshal(_raw, &_typed); _uErr != nil {
				return fmt.Errorf("tuple: items[%d]: %w", _idx, _uErr)
			}
			if _vErr := _typed.Validate(); _vErr != nil {
				return fmt.Errorf("tuple: items[%d]: %w", _idx, _vErr)
			}
		}
		if _idx == 1 {
			_raw, _mErr := json.Marshal(_elem)
			if _mErr != nil {
				return fmt.Errorf("tuple: items[%d]: %w", _idx, _mErr)
			}
			var _typed Addr
			if _uErr := json.Unmarshal(_raw, &_typed); _uErr != nil {
				return fmt.Errorf("tuple: items[%d]: %w", _idx, _uErr)
			}
			if _vErr := _typed.Validate(); _vErr != nil {
				return fmt.Errorf("tuple: items[%d]: %w", _idx, _vErr)
			}
		}
	}
	return nil
}
