// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type Day string

func (d *Day) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Day")
	}
	type Alias Day
	return json.Unmarshal(data, (*Alias)(d))
}

// Validate checks Day against its JSON Schema constraints.
func (d Day) Validate() error {
	return nil
}

type Email string

func (e *Email) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Email")
	}
	type Alias Email
	return json.Unmarshal(data, (*Alias)(e))
}

// Validate checks Email against its JSON Schema constraints.
func (e Email) Validate() error {
	return nil
}

type Site string

func (s *Site) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Site")
	}
	type Alias Site
	return json.Unmarshal(data, (*Alias)(s))
}

// Validate checks Site against its JSON Schema constraints.
func (s Site) Validate() error {
	return nil
}

type UUID string

func (u *UUID) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type UUID")
	}
	type Alias UUID
	return json.Unmarshal(data, (*Alias)(u))
}

// Validate checks UUID against its JSON Schema constraints.
func (u UUID) Validate() error {
	return nil
}

type V4 string

func (v *V4) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type V4")
	}
	type Alias V4
	return json.Unmarshal(data, (*Alias)(v))
}

// Validate checks V4 against its JSON Schema constraints.
func (v V4) Validate() error {
	return nil
}

type V6 string

func (v *V6) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type V6")
	}
	type Alias V6
	return json.Unmarshal(data, (*Alias)(v))
}

// Validate checks V6 against its JSON Schema constraints.
func (v V6) Validate() error {
	return nil
}

// FormatAliasAssertions - Formats behind a $ref, where the assertion has to be carried by the named type's own Validate
type FormatAliasAssertions struct {
	Day                  *Day                       `json:"day,omitempty"`
	Email                *Email                     `json:"email,omitempty"`
	EmailMap             map[string]Email           `json:"email_map,omitzero"`
	Site                 *Site                      `json:"site,omitempty"`
	UUID                 *UUID                      `json:"uuid,omitempty"`
	V4                   *V4                        `json:"v4,omitempty"`
	V4List               []V4                       `json:"v4_list,omitzero"`
	V6                   *V6                        `json:"v6,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (f *FormatAliasAssertions) UnmarshalJSON(data []byte) error {
	f.AdditionalProperties = nil
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type FormatAliasAssertions")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"day",
			"email",
			"email_map",
			"site",
			"uuid",
			"v4",
			"v4_list",
			"v6",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias FormatAliasAssertions
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(f),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return err
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"day",
			"email",
			"site",
			"uuid",
			"v4",
			"v6",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return fmt.Errorf("%s: null is not allowed", _nullKey)
			}
		}
		if _v, ok := raw["email_map"]; ok {
			if err := checkJSONNulls(_v, "email_map", &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		if _v, ok := raw["v4_list"]; ok {
			if err := checkJSONNulls(_v, "v4_list", &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
				return err
			}
		}
		knownFields := map[string]bool{
			"day":       true,
			"email":     true,
			"email_map": true,
			"site":      true,
			"uuid":      true,
			"v4":        true,
			"v4_list":   true,
			"v6":        true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if f.AdditionalProperties == nil {
				f.AdditionalProperties = make(map[string]json.RawMessage)
			}
			f.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (f FormatAliasAssertions) MarshalJSON() ([]byte, error) {
	type Alias FormatAliasAssertions
	aux := struct {
		Alias
	}{
		Alias: (Alias)(f),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range f.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks FormatAliasAssertions against its JSON Schema constraints.
func (f FormatAliasAssertions) Validate() error {
	if f.Day != nil {
		if err := f.Day.Validate(); err != nil {
			return fmt.Errorf("day.%w", err)
		}
	}
	if f.Email != nil {
		if err := f.Email.Validate(); err != nil {
			return fmt.Errorf("email.%w", err)
		}
	}
	for _k, _val := range f.EmailMap {
		if err := _val.Validate(); err != nil {
			return fmt.Errorf("email_map[%q].%w", _k, err)
		}
	}
	if f.Site != nil {
		if err := f.Site.Validate(); err != nil {
			return fmt.Errorf("site.%w", err)
		}
	}
	if f.UUID != nil {
		if err := f.UUID.Validate(); err != nil {
			return fmt.Errorf("uuid.%w", err)
		}
	}
	if f.V4 != nil {
		if err := f.V4.Validate(); err != nil {
			return fmt.Errorf("v4.%w", err)
		}
	}
	for _i, _item := range f.V4List {
		if err := _item.Validate(); err != nil {
			return fmt.Errorf("v4_list[%d].%w", _i, err)
		}
	}
	if f.V6 != nil {
		if err := f.V6.Validate(); err != nil {
			return fmt.Errorf("v6.%w", err)
		}
	}
	return nil
}
