// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type NeedsA struct {
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces n with the value the document holds. See
// decodeJSONAt.
func (n *NeedsA) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(n.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into n, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever n held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (n *NeedsA) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*n = NeedsA{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*NeedsA)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	n._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		n._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		if n.AdditionalProperties == nil {
			n.AdditionalProperties = make(map[string]json.RawMessage)
		}
		n.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (n NeedsA) MarshalJSON() ([]byte, error) {
	_b, _err := n.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends n to _b as JSON. See jsonEnc.
func (n NeedsA) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := n.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range n.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, n.appendMemberJSON)
}

// encodeFieldsJSON gathers the members n's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (n NeedsA) encodeFieldsJSON(_o *jsonObj) error {
	return nil
}

// appendMemberJSON writes the member of n numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (n NeedsA) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// jsonIdentity is n's identity as JSON, read off its members by the rules
// appendJSON writes them by. See jsonID.
func (n *NeedsA) jsonIdentity(_m *jsonValidation) (jsonID, error) {
	_o := jsonIDObj{m: _m}
	for _key, _member := range n.AdditionalProperties {
		_o.idHeld(_key, _member)
	}
	return _o.idOf(n.jsonIdentityMember, _m)
}

// jsonIdentityMember reads the member of n numbered idx, as
// appendMemberJSON writes it. key is the member's key, which names the
// additionalProperties value to read.
func (n *NeedsA) jsonIdentityMember(_idx int, _key string, _m *jsonValidation) (jsonID, error) {
	_ = _key
	switch _idx {
	}
	return jsonIDNull(_m)
}

// Validate checks NeedsA against its JSON Schema constraints.
func (n NeedsA) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if n._jsonKeys != nil {
		for _, _req := range []string{"a"} {
			if !n._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

type InferredArrayTupleDraft7OneItem struct {
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces i with the value the document holds. See
// decodeJSONAt.
func (i *InferredArrayTupleDraft7OneItem) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(i.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into i, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever i held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (i *InferredArrayTupleDraft7OneItem) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*i = InferredArrayTupleDraft7OneItem{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*InferredArrayTupleDraft7OneItem)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	i._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		i._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		if i.AdditionalProperties == nil {
			i.AdditionalProperties = make(map[string]json.RawMessage)
		}
		i.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (i InferredArrayTupleDraft7OneItem) MarshalJSON() ([]byte, error) {
	_b, _err := i.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends i to _b as JSON. See jsonEnc.
func (i InferredArrayTupleDraft7OneItem) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := i.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range i.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, i.appendMemberJSON)
}

// encodeFieldsJSON gathers the members i's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (i InferredArrayTupleDraft7OneItem) encodeFieldsJSON(_o *jsonObj) error {
	return nil
}

// appendMemberJSON writes the member of i numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (i InferredArrayTupleDraft7OneItem) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// jsonIdentity is i's identity as JSON, read off its members by the rules
// appendJSON writes them by. See jsonID.
func (i *InferredArrayTupleDraft7OneItem) jsonIdentity(_m *jsonValidation) (jsonID, error) {
	_o := jsonIDObj{m: _m}
	for _key, _member := range i.AdditionalProperties {
		_o.idHeld(_key, _member)
	}
	return _o.idOf(i.jsonIdentityMember, _m)
}

// jsonIdentityMember reads the member of i numbered idx, as
// appendMemberJSON writes it. key is the member's key, which names the
// additionalProperties value to read.
func (i *InferredArrayTupleDraft7OneItem) jsonIdentityMember(_idx int, _key string, _m *jsonValidation) (jsonID, error) {
	_ = _key
	switch _idx {
	}
	return jsonIDNull(_m)
}

// Validate checks InferredArrayTupleDraft7OneItem against its JSON Schema constraints.
func (i InferredArrayTupleDraft7OneItem) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if i._jsonKeys != nil {
		for _, _req := range []string{"a"} {
			if !i._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

// InferredArrayTupleDraft7One accepts any JSON value. Constraints apply only when the value is array.
type InferredArrayTupleDraft7One struct {
	_value []any
	_raw   json.RawMessage
	_isRaw bool
}

func (i *InferredArrayTupleDraft7One) UnmarshalJSON(data []byte) error {
	*i = InferredArrayTupleDraft7One{}
	// Null is a non-matching type for inferred schemas — store as raw.
	if string(data) == "null" {
		i._raw = append(json.RawMessage(nil), data...)
		i._isRaw = true
		return nil
	}
	// Try typed unmarshal first.
	if _err := json.Unmarshal(data, &i._value); _err == nil {
		i._isRaw = false
		return nil
	}
	// Non-matching type — store raw bytes, accept silently per JSON Schema. A
	// value that is not JSON at all is not a value of some other type, and is
	// refused in encoding/json's words; encoding/json never hands one over, so
	// only a direct caller reaches that.
	if !json.Valid(data) {
		var _v json.RawMessage
		return jsonDecodeRefusal(json.Unmarshal(data, &_v))
	}
	i._raw = append(json.RawMessage(nil), data...)
	i._isRaw = true
	return nil
}
func (i InferredArrayTupleDraft7One) MarshalJSON() ([]byte, error) {
	if i._isRaw {
		if len(i._raw) == 0 {
			return []byte("null"), nil
		}
		// A copy: the value's own bytes, handed out, are bytes a caller can
		// rewrite the value through.
		return append([]byte(nil), i._raw...), nil
	}
	return json.Marshal(i._value)
}
func (i InferredArrayTupleDraft7One) Slice() []any  { return i._value }
func (i InferredArrayTupleDraft7One) IsArray() bool { return !i._isRaw }
func (i InferredArrayTupleDraft7One) Raw() json.RawMessage {
	if i._isRaw {
		return append(json.RawMessage(nil), i._raw...)
	}
	_b, _ := json.Marshal(i._value)
	return _b
}
func (i InferredArrayTupleDraft7One) String() string {
	if i._isRaw {
		return string(i._raw)
	}
	return fmt.Sprintf("%v", i._value)
}

// Validate checks InferredArrayTupleDraft7One against its JSON Schema constraints.
func (i InferredArrayTupleDraft7One) Validate() error {
	if i._isRaw {
		return nil // Constraints don't apply to non-matching types.
	}
	// Item-level validation for inferred array.
	for _i, _elem := range i._value {
		_tv, _tvErr := jsonTreeView(_elem)
		if _tvErr != nil {
			return fmt.Errorf("items[%d]: %w", _i, jsonMarshalError(&_elem, _tvErr))
		}
		if _tr := _evalNode(&_etInferredArrayTupleDraft7OneItem, _tv); !_tr.ok {
			return fmt.Errorf("items[%d]: %w", _i, _evalError(_tr))
		}
	}
	return nil
}

// InferredArrayTupleDraft7Ref accepts any JSON value. Constraints apply only when the value is array.
type InferredArrayTupleDraft7Ref struct {
	_value []any
	_raw   json.RawMessage
	_isRaw bool
}

func (i *InferredArrayTupleDraft7Ref) UnmarshalJSON(data []byte) error {
	*i = InferredArrayTupleDraft7Ref{}
	// Null is a non-matching type for inferred schemas — store as raw.
	if string(data) == "null" {
		i._raw = append(json.RawMessage(nil), data...)
		i._isRaw = true
		return nil
	}
	// Try typed unmarshal first.
	if _err := json.Unmarshal(data, &i._value); _err == nil {
		i._isRaw = false
		return nil
	}
	// Non-matching type — store raw bytes, accept silently per JSON Schema. A
	// value that is not JSON at all is not a value of some other type, and is
	// refused in encoding/json's words; encoding/json never hands one over, so
	// only a direct caller reaches that.
	if !json.Valid(data) {
		var _v json.RawMessage
		return jsonDecodeRefusal(json.Unmarshal(data, &_v))
	}
	i._raw = append(json.RawMessage(nil), data...)
	i._isRaw = true
	return nil
}
func (i InferredArrayTupleDraft7Ref) MarshalJSON() ([]byte, error) {
	if i._isRaw {
		if len(i._raw) == 0 {
			return []byte("null"), nil
		}
		// A copy: the value's own bytes, handed out, are bytes a caller can
		// rewrite the value through.
		return append([]byte(nil), i._raw...), nil
	}
	return json.Marshal(i._value)
}
func (i InferredArrayTupleDraft7Ref) Slice() []any  { return i._value }
func (i InferredArrayTupleDraft7Ref) IsArray() bool { return !i._isRaw }
func (i InferredArrayTupleDraft7Ref) Raw() json.RawMessage {
	if i._isRaw {
		return append(json.RawMessage(nil), i._raw...)
	}
	_b, _ := json.Marshal(i._value)
	return _b
}
func (i InferredArrayTupleDraft7Ref) String() string {
	if i._isRaw {
		return string(i._raw)
	}
	return fmt.Sprintf("%v", i._value)
}

// Validate checks InferredArrayTupleDraft7Ref against its JSON Schema constraints.
func (i InferredArrayTupleDraft7Ref) Validate() error {
	if i._isRaw {
		return nil // Constraints don't apply to non-matching types.
	}
	// Item-level validation for inferred array.
	for _i, _elem := range i._value {
		_tv, _tvErr := jsonTreeView(_elem)
		if _tvErr != nil {
			return fmt.Errorf("items[%d]: %w", _i, jsonMarshalError(&_elem, _tvErr))
		}
		if _tr := _evalNode(&_etNeedsA, _tv); !_tr.ok {
			return fmt.Errorf("items[%d]: %w", _i, _evalError(_tr))
		}
	}
	return nil
}

type InferredArrayTupleDraft7TupItem0 struct {
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces i with the value the document holds. See
// decodeJSONAt.
func (i *InferredArrayTupleDraft7TupItem0) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(i.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into i, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever i held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (i *InferredArrayTupleDraft7TupItem0) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*i = InferredArrayTupleDraft7TupItem0{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*InferredArrayTupleDraft7TupItem0)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	i._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		i._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		if i.AdditionalProperties == nil {
			i.AdditionalProperties = make(map[string]json.RawMessage)
		}
		i.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (i InferredArrayTupleDraft7TupItem0) MarshalJSON() ([]byte, error) {
	_b, _err := i.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends i to _b as JSON. See jsonEnc.
func (i InferredArrayTupleDraft7TupItem0) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := i.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range i.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, i.appendMemberJSON)
}

// encodeFieldsJSON gathers the members i's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (i InferredArrayTupleDraft7TupItem0) encodeFieldsJSON(_o *jsonObj) error {
	return nil
}

// appendMemberJSON writes the member of i numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (i InferredArrayTupleDraft7TupItem0) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// jsonIdentity is i's identity as JSON, read off its members by the rules
// appendJSON writes them by. See jsonID.
func (i *InferredArrayTupleDraft7TupItem0) jsonIdentity(_m *jsonValidation) (jsonID, error) {
	_o := jsonIDObj{m: _m}
	for _key, _member := range i.AdditionalProperties {
		_o.idHeld(_key, _member)
	}
	return _o.idOf(i.jsonIdentityMember, _m)
}

// jsonIdentityMember reads the member of i numbered idx, as
// appendMemberJSON writes it. key is the member's key, which names the
// additionalProperties value to read.
func (i *InferredArrayTupleDraft7TupItem0) jsonIdentityMember(_idx int, _key string, _m *jsonValidation) (jsonID, error) {
	_ = _key
	switch _idx {
	}
	return jsonIDNull(_m)
}

// Validate checks InferredArrayTupleDraft7TupItem0 against its JSON Schema constraints.
func (i InferredArrayTupleDraft7TupItem0) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if i._jsonKeys != nil {
		for _, _req := range []string{"a"} {
			if !i._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

type InferredArrayTupleDraft7TupRest struct {
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces i with the value the document holds. See
// decodeJSONAt.
func (i *InferredArrayTupleDraft7TupRest) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(i.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into i, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever i held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (i *InferredArrayTupleDraft7TupRest) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*i = InferredArrayTupleDraft7TupRest{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*InferredArrayTupleDraft7TupRest)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	i._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		i._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		if i.AdditionalProperties == nil {
			i.AdditionalProperties = make(map[string]json.RawMessage)
		}
		i.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (i InferredArrayTupleDraft7TupRest) MarshalJSON() ([]byte, error) {
	_b, _err := i.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends i to _b as JSON. See jsonEnc.
func (i InferredArrayTupleDraft7TupRest) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := i.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range i.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, i.appendMemberJSON)
}

// encodeFieldsJSON gathers the members i's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (i InferredArrayTupleDraft7TupRest) encodeFieldsJSON(_o *jsonObj) error {
	return nil
}

// appendMemberJSON writes the member of i numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (i InferredArrayTupleDraft7TupRest) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// jsonIdentity is i's identity as JSON, read off its members by the rules
// appendJSON writes them by. See jsonID.
func (i *InferredArrayTupleDraft7TupRest) jsonIdentity(_m *jsonValidation) (jsonID, error) {
	_o := jsonIDObj{m: _m}
	for _key, _member := range i.AdditionalProperties {
		_o.idHeld(_key, _member)
	}
	return _o.idOf(i.jsonIdentityMember, _m)
}

// jsonIdentityMember reads the member of i numbered idx, as
// appendMemberJSON writes it. key is the member's key, which names the
// additionalProperties value to read.
func (i *InferredArrayTupleDraft7TupRest) jsonIdentityMember(_idx int, _key string, _m *jsonValidation) (jsonID, error) {
	_ = _key
	switch _idx {
	}
	return jsonIDNull(_m)
}

// Validate checks InferredArrayTupleDraft7TupRest against its JSON Schema constraints.
func (i InferredArrayTupleDraft7TupRest) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if i._jsonKeys != nil {
		for _, _req := range []string{"b"} {
			if !i._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

// InferredArrayTupleDraft7Tup accepts any JSON value. Constraints apply only when the value is array.
type InferredArrayTupleDraft7Tup struct {
	_value []any
	_raw   json.RawMessage
	_isRaw bool
}

func (i *InferredArrayTupleDraft7Tup) UnmarshalJSON(data []byte) error {
	*i = InferredArrayTupleDraft7Tup{}
	// Null is a non-matching type for inferred schemas — store as raw.
	if string(data) == "null" {
		i._raw = append(json.RawMessage(nil), data...)
		i._isRaw = true
		return nil
	}
	// Try typed unmarshal first.
	if _err := json.Unmarshal(data, &i._value); _err == nil {
		i._isRaw = false
		return nil
	}
	// Non-matching type — store raw bytes, accept silently per JSON Schema. A
	// value that is not JSON at all is not a value of some other type, and is
	// refused in encoding/json's words; encoding/json never hands one over, so
	// only a direct caller reaches that.
	if !json.Valid(data) {
		var _v json.RawMessage
		return jsonDecodeRefusal(json.Unmarshal(data, &_v))
	}
	i._raw = append(json.RawMessage(nil), data...)
	i._isRaw = true
	return nil
}
func (i InferredArrayTupleDraft7Tup) MarshalJSON() ([]byte, error) {
	if i._isRaw {
		if len(i._raw) == 0 {
			return []byte("null"), nil
		}
		// A copy: the value's own bytes, handed out, are bytes a caller can
		// rewrite the value through.
		return append([]byte(nil), i._raw...), nil
	}
	return json.Marshal(i._value)
}
func (i InferredArrayTupleDraft7Tup) Slice() []any  { return i._value }
func (i InferredArrayTupleDraft7Tup) IsArray() bool { return !i._isRaw }
func (i InferredArrayTupleDraft7Tup) Raw() json.RawMessage {
	if i._isRaw {
		return append(json.RawMessage(nil), i._raw...)
	}
	_b, _ := json.Marshal(i._value)
	return _b
}
func (i InferredArrayTupleDraft7Tup) String() string {
	if i._isRaw {
		return string(i._raw)
	}
	return fmt.Sprintf("%v", i._value)
}

// Validate checks InferredArrayTupleDraft7Tup against its JSON Schema constraints.
func (i InferredArrayTupleDraft7Tup) Validate() error {
	if i._isRaw {
		return nil // Constraints don't apply to non-matching types.
	}
	// Item-level validation for inferred array.
	{
		if len(i._value) > 0 {
			_tv, _tvErr := jsonTreeView(i._value[0])
			if _tvErr != nil {
				return fmt.Errorf("items[0]: %w", jsonMarshalError(&i._value[0], _tvErr))
			}
			if _tr := _evalNode(&_etInferredArrayTupleDraft7TupItem0, _tv); !_tr.ok {
				return fmt.Errorf("items[0]: %w", _evalError(_tr))
			}
		}
	}
	for _i := 1; _i < len(i._value); _i++ {
		_tv, _tvErr := jsonTreeView(i._value[_i])
		if _tvErr != nil {
			return fmt.Errorf("additionalItems[%d]: %w", _i, jsonMarshalError(&i._value[_i], _tvErr))
		}
		if _tr := _evalNode(&_etInferredArrayTupleDraft7TupRest, _tv); !_tr.ok {
			return fmt.Errorf("additionalItems[%d]: %w", _i, _evalError(_tr))
		}
	}
	return nil
}

// InferredArrayTupleDraft7 - Issue #166 in the tuple spelling drafts 4 to 7 use: `items` as an array of schemas, with `additionalItems` governing everything past it. Both took the same reduction as the 2020-12 prefixItems form -- each position kept its declared JSON type and dropped the rest -- and neither is reachable from a 2020-12 document, so the draft matters.
type InferredArrayTupleDraft7 struct {
	One                  *InferredArrayTupleDraft7One `json:"one,omitempty"`
	Ref                  *InferredArrayTupleDraft7Ref `json:"ref,omitempty"`
	Tup                  *InferredArrayTupleDraft7Tup `json:"tup,omitempty"`
	AdditionalProperties map[string]json.RawMessage   `json:"-"`
	_jsonNulls           map[string]bool              // set by UnmarshalJSON for the properties written as null, which the decoded value cannot hold
}

// UnmarshalJSON replaces i with the value the document holds. See
// decodeJSONAt.
func (i *InferredArrayTupleDraft7) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(i.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into i, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever i held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (i *InferredArrayTupleDraft7) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*i = InferredArrayTupleDraft7{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*InferredArrayTupleDraft7)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["one"]; _ok {
		if _err := func(_p **InferredArrayTupleDraft7One, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*InferredArrayTupleDraft7One](_p, _d, _s, jsonDecodeValue[*InferredArrayTupleDraft7One])
		}(&i.One, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "one")
		}
	}
	if _v, _ok := _raw["ref"]; _ok {
		if _err := func(_p **InferredArrayTupleDraft7Ref, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*InferredArrayTupleDraft7Ref](_p, _d, _s, jsonDecodeValue[*InferredArrayTupleDraft7Ref])
		}(&i.Ref, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "ref")
		}
	}
	if _v, _ok := _raw["tup"]; _ok {
		if _err := func(_p **InferredArrayTupleDraft7Tup, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*InferredArrayTupleDraft7Tup](_p, _d, _s, jsonDecodeValue[*InferredArrayTupleDraft7Tup])
		}(&i.Tup, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "tup")
		}
	}
	// The properties whose schema permits a null. The decode above has
	// already turned one into a nil pointer, a nil collection or an
	// untouched zero -- the same state an absent property leaves -- so the
	// document's own bytes are the only place the difference still exists.
	// Validate reads this to pass over the keywords a null satisfies
	// vacuously, and MarshalJSON to write the null back. See issue #110.
	for _, _nullKey := range []string{
		"one",
		"ref",
		"tup",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			if i._jsonNulls == nil {
				i._jsonNulls = make(map[string]bool, 1)
			}
			i._jsonNulls[_nullKey] = true
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "one", "ref", "tup":
			continue
		}
		if i.AdditionalProperties == nil {
			i.AdditionalProperties = make(map[string]json.RawMessage)
		}
		i.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (i InferredArrayTupleDraft7) MarshalJSON() ([]byte, error) {
	_b, _err := i.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends i to _b as JSON. See jsonEnc.
func (i InferredArrayTupleDraft7) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := i.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	// The properties the source document wrote as null, written back as null
	// where the field still holds what the null left it holding: the member is
	// absent, or reads as the same member of a zero value does. A caller who
	// assigned a value since has said something newer than the document did.
	// See issue #110.
	if len(i._jsonNulls) > 0 {
		var _zero InferredArrayTupleDraft7
		var _zo jsonObj
		if _zero.encodeFieldsJSON(&_zo) == nil {
			for _k := range i._jsonNulls {
				_cur, _present, _err := _o.memberBytes(_k, i.appendMemberJSON)
				if _err != nil {
					return _b, _err
				}
				_zv, _, _zerr := _zo.memberBytes(_k, _zero.appendMemberJSON)
				if _zerr != nil {
					continue
				}
				if !_present || string(_cur) == string(_zv) {
					_o.encoded(_k, []byte("null"))
				}
			}
		}
	}
	for _key, _member := range i.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, i.appendMemberJSON)
}

// encodeFieldsJSON gathers the members i's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (i InferredArrayTupleDraft7) encodeFieldsJSON(_o *jsonObj) error {
	{
		_v, _omit, _err := jsonLeafOmitEmpty(i.One)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("one", _v)
		}
	}
	{
		_v, _omit, _err := jsonLeafOmitEmpty(i.Ref)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("ref", _v)
		}
	}
	{
		_v, _omit, _err := jsonLeafOmitEmpty(i.Tup)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("tup", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of i numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (i InferredArrayTupleDraft7) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks InferredArrayTupleDraft7 against its JSON Schema constraints.
func (i InferredArrayTupleDraft7) Validate() error {
	if i.One != nil {
		if err := i.One.Validate(); err != nil {
			return jsonPathf(err, "one")
		}
	}
	if i.Ref != nil {
		if err := i.Ref.Validate(); err != nil {
			return jsonPathf(err, "ref")
		}
	}
	if i.Tup != nil {
		if err := i.Tup.Validate(); err != nil {
			return jsonPathf(err, "tup")
		}
	}
	return nil
}

// _etInferredArrayTupleDraft7OneItem is the schema of InferredArrayTupleDraft7OneItem, compiled for judging an element held as
// decoded JSON against it.
var _etInferredArrayTupleDraft7OneItem = _schemaNode{
	Required: []string{"a"},
	Type:     []string{"object"},
}

// _etNeedsA is the schema of NeedsA, compiled for judging an element held as
// decoded JSON against it.
var _etNeedsA = _schemaNode{
	Required: []string{"a"},
	Type:     []string{"object"},
}

// _etInferredArrayTupleDraft7TupItem0 is the schema of InferredArrayTupleDraft7TupItem0, compiled for judging an element held as
// decoded JSON against it.
var _etInferredArrayTupleDraft7TupItem0 = _schemaNode{
	Required: []string{"a"},
	Type:     []string{"object"},
}

// _etInferredArrayTupleDraft7TupRest is the schema of InferredArrayTupleDraft7TupRest, compiled for judging an element held as
// decoded JSON against it.
var _etInferredArrayTupleDraft7TupRest = _schemaNode{
	Required: []string{"b"},
	Type:     []string{"object"},
}
