// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
	rt "github.com/mgilbir/schemagen/runtime"
)

// This file needs the runtime module github.com/mgilbir/schemagen/runtime at API
// level 1 or newer. If the compiler reports rt.API1 undefined, the release the
// build resolved is older than the schemagen that generated this file: update it
// with go get github.com/mgilbir/schemagen/runtime@latest.
var _ rt.API1

type NullableArrayItemsRowsItem struct {
	Qty                  *int64                     `json:"qty,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	ID                   string                     `json:"id"`
	_rawNonObject        json.RawMessage            // raw bytes of non-object data for lossless roundtrip
	_nonObject           bool                       // set by UnmarshalJSON when the JSON data is not an object
}

// UnmarshalJSON replaces n with the value the document holds. See
// decodeJSONAt.
func (n *NullableArrayItemsRowsItem) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(n.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks NullableArrayItemsRowsItem as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (n *NullableArrayItemsRowsItem) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into n, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever n held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (n *NullableArrayItemsRowsItem) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*n = NullableArrayItemsRowsItem{}
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if _d.First(_sp) != '{' {
		n._nonObject = true
		n._rawNonObject = _d.Keep(_sp)
		return nil
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*NullableArrayItemsRowsItem)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["id"]; _ok {
		if _err := func(_p *string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[string](_p, _d, _s, rt.DecodeValue[string])
		}(&n.ID, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "id")
		}
	}
	if _v, _ok := _raw["qty"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.IsNull(_v) {
			var _iv *rt.Integer
			if _err := func(_p **rt.Integer, _d *rt.Doc, _s rt.Span) error {
				return rt.ProbeLeaf[*rt.Integer](_p, _d, _s, rt.DecodeValue[*rt.Integer])
			}(&_iv, _d, _v); _err != nil {
				return rt.Pathf(_err, "%s", "qty")
			}
			n.Qty = rt.IntegerPtr(_iv, func(_ix0 rt.Integer) int64 { return int64(_ix0) })
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See rt.NullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"id",
		"qty",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			return rt.Pathf(rt.ValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	n._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		n._jsonKeys[_k] = true
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "id", "qty":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	n.AdditionalProperties = _apFiled

	return nil
}
func (n NullableArrayItemsRowsItem) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes,
	// in a buffer of their own: the value's bytes, handed out, are bytes a
	// caller can rewrite the value through.
	if n._nonObject {
		if len(n._rawNonObject) > 0 {
			return append([]byte(nil), n._rawNonObject...), nil
		}
		return []byte("null"), nil
	}
	_b, _err := n.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends n to _b as JSON. See rt.Enc.
func (n NullableArrayItemsRowsItem) appendJSON(_b []byte) ([]byte, error) {
	if n._nonObject {
		if len(n._rawNonObject) > 0 {
			return rt.AppendLeaf(json.RawMessage(n._rawNonObject), _b)
		}
		return append(_b, "null"...), nil
	}
	var _o rt.Obj
	if _err := n.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range n.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, n.appendMemberJSON)
}

// encodeFieldsJSON gathers the members n's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (n NullableArrayItemsRowsItem) encodeFieldsJSON(_o *rt.Obj) error {
	{
		_v, _omit, _err := rt.LeafOmitEmpty(n.Qty)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("qty", _v)
		}
	}
	{
		_v, _err := rt.AppendLeaf(n.ID, nil)
		if _err != nil {
			return _err
		}
		_o.Encoded("id", _v)
	}
	return nil
}

// appendMemberJSON writes the member of n numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (n NullableArrayItemsRowsItem) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks NullableArrayItemsRowsItem against its JSON Schema constraints.
func (n NullableArrayItemsRowsItem) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if n._nonObject {
		_nonObj := n._rawNonObject
		_ = _nonObj
		{
			jt := rt.RawKind(_nonObj, false)
			_ppTypeOK := false
			if jt == "object" {
				_ppTypeOK = true
			}
			if jt == "null" {
				_ppTypeOK = true
			}
			if !_ppTypeOK {
				return rt.ValueErrorf("value must be one of: object, null")
			}
		}
		return nil
	}
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if n._jsonKeys != nil {
		for _, _req := range []string{"id"} {
			if !n._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

// NullableArrayItems - Regression: a nullable array node ("type":["array","null"]) must still generate a named item struct for object items and preserve scalar element types, rather than collapsing to *[]any. Mirrors the explode/child-table flattening shape.
type NullableArrayItems struct {
	AdditionalProperties map[string]json.RawMessage    `json:"-"`
	_jsonNulls           map[string]bool               // set by UnmarshalJSON for the properties written as null, which the decoded value cannot hold
	Rows                 []*NullableArrayItemsRowsItem `json:"rows,omitzero"`
	Scores               []float64                     `json:"scores,omitzero"`
	Tags                 []*string                     `json:"tags,omitzero"`
}

// UnmarshalJSON replaces n with the value the document holds. See
// decodeJSONAt.
func (n *NullableArrayItems) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := rt.OpenDoc(data)
	if _err != nil {
		return rt.DecodeRefusal(_err)
	}
	return _d.Finish(n.decodeJSONAt(_d, _sp))
}

// SchemagenGenerated marks NullableArrayItems as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (n *NullableArrayItems) SchemagenGenerated() {}

// decodeJSONAt decodes the value at _sp into n, in place, and hands each
// member's value to the member's own type in turn. See rt.Doc.
//
// The value is replaced, not merged into: whatever n held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (n *NullableArrayItems) decodeJSONAt(_d *rt.Doc, _sp rt.Span) error {
	*n = NullableArrayItems{}
	if _d.IsNull(_sp) {
		return rt.ValueErrorf("null is not allowed")
	}
	switch _d.First(_sp) {
	case '{', 'n':
	default:
		return rt.DecodeRefusal(rt.TypeErrorFor(_d, _sp, (*NullableArrayItems)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]rt.Span)
	if _d.First(_sp) == '{' {
		_it := _d.Iter(_sp)
		for {
			_k, _v, _ok := _it.Member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["rows"]; _ok {
		if _err := func(_p *[]*NullableArrayItemsRowsItem, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeSlice[*NullableArrayItemsRowsItem](_p, _d, _s, func(_p **NullableArrayItemsRowsItem, _d *rt.Doc, _s rt.Span) error {
				return rt.DecodeRefusal(func(_p **NullableArrayItemsRowsItem, _d *rt.Doc, _s rt.Span) error {
					if _d.IsNull(_s) {
						*_p = nil
						return nil
					}
					_v := new(NullableArrayItemsRowsItem)
					*_p = _v
					return _v.decodeJSONAt(_d, _s)
				}(_p, _d, _s))
			})
		}(&n.Rows, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "rows")
		}
	}
	if _v, _ok := _raw["scores"]; _ok {
		if _err := func(_p *[]float64, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[[]float64](_p, _d, _s, rt.DecodeItems(rt.DecodeValue[float64]))
		}(&n.Scores, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "scores")
		}
	}
	if _v, _ok := _raw["tags"]; _ok {
		if _err := func(_p *[]*string, _d *rt.Doc, _s rt.Span) error {
			return rt.ProbeLeaf[[]*string](_p, _d, _s, rt.DecodeItems(rt.DecodeValue[*string]))
		}(&n.Tags, _d, _v); _err != nil {
			return rt.Pathf(_err, "%s", "tags")
		}
	}
	if _v, ok := _raw["scores"]; ok {
		if err := rt.CheckNullsAt(_d, _v, &rt.NullRule{Elem: &rt.NullRule{Reject: true}}); err != nil {
			return rt.Pathf(err, "%s", "scores")
		}
	}
	// The properties whose schema permits a null. The decode above has
	// already turned one into a nil pointer, a nil collection or an
	// untouched zero -- the same state an absent property leaves -- so the
	// document's own bytes are the only place the difference still exists.
	// Validate reads this to pass over the keywords a null satisfies
	// vacuously, and MarshalJSON to write the null back. See issue #110.
	for _, _nullKey := range []string{
		"rows",
		"scores",
		"tags",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.IsNull(_v) {
			if n._jsonNulls == nil {
				n._jsonNulls = make(map[string]bool, 1)
			}
			n._jsonNulls[_nullKey] = true
		}
	}
	var _apFiled map[string]json.RawMessage
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "rows", "scores", "tags":
			continue
		}
		if _apFiled == nil {
			_apFiled = make(map[string]json.RawMessage)
		}
		_apFiled[rawKey] = _d.CopyOf(rawVal)
	}
	n.AdditionalProperties = _apFiled

	return nil
}
func (n NullableArrayItems) MarshalJSON() ([]byte, error) {
	_b, _err := n.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends n to _b as JSON. See rt.Enc.
func (n NullableArrayItems) appendJSON(_b []byte) ([]byte, error) {
	var _o rt.Obj
	if _err := n.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	// The properties the source document wrote as null, written back as null
	// where the field still holds what the null left it holding: the member is
	// absent, or reads as the same member of a zero value does. A caller who
	// assigned a value since has said something newer than the document did.
	// See issue #110.
	if len(n._jsonNulls) > 0 {
		var _zero NullableArrayItems
		var _zo rt.Obj
		if _zero.encodeFieldsJSON(&_zo) == nil {
			for _k := range n._jsonNulls {
				_cur, _present, _err := _o.MemberBytes(_k, n.appendMemberJSON)
				if _err != nil {
					return _b, _err
				}
				_zv, _, _zerr := _zo.MemberBytes(_k, _zero.appendMemberJSON)
				if _zerr != nil {
					continue
				}
				if !_present || string(_cur) == string(_zv) {
					_o.Encoded(_k, []byte("null"))
				}
			}
		}
	}
	for _key, _member := range n.AdditionalProperties {
		_o.Held(_key, _member)
	}
	return _o.Write(_b, n.appendMemberJSON)
}

// encodeFieldsJSON gathers the members n's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (n NullableArrayItems) encodeFieldsJSON(_o *rt.Obj) error {
	{
		if !rt.IsZero(n.Rows) {
			_o.Deferred("rows", 0)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitZero(n.Scores)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("scores", _v)
		}
	}
	{
		_v, _omit, _err := rt.LeafOmitZero(n.Tags)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.Encoded("tags", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of n numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (n NullableArrayItems) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	case 0:
		return (func(_v []*NullableArrayItemsRowsItem, _b []byte) ([]byte, error) {
			return rt.EncSlice[[]*NullableArrayItemsRowsItem, *NullableArrayItemsRowsItem](_v, _b, func(_v *NullableArrayItemsRowsItem, _b []byte) ([]byte, error) {
				if _v == nil {
					return append(_b, "null"...), nil
				}
				_out, _err := (*_v).appendJSON(_b)
				if _err != nil {
					return _b, rt.MarshalerErrFor(_err, (*NullableArrayItemsRowsItem)(nil), true)
				}
				return _out, nil
			})
		})(n.Rows, _b)
	}
	return _b, nil
}

// Validate checks NullableArrayItems against its JSON Schema constraints.
func (n NullableArrayItems) Validate() error {
	for _i, _item := range n.Rows {
		if _item == nil {
			continue // a JSON null left no value behind to check
		}
		if err := _item.Validate(); err != nil {
			return rt.Pathf(err, "rows[%d]", _i)
		}
	}
	return nil
}
