// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type NullableArrayItemsRowsItem struct {
	ID                   string                     `json:"id"`
	Qty                  *int64                     `json:"qty,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (n *NullableArrayItemsRowsItem) UnmarshalJSON(data []byte) error {
	type Alias NullableArrayItemsRowsItem
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(n),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"id"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"id":  true,
			"qty": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if n.AdditionalProperties == nil {
				n.AdditionalProperties = make(map[string]json.RawMessage)
			}
			n.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (n NullableArrayItemsRowsItem) MarshalJSON() ([]byte, error) {
	type Alias NullableArrayItemsRowsItem
	aux := struct {
		Alias
	}{
		Alias: (Alias)(n),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range n.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks NullableArrayItemsRowsItem against its JSON Schema constraints.
func (n NullableArrayItemsRowsItem) Validate() error {
	return nil
}

// NullableArrayItems - Regression: a nullable array node ("type":["array","null"]) must still generate a named item struct for object items and preserve scalar element types, rather than collapsing to *[]any. Mirrors the explode/child-table flattening shape.
type NullableArrayItems struct {
	Rows                 []*NullableArrayItemsRowsItem `json:"rows"`
	Scores               []float64                     `json:"scores"`
	Tags                 []*string                     `json:"tags"`
	AdditionalProperties map[string]json.RawMessage    `json:"-"`
}

func (n *NullableArrayItems) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type NullableArrayItems")
	}
	type Alias NullableArrayItems
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(n),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		knownFields := map[string]bool{
			"rows":   true,
			"scores": true,
			"tags":   true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if n.AdditionalProperties == nil {
				n.AdditionalProperties = make(map[string]json.RawMessage)
			}
			n.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (n NullableArrayItems) MarshalJSON() ([]byte, error) {
	type Alias NullableArrayItems
	aux := struct {
		Alias
	}{
		Alias: (Alias)(n),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range n.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks NullableArrayItems against its JSON Schema constraints.
func (n NullableArrayItems) Validate() error {
	for _i, _item := range n.Rows {
		if err := _item.Validate(); err != nil {
			return fmt.Errorf("rows[%d].%w", _i, err)
		}
	}
	return nil
}
