// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type OneOfOptionalConstPOption0Kind string

const (
	OneOfOptionalConstPOption0KindA OneOfOptionalConstPOption0Kind = "a"
)

// Validate checks OneOfOptionalConstPOption0Kind against its JSON Schema constraints.
func (o OneOfOptionalConstPOption0Kind) Validate() error {
	switch o {
	case OneOfOptionalConstPOption0KindA:
		return nil
	default:
		return jsonValueErrorf("invalid OneOfOptionalConstPOption0Kind value: %v", o)
	}
}

type OneOfOptionalConstPOption0 struct {
	Kind                 *OneOfOptionalConstPOption0Kind `json:"kind,omitempty"`
	X                    string                          `json:"x"`
	AdditionalProperties map[string]json.RawMessage      `json:"-"`
	_nonObject           bool                            // set by UnmarshalJSON when the JSON data is not an object
	_rawNonObject        json.RawMessage                 // raw bytes of non-object data for lossless roundtrip
	_jsonKeys            map[string]bool                 // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (o *OneOfOptionalConstPOption0) UnmarshalJSON(data []byte) error {
	o.AdditionalProperties = nil
	o._jsonKeys = nil
	o._nonObject = false
	o._rawNonObject = nil
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if len(data) == 0 || data[0] != '{' {
		o._nonObject = true
		o._rawNonObject = append(o._rawNonObject[:0], data...)
		return nil
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"kind",
			"x",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias OneOfOptionalConstPOption0
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(o),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return jsonDecodeMemberError(data, err, []jsonMemberDecode{
			{"kind", jsonDecodeValue[*OneOfOptionalConstPOption0Kind]},
			{"x", jsonDecodeValue[string]},
		})
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"kind",
			"x",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
			}
		}
		o._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			o._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"kind": true,
			"x":    true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if o.AdditionalProperties == nil {
				o.AdditionalProperties = make(map[string]json.RawMessage)
			}
			o.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (o OneOfOptionalConstPOption0) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes.
	if o._nonObject {
		if len(o._rawNonObject) > 0 {
			return o._rawNonObject, nil
		}
		return []byte("null"), nil
	}
	type Alias OneOfOptionalConstPOption0
	aux := struct {
		Alias
	}{
		Alias: (Alias)(o),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range o.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks OneOfOptionalConstPOption0 against its JSON Schema constraints.
func (o OneOfOptionalConstPOption0) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if o._nonObject {
		return nil
	}
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if o._jsonKeys != nil {
		for _, _req := range []string{"x"} {
			if !o._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	if o.Kind != nil {
		if err := o.Kind.Validate(); err != nil {
			return jsonPathf(err, "kind")
		}
	}
	return nil
}

type OneOfOptionalConstPOption1Kind string

const (
	OneOfOptionalConstPOption1KindB OneOfOptionalConstPOption1Kind = "b"
)

// Validate checks OneOfOptionalConstPOption1Kind against its JSON Schema constraints.
func (o OneOfOptionalConstPOption1Kind) Validate() error {
	switch o {
	case OneOfOptionalConstPOption1KindB:
		return nil
	default:
		return jsonValueErrorf("invalid OneOfOptionalConstPOption1Kind value: %v", o)
	}
}

type OneOfOptionalConstPOption1 struct {
	Kind                 *OneOfOptionalConstPOption1Kind `json:"kind,omitempty"`
	Y                    string                          `json:"y"`
	AdditionalProperties map[string]json.RawMessage      `json:"-"`
	_nonObject           bool                            // set by UnmarshalJSON when the JSON data is not an object
	_rawNonObject        json.RawMessage                 // raw bytes of non-object data for lossless roundtrip
	_jsonKeys            map[string]bool                 // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (o *OneOfOptionalConstPOption1) UnmarshalJSON(data []byte) error {
	o.AdditionalProperties = nil
	o._jsonKeys = nil
	o._nonObject = false
	o._rawNonObject = nil
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if len(data) == 0 || data[0] != '{' {
		o._nonObject = true
		o._rawNonObject = append(o._rawNonObject[:0], data...)
		return nil
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"kind",
			"y",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias OneOfOptionalConstPOption1
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(o),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return jsonDecodeMemberError(data, err, []jsonMemberDecode{
			{"kind", jsonDecodeValue[*OneOfOptionalConstPOption1Kind]},
			{"y", jsonDecodeValue[string]},
		})
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"kind",
			"y",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
			}
		}
		o._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			o._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"kind": true,
			"y":    true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if o.AdditionalProperties == nil {
				o.AdditionalProperties = make(map[string]json.RawMessage)
			}
			o.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (o OneOfOptionalConstPOption1) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes.
	if o._nonObject {
		if len(o._rawNonObject) > 0 {
			return o._rawNonObject, nil
		}
		return []byte("null"), nil
	}
	type Alias OneOfOptionalConstPOption1
	aux := struct {
		Alias
	}{
		Alias: (Alias)(o),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range o.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks OneOfOptionalConstPOption1 against its JSON Schema constraints.
func (o OneOfOptionalConstPOption1) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if o._nonObject {
		return nil
	}
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if o._jsonKeys != nil {
		for _, _req := range []string{"y"} {
			if !o._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	if o.Kind != nil {
		if err := o.Kind.Validate(); err != nil {
			return jsonPathf(err, "kind")
		}
	}
	return nil
}

type OneOfOptionalConst struct {
	P                    isOneOfOptionalConst_P     `json:"-"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonNulls           map[string]bool            // set by UnmarshalJSON for the properties written as null, which the decoded value cannot hold
}

// isOneOfOptionalConst_P is a sealed interface for the P field of OneOfOptionalConst.
// Exactly one variant must be set.
type isOneOfOptionalConst_P interface {
	isOneOfOptionalConst_P()
}

// OneOfOptionalConst_OneOfOptionalConstPOption0 wraps *OneOfOptionalConstPOption0 as a P variant.
type OneOfOptionalConst_OneOfOptionalConstPOption0 struct {
	OneOfOptionalConstPOption0 *OneOfOptionalConstPOption0
}

func (*OneOfOptionalConst_OneOfOptionalConstPOption0) isOneOfOptionalConst_P() {}

// OneOfOptionalConst_OneOfOptionalConstPOption1 wraps *OneOfOptionalConstPOption1 as a P variant.
type OneOfOptionalConst_OneOfOptionalConstPOption1 struct {
	OneOfOptionalConstPOption1 *OneOfOptionalConstPOption1
}

func (*OneOfOptionalConst_OneOfOptionalConstPOption1) isOneOfOptionalConst_P() {}

// GetOneOfOptionalConstPOption0 returns the OneOfOptionalConstPOption0 variant value, or the zero value if not set.
func (o *OneOfOptionalConst) GetOneOfOptionalConstPOption0() *OneOfOptionalConstPOption0 {
	if o != nil {
		if v, ok := o.P.(*OneOfOptionalConst_OneOfOptionalConstPOption0); ok {
			return v.OneOfOptionalConstPOption0
		}
	}
	var zero *OneOfOptionalConstPOption0
	return zero
}

// GetOneOfOptionalConstPOption1 returns the OneOfOptionalConstPOption1 variant value, or the zero value if not set.
func (o *OneOfOptionalConst) GetOneOfOptionalConstPOption1() *OneOfOptionalConstPOption1 {
	if o != nil {
		if v, ok := o.P.(*OneOfOptionalConst_OneOfOptionalConstPOption1); ok {
			return v.OneOfOptionalConstPOption1
		}
	}
	var zero *OneOfOptionalConstPOption1
	return zero
}

func (o *OneOfOptionalConst) UnmarshalJSON(data []byte) error {
	o.AdditionalProperties = nil
	o._jsonNulls = nil
	o.P = nil
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"p",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias OneOfOptionalConst
	aux := &struct {
		*Alias
		P json.RawMessage `json:"p"`
	}{
		Alias: (*Alias)(o),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return jsonDecodeRefusal(err)
	}

	{
		oneofData := aux.P
		if len(oneofData) > 0 && string(oneofData) != "null" {
			var oneofMatched int
			var oneofLastErr error
			// A second tally: branches actually satisfied, not merely decoded.
			// An object branch keeps its constraints inside the variant type, so
			// two branches whose required keys are both present both decode even
			// when only one holds. oneofOpaque counts branches neither this
			// tally nor the checks above can speak for. Read once, below.
			var oneofStrict int
			var oneofOpaque int
			var oneofStrictSel isOneOfOptionalConst_P
			var oneofStrictErr error

			// Try variant: OneOfOptionalConstPOption0
			{
				if oneofHasRequiredFields(oneofData, "x") {
					var candidate *OneOfOptionalConstPOption0
					if err := json.Unmarshal(oneofData, &candidate); err == nil {
						o.P = &OneOfOptionalConst_OneOfOptionalConstPOption0{OneOfOptionalConstPOption0: candidate}
						oneofMatched++
						if candidate != nil {
							if _vErr := candidate.Validate(); _vErr == nil {
								oneofStrict++
								oneofStrictSel = &OneOfOptionalConst_OneOfOptionalConstPOption0{OneOfOptionalConstPOption0: candidate}
							} else {
								oneofStrictErr = fmt.Errorf("variant OneOfOptionalConstPOption0: %w", _vErr)
							}
						} else {
							oneofOpaque++
						}
					} else {
						oneofLastErr = err
					}
				}
			}

			// Try variant: OneOfOptionalConstPOption1
			{
				if oneofHasRequiredFields(oneofData, "y") {
					var candidate *OneOfOptionalConstPOption1
					if err := json.Unmarshal(oneofData, &candidate); err == nil {
						o.P = &OneOfOptionalConst_OneOfOptionalConstPOption1{OneOfOptionalConstPOption1: candidate}
						oneofMatched++
						if candidate != nil {
							if _vErr := candidate.Validate(); _vErr == nil {
								oneofStrict++
								oneofStrictSel = &OneOfOptionalConst_OneOfOptionalConstPOption1{OneOfOptionalConstPOption1: candidate}
							} else {
								oneofStrictErr = fmt.Errorf("variant OneOfOptionalConstPOption1: %w", _vErr)
							}
						} else {
							oneofOpaque++
						}
					} else {
						oneofLastErr = err
					}
				}
			}

			if oneofMatched == 0 {
				return fmt.Errorf("OneOfOptionalConst.P: no matching oneOf variant: %w", oneofLastErr)
			}
			if oneofMatched > 1 && oneofOpaque == 0 {
				// Several branches decoded and every one can be judged, so the
				// branches' own constraints settle which of them the value
				// really satisfies. Ambiguity is already a rejection here, so
				// this can only let through a document the schema allows.
				switch {
				case oneofStrict == 1:
					o.P = oneofStrictSel
					oneofMatched = 1
				case oneofStrict > 1:
					oneofMatched = oneofStrict
				case oneofStrictErr != nil:
					// Not ambiguity but a value no branch accepts: report the
					// branch's own reason rather than a count.
					return fmt.Errorf("OneOfOptionalConst.P: no matching oneOf variant: %w", oneofStrictErr)
				}
			}
			if oneofMatched > 1 {
				return fmt.Errorf("OneOfOptionalConst.P: multiple oneOf variants matched (%d), expected exactly 1", oneofMatched)
			}
		}
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// The properties whose schema permits a null. The decode above has
		// already turned one into a nil pointer, a nil collection or an
		// untouched zero -- the same state an absent property leaves -- so the
		// document's own bytes are the only place the difference still exists.
		// Validate reads this to pass over the keywords a null satisfies
		// vacuously, and MarshalJSON to write the null back. See issue #110.
		for _, _nullKey := range []string{
			"p",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				if o._jsonNulls == nil {
					o._jsonNulls = make(map[string]bool, 1)
				}
				o._jsonNulls[_nullKey] = true
			}
		}
		knownFields := map[string]bool{
			"p": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if o.AdditionalProperties == nil {
				o.AdditionalProperties = make(map[string]json.RawMessage)
			}
			o.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (o OneOfOptionalConst) MarshalJSON() ([]byte, error) {
	type Alias OneOfOptionalConst
	aux := struct {
		Alias
		P json.RawMessage `json:"p,omitempty"`
	}{
		Alias: (Alias)(o),
	}

	if o.P != nil {
		switch v := o.P.(type) {
		case *OneOfOptionalConst_OneOfOptionalConstPOption0:
			raw, err := json.Marshal(v.OneOfOptionalConstPOption0)
			if err != nil {
				return nil, fmt.Errorf("marshaling OneOfOptionalConst.P: %w", err)
			}
			aux.P = raw
		case *OneOfOptionalConst_OneOfOptionalConstPOption1:
			raw, err := json.Marshal(v.OneOfOptionalConstPOption1)
			if err != nil {
				return nil, fmt.Errorf("marshaling OneOfOptionalConst.P: %w", err)
			}
			aux.P = raw
		}
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	// The properties the source document wrote as null. Nothing left in the
	// decoded value says they were there -- a null leaves the nil pointer or the
	// untouched zero an absent property leaves -- so writing them back has to
	// come from the record UnmarshalJSON kept. See issue #110.
	//
	// Only where the field still holds what the null left it holding. A caller
	// who decoded a null and then assigned a value has said something newer than
	// the document did, and writing the null over it would discard the
	// assignment; the record is about a value nobody has touched. What the
	// untouched state looks like is read off a zero of this very struct rather
	// than from a per-field literal, so a field type's own MarshalJSON decides
	// for itself and nothing here has to know how it spells "empty".
	if len(o._jsonNulls) > 0 {
		var _zero Alias
		if _zeroData, _zeroErr := json.Marshal(_zero); _zeroErr == nil {
			var _zeroObj map[string]json.RawMessage
			if json.Unmarshal(_zeroData, &_zeroObj) == nil {
				for _k := range o._jsonNulls {
					if _cur, _present := obj[_k]; !_present || string(_cur) == string(_zeroObj[_k]) {
						obj[_k] = json.RawMessage("null")
					}
				}
			}
		}
	}
	for k, v := range o.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks OneOfOptionalConst against its JSON Schema constraints.
func (o OneOfOptionalConst) Validate() error {
	// oneOf union: the branch selection settled on one variant, whose own type
	// carries that branch's constraints. Nothing else applies them — selection
	// only decides which branch decodes — so the interior of an object variant
	// goes unchecked unless the parent descends here. A variant whose type has
	// no Validate (a scalar, or `any`) is absent from the switch: its branch
	// constraints ride on the selection checks in UnmarshalJSON instead.
	switch _oneOfSel := o.P.(type) {
	case *OneOfOptionalConst_OneOfOptionalConstPOption0:
		if _oneOfSel.OneOfOptionalConstPOption0 != nil {
			if err := _oneOfSel.OneOfOptionalConstPOption0.Validate(); err != nil {
				return jsonPathf(err, "p")
			}
		}
	case *OneOfOptionalConst_OneOfOptionalConstPOption1:
		if _oneOfSel.OneOfOptionalConstPOption1 != nil {
			if err := _oneOfSel.OneOfOptionalConstPOption1.Validate(); err != nil {
				return jsonPathf(err, "p")
			}
		}
	}
	return nil
}
