// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	rt "github.com/mgilbir/schemagen/runtime"
	"unicode/utf8"
)

// This file needs the runtime module github.com/mgilbir/schemagen/runtime at API
// level 1 or newer. If the compiler reports rt.API1 undefined, the release the
// build resolved is older than the schemagen that generated this file: update it
// with go get github.com/mgilbir/schemagen/runtime@latest.
var _ rt.API1

type OneOfStringLengthVariants string

func (o *OneOfStringLengthVariants) UnmarshalJSON(data []byte) error {
	var _zero OneOfStringLengthVariants
	*o = _zero
	if string(data) == "null" {
		return rt.ValueErrorf("null is not allowed")
	}
	type Alias OneOfStringLengthVariants
	return rt.DecodeRefusal(json.Unmarshal(data, (*Alias)(o)))
}

// SchemagenGenerated marks OneOfStringLengthVariants as generated by schemagen, so that its
// UnmarshalJSON is handed bytes the runtime has already checked.
func (o *OneOfStringLengthVariants) SchemagenGenerated() {}

// Validate checks OneOfStringLengthVariants against its JSON Schema constraints.
func (o OneOfStringLengthVariants) Validate() error {
	// oneOf: exactly one variant must be satisfied.
	{
		oneOfCount := 0
		{
			variantValid := true
			if utf8.RuneCountInString(string(o)) < 2 {
				variantValid = false
			}
			if variantValid {
				oneOfCount++
			}
		}
		{
			variantValid := true
			if utf8.RuneCountInString(string(o)) > 4 {
				variantValid = false
			}
			if variantValid {
				oneOfCount++
			}
		}
		if oneOfCount != 1 {
			return rt.ValueErrorf("value matches %d oneOf variants, expected exactly 1", oneOfCount)
		}
	}
	return nil
}
