// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
)

type PropertyCount struct {
	A                    *string                    `json:"a,omitempty"`
	B                    *string                    `json:"b,omitempty"`
	C                    *string                    `json:"c,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

// UnmarshalJSON replaces p with the value the document holds. See
// decodeJSONAt.
func (p *PropertyCount) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(p.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into p, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever p held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (p *PropertyCount) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*p = PropertyCount{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[PropertyCount](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["a"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&p.A, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "a")
		}
	}
	if _v, _ok := _raw["b"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&p.B, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "b")
		}
	}
	if _v, _ok := _raw["c"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&p.C, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "c")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"a",
		"b",
		"c",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	p._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		p._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "a", "b", "c":
			continue
		}
		if p.AdditionalProperties == nil {
			p.AdditionalProperties = make(map[string]json.RawMessage)
		}
		p.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (p PropertyCount) MarshalJSON() ([]byte, error) {
	type Alias PropertyCount
	aux := struct {
		Alias
	}{
		Alias: (Alias)(p),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for _key, _member := range p.AdditionalProperties {
		obj[_key] = _member
	}
	return json.Marshal(obj)
}

// Validate checks PropertyCount against its JSON Schema constraints.
func (p PropertyCount) Validate() error {
	{
		// Count properties actually present in the source JSON. _jsonKeys is
		// populated by UnmarshalJSON; when nil (value not built from JSON) fall
		// back to the overflow map count.
		totalProps := len(p.AdditionalProperties)
		if p._jsonKeys != nil {
			totalProps = len(p._jsonKeys)
		}
		if totalProps > 2 {
			return jsonValueErrorf("too many properties: %d exceeds maximum 2", totalProps)
		}
	}
	{
		totalProps := len(p.AdditionalProperties)
		if p._jsonKeys != nil {
			totalProps = len(p._jsonKeys)
		}
		if totalProps < 1 {
			return jsonValueErrorf("too few properties: %d is less than minimum 1", totalProps)
		}
	}
	return nil
}
