// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
	"unicode/utf8"
)

type Num float64

func (n *Num) UnmarshalJSON(data []byte) error {
	var _zero Num
	*n = _zero
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	type Alias Num
	return jsonDecodeRefusal(json.Unmarshal(data, (*Alias)(n)))
}

// Validate checks Num against its JSON Schema constraints.
func (n Num) Validate() error {
	if float64(n) < 0 {
		return jsonValueErrorf("%v is less than minimum 0", n)
	}
	return nil
}

type QuotedPropertyName struct {
	FooBar               *Num                       `json:"-"`
	MapKey               map[string]int64           `json:"-"`
	PctD                 *string                    `json:"pct%d,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	ArrKey               []string                   `json:"-"`
}

// UnmarshalJSON replaces q with the value the document holds. See
// decodeJSONAt.
func (q *QuotedPropertyName) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(q.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into q, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever q held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (q *QuotedPropertyName) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*q = QuotedPropertyName{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*QuotedPropertyName)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["pct%d"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&q.PctD, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "pct%d")
		}
	}

	// Fields with JSON names that cannot be represented in struct tags. They are
	// decoded after every tagged member, which is the order they have always
	// been refused in.
	if _v, _ok := _raw["arr\"key"]; _ok {
		if _err := jsonAtJSON[[]string](&q.ArrKey, _d, _v); _err != nil {
			return jsonPathf(jsonDecodeRefusal(_err), "%s", "arr\"key")
		}
	}
	if _v, _ok := _raw["foo\"bar"]; _ok {
		if _err := jsonAtJSON[*Num](&q.FooBar, _d, _v); _err != nil {
			return jsonPathf(jsonDecodeRefusal(_err), "%s", "foo\"bar")
		}
	}
	if _v, _ok := _raw["map\"key"]; _ok {
		// Decoded through the shadow for the reason the tagged members are: a
		// property name that cannot go in a struct tag is decoded by hand, but
		// its integers are the same integers.
		var _iv map[string]jsonInteger
		if _err := jsonAtJSON[map[string]jsonInteger](&_iv, _d, _v); _err != nil {
			return jsonPathf(jsonDecodeRefusal(_err), "%s", "map\"key")
		}
		q.MapKey = jsonIntegerMap(_iv, func(_ix0 jsonInteger) int64 { return int64(_ix0) })
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"foo\"bar",
		"pct%d",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	if _v, ok := _raw["arr\"key"]; ok {
		if err := checkJSONNullsAt(_d, _v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
			return jsonPathf(err, "%s", "arr\"key")
		}
	}
	if _v, ok := _raw["map\"key"]; ok {
		if err := checkJSONNullsAt(_d, _v, &jsonNullRule{Reject: true, IsMap: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
			return jsonPathf(err, "%s", "map\"key")
		}
	}
	q._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		q._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "arr\"key", "foo\"bar", "map\"key", "pct%d":
			continue
		}
		if q.AdditionalProperties == nil {
			q.AdditionalProperties = make(map[string]json.RawMessage)
		}
		q.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (q QuotedPropertyName) MarshalJSON() ([]byte, error) {
	_b, _err := q.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends q to _b as JSON. See jsonEnc.
func (q QuotedPropertyName) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := q.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	// The property name cannot go in a struct tag, so omitempty never reaches
	// this field: an absent optional value is skipped by hand.
	if q.ArrKey != nil {
		_v, _err := (jsonAppendLeaf[[]string])(q.ArrKey, nil)
		if _err != nil {
			return _b, fmt.Errorf("marshaling QuotedPropertyName.ArrKey: %w", _err)
		}
		_o.encoded("arr\"key", _v)
	}
	// The property name cannot go in a struct tag, so omitempty never reaches
	// this field: an absent optional value is skipped by hand.
	if q.FooBar != nil {
		_v, _err := (jsonAppendLeaf[*Num])(q.FooBar, nil)
		if _err != nil {
			return _b, fmt.Errorf("marshaling QuotedPropertyName.FooBar: %w", _err)
		}
		_o.encoded("foo\"bar", _v)
	}
	// The property name cannot go in a struct tag, so omitempty never reaches
	// this field: an absent optional value is skipped by hand.
	if q.MapKey != nil {
		_v, _err := (jsonAppendLeaf[map[string]int64])(q.MapKey, nil)
		if _err != nil {
			return _b, fmt.Errorf("marshaling QuotedPropertyName.MapKey: %w", _err)
		}
		_o.encoded("map\"key", _v)
	}
	for _key, _member := range q.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, q.appendMemberJSON)
}

// encodeFieldsJSON gathers the members q's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (q QuotedPropertyName) encodeFieldsJSON(_o *jsonObj) error {
	{
		_v, _omit, _err := jsonLeafOmitEmpty(q.PctD)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("pct%d", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of q numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (q QuotedPropertyName) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	case 1:
		_out, _err := (jsonAppendLeaf[[]string])(q.ArrKey, _b)
		if _err != nil {
			return _b, fmt.Errorf("marshaling QuotedPropertyName.ArrKey: %w", _err)
		}
		return _out, nil
	case 2:
		_out, _err := (jsonAppendLeaf[*Num])(q.FooBar, _b)
		if _err != nil {
			return _b, fmt.Errorf("marshaling QuotedPropertyName.FooBar: %w", _err)
		}
		return _out, nil
	case 3:
		_out, _err := (jsonAppendLeaf[map[string]int64])(q.MapKey, _b)
		if _err != nil {
			return _b, fmt.Errorf("marshaling QuotedPropertyName.MapKey: %w", _err)
		}
		return _out, nil
	}
	return _b, nil
}

// Validate checks QuotedPropertyName against its JSON Schema constraints.
func (q QuotedPropertyName) Validate() error {
	if q._jsonKeys["pct%d"] {
		if q.PctD != nil && utf8.RuneCountInString(*q.PctD) < 1 {
			return fmt.Errorf("pct%%d: length %d is less than minimum 1", utf8.RuneCountInString(*q.PctD))
		}
	}
	if q.FooBar != nil {
		if err := q.FooBar.Validate(); err != nil {
			return jsonPathf(err, "foo\"bar")
		}
	}
	return nil
}
