// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
)

// RootNotObjectShape accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type RootNotObjectShape struct {
	_raw json.RawMessage
}

// UnmarshalJSON replaces r with the value the document holds. See
// decodeJSONAt.
func (r *RootNotObjectShape) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(r.decodeJSONAt(_d, _sp))
}

// decodeJSONAt keeps the value at _sp, replacing whatever r held.
func (r *RootNotObjectShape) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*r = RootNotObjectShape{}
	r._raw = _d.keep(_sp)
	return nil
}

// MarshalJSON writes the value back as the document wrote it.
func (r RootNotObjectShape) MarshalJSON() ([]byte, error) {
	if len(r._raw) == 0 {
		return []byte("null"), nil
	}
	return append([]byte(nil), r._raw...), nil
}

// Raw returns a copy of the value's bytes.
func (r RootNotObjectShape) Raw() json.RawMessage { return append(json.RawMessage(nil), r._raw...) }

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (r RootNotObjectShape) IsZero() bool { return len(r._raw) == 0 }

func (r RootNotObjectShape) String() string { return string(r._raw) }

// RootNotObjectShapeSchema is the schema RootNotObjectShape validates against.
var RootNotObjectShapeSchema = _schemaNode{
	Not: _node(_schemaNode{
		Properties: []_schemaMember{
			{Key: "foo", Node: _schemaNode{
				Type: []string{"string"},
			}},
		},
		Required: []string{"foo"},
		Type:     []string{"object"},
	}),
}

// Validate checks RootNotObjectShape against its JSON Schema constraints.
func (r RootNotObjectShape) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(r._raw) == 0 {
		return nil
	}
	// Read one level at a time (see jsonLazy), as the evaluator asks for each
	// level. Decoded whole, the value was an any the evaluator's checks that
	// compare values -- uniqueItems, const, enum -- read the identity of afresh at
	// every level of a document; read off a document, what one level computes is
	// kept there for the next (see jsonLazy.jsonDocID).
	_v, _err := jsonReadLazily(r._raw)
	if _err != nil {
		// A sentence about the value, joined by the same rule as the verdict
		// below. Structural: the raw bytes came from a decoder that had already
		// accepted them as JSON, so nothing has been seen to reach this.
		return jsonValueErrorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&RootNotObjectShapeSchema, _v); !_res.ok {
		return _evalError(_res)
	}
	return nil
}
