// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type StructReuse struct {
	A                    *int64                     `json:"a,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_nonObject           bool                       // set by UnmarshalJSON when the JSON data is not an object
	_rawNonObject        json.RawMessage            // raw bytes of non-object data for lossless roundtrip
}

func (s *StructReuse) UnmarshalJSON(data []byte) error {
	s.AdditionalProperties = nil
	s._nonObject = false
	s._rawNonObject = nil
	// Schema has no explicit "type":"object" — object constraints are type-conditional.
	// Non-object JSON data is silently accepted; raw bytes are preserved for roundtrip.
	if len(data) == 0 || data[0] != '{' {
		s._nonObject = true
		s._rawNonObject = append(s._rawNonObject[:0], data...)
		return nil
	}
	type Alias StructReuse
	aux := &struct {
		*Alias
		A **jsonInteger `json:"a"`
	}{
		Alias: (*Alias)(s),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	// A number written 1.0 is the integer 1 from draft 6 on, and the shadows
	// above are what let encoding/json see it. Each outer pointer is nil when
	// the property was absent or null, both of which leave the field as it was.
	if aux.A != nil {
		_iv := *aux.A
		s.A = jsonIntegerPtr(_iv, func(_ix0 jsonInteger) int64 { return int64(_ix0) })
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"a",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return fmt.Errorf("%s: null is not allowed", _nullKey)
			}
		}
		knownFields := map[string]bool{
			"a": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if s.AdditionalProperties == nil {
				s.AdditionalProperties = make(map[string]json.RawMessage)
			}
			s.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (s StructReuse) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes.
	if s._nonObject {
		if len(s._rawNonObject) > 0 {
			return s._rawNonObject, nil
		}
		return []byte("null"), nil
	}
	type Alias StructReuse
	aux := struct {
		Alias
	}{
		Alias: (Alias)(s),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range s.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks StructReuse against its JSON Schema constraints.
func (s StructReuse) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if s._nonObject {
		return nil
	}
	return nil
}
