// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
)

type Root struct {
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	P                    []int64                    `json:"p,omitzero"`
	_rawNonObject        json.RawMessage            // raw bytes of non-object data for lossless roundtrip
	_nonObject           bool                       // set by UnmarshalJSON when the JSON data is not an object
}

// UnmarshalJSON replaces r with the value the document holds. See
// decodeJSONAt.
func (r *Root) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(r.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into r, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever r held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (r *Root) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*r = Root{}
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if _d.data[_sp.start] != '{' {
		r._nonObject = true
		r._rawNonObject = _d.keep(_sp)
		return nil
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeError[Root](_d, _sp))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["p"]; _ok {
		// A number written 1.0 is the integer 1 from draft 6 on; the shadow is
		// what lets it through. A null leaves the field as it is.
		if !_d.isNull(_v) {
			var _iv []jsonInteger
			if _err := func(_p *[]jsonInteger, _d *jsonDoc, _s jsonSpan) error {
				return jsonProbeLeaf[[]jsonInteger](_p, _d, _s, jsonDecodeItems(jsonDecodeValue[jsonInteger]))
			}(&_iv, _d, _v); _err != nil {
				return jsonPathf(_err, "%s", "p")
			}
			r.P = jsonIntegerSlice(_iv, func(_ix0 jsonInteger) int64 { return int64(_ix0) })
		}
	}
	if _v, ok := _raw["p"]; ok {
		if err := checkJSONNullsAt(_d, _v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
			return jsonPathf(err, "%s", "p")
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "p":
			continue
		}
		if r.AdditionalProperties == nil {
			r.AdditionalProperties = make(map[string]json.RawMessage)
		}
		r.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (r Root) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes,
	// in a buffer of their own: the value's bytes, handed out, are bytes a
	// caller can rewrite the value through.
	if r._nonObject {
		if len(r._rawNonObject) > 0 {
			return append([]byte(nil), r._rawNonObject...), nil
		}
		return []byte("null"), nil
	}
	_b, _err := r.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends r to _b as JSON. See jsonEnc.
func (r Root) appendJSON(_b []byte) ([]byte, error) {
	if r._nonObject {
		if len(r._rawNonObject) > 0 {
			return jsonAppendLeaf(json.RawMessage(r._rawNonObject), _b)
		}
		return append(_b, "null"...), nil
	}
	var _o jsonObj
	if _err := r.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range r.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, r.appendMemberJSON)
}

// encodeFieldsJSON gathers the members r's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (r Root) encodeFieldsJSON(_o *jsonObj) error {
	{
		_v, _omit, _err := jsonLeafOmitZero(r.P)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("p", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of r numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (r Root) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks Root against its JSON Schema constraints.
func (r Root) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if r._nonObject {
		return nil
	}
	return nil
}
