// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// UnevaluatedItemsCousins accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type UnevaluatedItemsCousins struct {
	_raw json.RawMessage
}

func (u *UnevaluatedItemsCousins) UnmarshalJSON(data []byte) error {
	u._raw = append(u._raw[:0], data...)
	return nil
}

func (u UnevaluatedItemsCousins) MarshalJSON() ([]byte, error) {
	if len(u._raw) == 0 {
		return []byte("null"), nil
	}
	return u._raw, nil
}

func (u UnevaluatedItemsCousins) Raw() json.RawMessage { return u._raw }

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (u UnevaluatedItemsCousins) IsZero() bool { return len(u._raw) == 0 }

func (u UnevaluatedItemsCousins) String() string { return string(u._raw) }

// UnevaluatedItemsCousinsSchema is the schema UnevaluatedItemsCousins validates against.
var UnevaluatedItemsCousinsSchema = _schemaNode{
	AllOf: []_schemaNode{
		_schemaNode{
			PrefixItems: []_schemaNode{
				_schemaNode{Boolean: _boolPtr(true)},
			},
		},
		_schemaNode{
			UnevaluatedItems: _node(_schemaNode{Boolean: _boolPtr(false)}),
		},
	},
}

// Validate checks UnevaluatedItemsCousins against its JSON Schema constraints.
func (u UnevaluatedItemsCousins) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(u._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(u._raw, &_v); _err != nil {
		return fmt.Errorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&UnevaluatedItemsCousinsSchema, _v); !_res.ok {
		if _res.reason == "" {
			return fmt.Errorf("value does not satisfy the schema")
		}
		return fmt.Errorf("%s", _res.reason)
	}
	return nil
}
