// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// UnevaluatedItemsAnyOf accepts any JSON value. Its schema is held as data and interpreted
// at validation time, either because an unevaluatedItems constraint depends on
// which items the applicators evaluate for the value in hand, or because the
// schema gives the value no Go type of its own to hang a check on.
type UnevaluatedItemsAnyOf struct {
	_raw json.RawMessage
}

func (u *UnevaluatedItemsAnyOf) UnmarshalJSON(data []byte) error {
	u._raw = append(u._raw[:0], data...)
	return nil
}

func (u UnevaluatedItemsAnyOf) MarshalJSON() ([]byte, error) {
	if len(u._raw) == 0 {
		return []byte("null"), nil
	}
	return u._raw, nil
}

func (u UnevaluatedItemsAnyOf) Raw() json.RawMessage { return u._raw }

// IsZero reports whether no value was present, so an optional field tagged
// ",omitzero" is omitted when absent rather than marshalled as null.
func (u UnevaluatedItemsAnyOf) IsZero() bool { return len(u._raw) == 0 }

func (u UnevaluatedItemsAnyOf) String() string { return string(u._raw) }

// UnevaluatedItemsAnyOfSchema is the schema UnevaluatedItemsAnyOf validates against.
var UnevaluatedItemsAnyOfSchema = _schemaNode{
	AnyOf: []_schemaNode{
		_schemaNode{
			PrefixItems: []_schemaNode{
				_schemaNode{Boolean: _boolPtr(true)},
				_schemaNode{
					Const: _strPtr("\"bar\""),
				},
			},
		},
		_schemaNode{
			PrefixItems: []_schemaNode{
				_schemaNode{Boolean: _boolPtr(true)},
				_schemaNode{Boolean: _boolPtr(true)},
				_schemaNode{
					Const: _strPtr("\"baz\""),
				},
			},
		},
	},
	PrefixItems: []_schemaNode{
		_schemaNode{
			Const: _strPtr("\"foo\""),
		},
	},
	UnevaluatedItems: _node(_schemaNode{Boolean: _boolPtr(false)}),
}

// Validate checks UnevaluatedItemsAnyOf against its JSON Schema constraints.
func (u UnevaluatedItemsAnyOf) Validate() error {
	// No value was present. A constraint applies to a value that is there; an
	// absent optional property is the parent's business (required), not this
	// type's.
	if len(u._raw) == 0 {
		return nil
	}
	var _v any
	if _err := json.Unmarshal(u._raw, &_v); _err != nil {
		return fmt.Errorf("cannot decode value: %w", _err)
	}
	if _res := _evalNode(&UnevaluatedItemsAnyOfSchema, _v); !_res.ok {
		if _res.reason == "" {
			return fmt.Errorf("value does not satisfy the schema")
		}
		return fmt.Errorf("%s", _res.reason)
	}
	return nil
}
