// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// UnevaluatedItemsCousins accepts any JSON value. Its unevaluatedItems constraint depends on
// which items the schema's applicators evaluate for the value being validated,
// so the schema is held as data and interpreted at validation time.
type UnevaluatedItemsCousins struct {
	_raw json.RawMessage
}

func (u *UnevaluatedItemsCousins) UnmarshalJSON(data []byte) error {
	u._raw = append(u._raw[:0], data...)
	return nil
}

func (u UnevaluatedItemsCousins) MarshalJSON() ([]byte, error) {
	if len(u._raw) == 0 {
		return []byte("null"), nil
	}
	return u._raw, nil
}

func (u UnevaluatedItemsCousins) Raw() json.RawMessage { return u._raw }

func (u UnevaluatedItemsCousins) String() string { return string(u._raw) }

// UnevaluatedItemsCousinsSchema is the schema UnevaluatedItemsCousins validates against.
var UnevaluatedItemsCousinsSchema = _schemaNode{
	AllOf: []_schemaNode{
		_schemaNode{
			PrefixItems: []_schemaNode{
				_schemaNode{Boolean: _boolPtr(true)},
			},
		},
		_schemaNode{
			UnevaluatedItems: _node(_schemaNode{Boolean: _boolPtr(false)}),
		},
	},
}

// Validate checks UnevaluatedItemsCousins against its JSON Schema constraints.
func (u UnevaluatedItemsCousins) Validate() error {
	var _v any
	if _err := json.Unmarshal(u._raw, &_v); _err != nil {
		return fmt.Errorf("cannot decode value: %w", _err)
	}
	if !_evalNode(&UnevaluatedItemsCousinsSchema, _v).ok {
		return fmt.Errorf("value does not satisfy the schema")
	}
	return nil
}
