// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
)

type Base struct {
	X                    *string                    `json:"x,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_rawNonObject        json.RawMessage            // raw bytes of non-object data for lossless roundtrip
	_nonObject           bool                       // set by UnmarshalJSON when the JSON data is not an object
}

// UnmarshalJSON replaces b with the value the document holds. See
// decodeJSONAt.
func (b *Base) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(b.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into b, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever b held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (b *Base) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*b = Base{}
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if _d.data[_sp.start] != '{' {
		b._nonObject = true
		b._rawNonObject = _d.keep(_sp)
		return nil
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*Base)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["x"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&b.X, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "x")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"x",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "x":
			continue
		}
		if b.AdditionalProperties == nil {
			b.AdditionalProperties = make(map[string]json.RawMessage)
		}
		b.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (b Base) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes,
	// in a buffer of their own: the value's bytes, handed out, are bytes a
	// caller can rewrite the value through.
	if b._nonObject {
		if len(b._rawNonObject) > 0 {
			return append([]byte(nil), b._rawNonObject...), nil
		}
		return []byte("null"), nil
	}
	_b, _err := b.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends b to _b as JSON. See jsonEnc.
func (b Base) appendJSON(_b []byte) ([]byte, error) {
	if b._nonObject {
		if len(b._rawNonObject) > 0 {
			return jsonAppendLeaf(json.RawMessage(b._rawNonObject), _b)
		}
		return append(_b, "null"...), nil
	}
	var _o jsonObj
	if _err := b.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range b.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, b.appendMemberJSON)
}

// encodeFieldsJSON gathers the members b's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (b Base) encodeFieldsJSON(_o *jsonObj) error {
	{
		_v, _omit, _err := jsonLeafOmitEmpty(b.X)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("x", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of b numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (b Base) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks Base against its JSON Schema constraints.
func (b Base) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if b._nonObject {
		return nil
	}
	return nil
}

type Inner struct {
	Bar                  *string                    `json:"bar,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_rawNonObject        json.RawMessage            // raw bytes of non-object data for lossless roundtrip
	_nonObject           bool                       // set by UnmarshalJSON when the JSON data is not an object
}

// UnmarshalJSON replaces i with the value the document holds. See
// decodeJSONAt.
func (i *Inner) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(i.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into i, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever i held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (i *Inner) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*i = Inner{}
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if _d.data[_sp.start] != '{' {
		i._nonObject = true
		i._rawNonObject = _d.keep(_sp)
		return nil
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*Inner)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["bar"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&i.Bar, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "bar")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"bar",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "bar":
			continue
		}
		if i.AdditionalProperties == nil {
			i.AdditionalProperties = make(map[string]json.RawMessage)
		}
		i.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (i Inner) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes,
	// in a buffer of their own: the value's bytes, handed out, are bytes a
	// caller can rewrite the value through.
	if i._nonObject {
		if len(i._rawNonObject) > 0 {
			return append([]byte(nil), i._rawNonObject...), nil
		}
		return []byte("null"), nil
	}
	_b, _err := i.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends i to _b as JSON. See jsonEnc.
func (i Inner) appendJSON(_b []byte) ([]byte, error) {
	if i._nonObject {
		if len(i._rawNonObject) > 0 {
			return jsonAppendLeaf(json.RawMessage(i._rawNonObject), _b)
		}
		return append(_b, "null"...), nil
	}
	var _o jsonObj
	if _err := i.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range i.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, i.appendMemberJSON)
}

// encodeFieldsJSON gathers the members i's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (i Inner) encodeFieldsJSON(_o *jsonObj) error {
	{
		_v, _omit, _err := jsonLeafOmitEmpty(i.Bar)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("bar", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of i numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (i Inner) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	}
	return _b, nil
}

// Validate checks Inner against its JSON Schema constraints.
func (i Inner) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if i._nonObject {
		return nil
	}
	return nil
}

type ValidatableFieldFmt struct {
	Foo                  *Inner                     `json:"foo,omitempty"`
	X                    *string                    `json:"x,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonNulls           map[string]bool            // set by UnmarshalJSON for the properties written as null, which the decoded value cannot hold
	_rawNonObject        json.RawMessage            // raw bytes of non-object data for lossless roundtrip
	_nonObject           bool                       // set by UnmarshalJSON when the JSON data is not an object
}

// UnmarshalJSON replaces v with the value the document holds. See
// decodeJSONAt.
func (v *ValidatableFieldFmt) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(v.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into v, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever v held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (v *ValidatableFieldFmt) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*v = ValidatableFieldFmt{}
	// The schema admits a document that is not an object, so object constraints
	// are type-conditional. Non-object JSON data is accepted here and judged by
	// Validate; raw bytes are preserved for roundtrip.
	if _d.data[_sp.start] != '{' {
		v._nonObject = true
		v._rawNonObject = _d.keep(_sp)
		return nil
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*ValidatableFieldFmt)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["foo"]; _ok {
		if _err := func(_p **Inner, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal(func(_p **Inner, _d *jsonDoc, _s jsonSpan) error {
				if _d.isNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(Inner)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&v.Foo, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "foo")
		}
	}
	if _v, _ok := _raw["x"]; _ok {
		if _err := func(_p **string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[*string](_p, _d, _s, jsonDecodeValue[*string])
		}(&v.X, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "x")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"x",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	// The properties whose schema permits a null. The decode above has
	// already turned one into a nil pointer, a nil collection or an
	// untouched zero -- the same state an absent property leaves -- so the
	// document's own bytes are the only place the difference still exists.
	// Validate reads this to pass over the keywords a null satisfies
	// vacuously, and MarshalJSON to write the null back. See issue #110.
	for _, _nullKey := range []string{
		"foo",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			if v._jsonNulls == nil {
				v._jsonNulls = make(map[string]bool, 1)
			}
			v._jsonNulls[_nullKey] = true
		}
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "foo", "x":
			continue
		}
		if v.AdditionalProperties == nil {
			v.AdditionalProperties = make(map[string]json.RawMessage)
		}
		v.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (v ValidatableFieldFmt) MarshalJSON() ([]byte, error) {
	// Non-object data was silently accepted — return the original raw bytes,
	// in a buffer of their own: the value's bytes, handed out, are bytes a
	// caller can rewrite the value through.
	if v._nonObject {
		if len(v._rawNonObject) > 0 {
			return append([]byte(nil), v._rawNonObject...), nil
		}
		return []byte("null"), nil
	}
	_b, _err := v.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends v to _b as JSON. See jsonEnc.
func (v ValidatableFieldFmt) appendJSON(_b []byte) ([]byte, error) {
	if v._nonObject {
		if len(v._rawNonObject) > 0 {
			return jsonAppendLeaf(json.RawMessage(v._rawNonObject), _b)
		}
		return append(_b, "null"...), nil
	}
	var _o jsonObj
	if _err := v.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	// The properties the source document wrote as null, written back as null
	// where the field still holds what the null left it holding: the member is
	// absent, or reads as the same member of a zero value does. A caller who
	// assigned a value since has said something newer than the document did.
	// See issue #110.
	if len(v._jsonNulls) > 0 {
		var _zero ValidatableFieldFmt
		var _zo jsonObj
		if _zero.encodeFieldsJSON(&_zo) == nil {
			for _k := range v._jsonNulls {
				_cur, _present, _err := _o.memberBytes(_k, v.appendMemberJSON)
				if _err != nil {
					return _b, _err
				}
				_zv, _, _zerr := _zo.memberBytes(_k, _zero.appendMemberJSON)
				if _zerr != nil {
					continue
				}
				if !_present || string(_cur) == string(_zv) {
					_o.encoded(_k, []byte("null"))
				}
			}
		}
	}
	for _key, _member := range v.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, v.appendMemberJSON)
}

// encodeFieldsJSON gathers the members v's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (v ValidatableFieldFmt) encodeFieldsJSON(_o *jsonObj) error {
	{
		if !jsonIsEmpty(v.Foo) {
			_o.deferred("foo", 0)
		}
	}
	{
		_v, _omit, _err := jsonLeafOmitEmpty(v.X)
		if _err != nil {
			return _err
		}
		if !_omit {
			_o.encoded("x", _v)
		}
	}
	return nil
}

// appendMemberJSON writes the member of v numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (v ValidatableFieldFmt) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	case 0:
		return (func(_v *Inner, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, jsonMarshalerErrFor(_err, (*Inner)(nil), true)
			}
			return _out, nil
		})(v.Foo, _b)
	}
	return _b, nil
}

// Validate checks ValidatableFieldFmt against its JSON Schema constraints.
func (v ValidatableFieldFmt) Validate() error {
	// Non-object data was silently accepted — validate non-object constraints if any.
	if v._nonObject {
		return nil
	}
	if v.Foo != nil {
		if err := v.Foo.Validate(); err != nil {
			return jsonPathf(err, "foo")
		}
	}
	return nil
}
