// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// TreeNode - A recursive tree structure
type TreeNode struct {
	// Parent node reference
	Parent               *TreeNode                  `json:"parent,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	// Node value
	Value string `json:"value"`
	// Child nodes
	Children []*TreeNode `json:"children,omitzero"`
}

// UnmarshalJSON replaces t with the value the document holds. See
// decodeJSONAt.
func (t *TreeNode) UnmarshalJSON(data []byte) error {
	_d, _sp, _err := jsonOpenDoc(data)
	if _err != nil {
		return jsonDecodeRefusal(_err)
	}
	return _d.finish(t.decodeJSONAt(_d, _sp))
}

// decodeJSONAt decodes the value at _sp into t, in place, and hands each
// member's value to the member's own type in turn. See jsonDoc.
//
// The value is replaced, not merged into: whatever t held before is gone,
// so a value decoded twice is exactly the second document, as one decoded once
// would be. encoding/json's own decode merges -- a member the second document
// leaves out keeps what the first one put there -- and a value that reported one
// document's verdict while holding another's fields is what that left behind.
func (t *TreeNode) decodeJSONAt(_d *jsonDoc, _sp jsonSpan) error {
	*t = TreeNode{}
	if _d.isNull(_sp) {
		return jsonValueErrorf("null is not allowed")
	}
	switch _d.data[_sp.start] {
	case '{', 'n':
	default:
		return jsonDecodeRefusal(jsonTypeErrorFor(_d, _sp, (*TreeNode)(nil)))
	}
	// The object's members, by key. A key is matched exactly: JSON Schema
	// property names are case-sensitive, and "NAME" is not "name" -- it is an
	// additional property, and "name" is absent (issue #245). A key written
	// twice means its last value, as it does everywhere a document is read.
	_raw := make(map[string]jsonSpan)
	if _d.data[_sp.start] == '{' {
		_it := _d.iter(_sp)
		for {
			_k, _v, _ok := _it.member()
			if !_ok {
				break
			}
			_raw[_k] = _v
		}
	}
	if _v, _ok := _raw["children"]; _ok {
		if _err := func(_p *[]*TreeNode, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeSlice[*TreeNode](_p, _d, _s, func(_p **TreeNode, _d *jsonDoc, _s jsonSpan) error {
				return jsonDecodeRefusal(func(_p **TreeNode, _d *jsonDoc, _s jsonSpan) error {
					if _d.isNull(_s) {
						*_p = nil
						return nil
					}
					_v := new(TreeNode)
					*_p = _v
					return _v.decodeJSONAt(_d, _s)
				}(_p, _d, _s))
			})
		}(&t.Children, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "children")
		}
	}
	if _v, _ok := _raw["parent"]; _ok {
		if _err := func(_p **TreeNode, _d *jsonDoc, _s jsonSpan) error {
			return jsonDecodeRefusal(func(_p **TreeNode, _d *jsonDoc, _s jsonSpan) error {
				if _d.isNull(_s) {
					*_p = nil
					return nil
				}
				_v := new(TreeNode)
				*_p = _v
				return _v.decodeJSONAt(_d, _s)
			}(_p, _d, _s))
		}(&t.Parent, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "parent")
		}
	}
	if _v, _ok := _raw["value"]; _ok {
		if _err := func(_p *string, _d *jsonDoc, _s jsonSpan) error {
			return jsonProbeLeaf[string](_p, _d, _s, jsonDecodeValue[string])
		}(&t.Value, _d, _v); _err != nil {
			return jsonPathf(_err, "%s", "value")
		}
	}
	// A property the schema gives a type to may not be written as null. By
	// the time the decode above has run there is nothing left to see: a null
	// leaves a nil pointer, a nil collection, or a scalar at its zero, which
	// is exactly what an absent property leaves, so the verdict has to be
	// taken from the document's own keys. See jsonNullRule for the nested
	// spelling of the same rule.
	for _, _nullKey := range []string{
		"parent",
		"value",
	} {
		if _v, ok := _raw[_nullKey]; ok && _d.isNull(_v) {
			return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
		}
	}
	if _v, ok := _raw["children"]; ok {
		if err := checkJSONNullsAt(_d, _v, &jsonNullRule{Reject: true, Elem: &jsonNullRule{Reject: true}}); err != nil {
			return jsonPathf(err, "%s", "children")
		}
	}
	t._jsonKeys = make(map[string]bool, len(_raw))
	for _k := range _raw {
		t._jsonKeys[_k] = true
	}
	for rawKey, rawVal := range _raw {
		switch rawKey {
		case "children", "parent", "value":
			continue
		}
		if t.AdditionalProperties == nil {
			t.AdditionalProperties = make(map[string]json.RawMessage)
		}
		t.AdditionalProperties[rawKey] = _d.copyOf(rawVal)
	}

	return nil
}
func (t TreeNode) MarshalJSON() ([]byte, error) {
	_b, _err := t.appendJSON(nil)
	if _err != nil {
		return nil, _err
	}
	return _b, nil
}

// appendJSON appends t to _b as JSON. See jsonEnc.
func (t TreeNode) appendJSON(_b []byte) ([]byte, error) {
	var _o jsonObj
	if _err := t.encodeFieldsJSON(&_o); _err != nil {
		return _b, _err
	}
	for _key, _member := range t.AdditionalProperties {
		_o.held(_key, _member)
	}
	return _o.write(_b, t.appendMemberJSON)
}

// encodeFieldsJSON gathers the members t's tagged fields write into _o:
// what encoding/json wrote for them, or, for one holding this package's types,
// the index appendMemberJSON writes it under.
func (t TreeNode) encodeFieldsJSON(_o *jsonObj) error {
	{
		if !jsonIsEmpty(t.Parent) {
			_o.deferred("parent", 0)
		}
	}
	{
		_v, _err := jsonAppendLeaf(t.Value, nil)
		if _err != nil {
			return _err
		}
		_o.encoded("value", _v)
	}
	{
		if !jsonIsZero(t.Children) {
			_o.deferred("children", 2)
		}
	}
	return nil
}

// appendMemberJSON writes the member of t numbered idx: one that holds
// this package's types, which is written straight into the output when its
// turn comes. key is the member's key, which names the additionalProperties
// value to write.
func (t TreeNode) appendMemberJSON(_idx int, _key string, _b []byte) ([]byte, error) {
	_ = _key
	switch _idx {
	case 0:
		return (func(_v *TreeNode, _b []byte) ([]byte, error) {
			if _v == nil {
				return append(_b, "null"...), nil
			}
			_out, _err := (*_v).appendJSON(_b)
			if _err != nil {
				return _b, jsonMarshalerErrFor(_err, (*TreeNode)(nil), true)
			}
			return _out, nil
		})(t.Parent, _b)
	case 2:
		return (func(_v []*TreeNode, _b []byte) ([]byte, error) {
			return jsonEncSlice[[]*TreeNode, *TreeNode](_v, _b, func(_v *TreeNode, _b []byte) ([]byte, error) {
				if _v == nil {
					return append(_b, "null"...), nil
				}
				_out, _err := (*_v).appendJSON(_b)
				if _err != nil {
					return _b, jsonMarshalerErrFor(_err, (*TreeNode)(nil), true)
				}
				return _out, nil
			})
		})(t.Children, _b)
	}
	return _b, nil
}

// Validate checks TreeNode against its JSON Schema constraints.
func (t TreeNode) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if t._jsonKeys != nil {
		for _, _req := range []string{"value"} {
			if !t._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	for _i, _item := range t.Children {
		if _item == nil {
			return fmt.Errorf("children[%d]: null is not allowed", _i)
		}
		if err := _item.Validate(); err != nil {
			return jsonPathf(err, "children[%d]", _i)
		}
	}
	if t.Parent != nil {
		if err := t.Parent.Validate(); err != nil {
			return jsonPathf(err, "parent")
		}
	}
	return nil
}
