// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type Address struct {
	City                 string                     `json:"city"`
	Street               string                     `json:"street"`
	Zip                  *string                    `json:"zip,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (a *Address) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Address")
	}
	type Alias Address
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(a),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		a._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			a._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"city":   true,
			"street": true,
			"zip":    true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if a.AdditionalProperties == nil {
				a.AdditionalProperties = make(map[string]json.RawMessage)
			}
			a.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (a Address) MarshalJSON() ([]byte, error) {
	type Alias Address
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range a.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks Address against its JSON Schema constraints.
func (a Address) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if a._jsonKeys != nil {
		for _, _req := range []string{"city", "street"} {
			if !a._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

type Item struct {
	Name                 string                     `json:"name"`
	Price                float64                    `json:"price"`
	Quantity             int64                      `json:"quantity"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (i *Item) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Item")
	}
	type Alias Item
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(i),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		i._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			i._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"name":     true,
			"price":    true,
			"quantity": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if i.AdditionalProperties == nil {
				i.AdditionalProperties = make(map[string]json.RawMessage)
			}
			i.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (i Item) MarshalJSON() ([]byte, error) {
	type Alias Item
	aux := struct {
		Alias
	}{
		Alias: (Alias)(i),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range i.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks Item against its JSON Schema constraints.
func (i Item) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if i._jsonKeys != nil {
		for _, _req := range []string{"name", "price", "quantity"} {
			if !i._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}

type Order struct {
	BillingAddress       *Address                   `json:"billing_address,omitempty"`
	Items                []Item                     `json:"items"`
	OrderID              string                     `json:"order_id"`
	ShippingAddress      Address                    `json:"shipping_address"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
}

func (o *Order) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type Order")
	}
	type Alias Order
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(o),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		o._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			o._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"billing_address":  true,
			"items":            true,
			"order_id":         true,
			"shipping_address": true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if o.AdditionalProperties == nil {
				o.AdditionalProperties = make(map[string]json.RawMessage)
			}
			o.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (o Order) MarshalJSON() ([]byte, error) {
	type Alias Order
	aux := struct {
		Alias
	}{
		Alias: (Alias)(o),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range o.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks Order against its JSON Schema constraints.
func (o Order) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if o._jsonKeys != nil {
		for _, _req := range []string{"items", "order_id", "shipping_address"} {
			if !o._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	if o.BillingAddress != nil {
		if err := o.BillingAddress.Validate(); err != nil {
			return fmt.Errorf("billing_address.%w", err)
		}
	}
	for _i, _item := range o.Items {
		if err := _item.Validate(); err != nil {
			return fmt.Errorf("items[%d].%w", _i, err)
		}
	}
	if err := o.ShippingAddress.Validate(); err != nil {
		return fmt.Errorf("shipping_address.%w", err)
	}
	return nil
}
