// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
	"math/big"
	"strings"
)

// RootNullBigIntMergedType holds an integer value with arbitrary-precision support (int64 + *big.Int).
type RootNullBigIntMergedType struct {
	_int64    int64
	_bigInt   *big.Int
	_isBigInt bool
}

func (r *RootNullBigIntMergedType) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return fmt.Errorf("null is not allowed for type RootNullBigIntMergedType")
	}
	// Reject JSON strings (e.g., "1").
	if len(data) > 0 && data[0] == '"' {
		return fmt.Errorf("cannot unmarshal string into Go value of type RootNullBigIntMergedType")
	}
	var _n json.Number
	if _err := json.Unmarshal(data, &_n); _err != nil {
		return _err
	}
	// Try int64 first.
	if _i, _iErr := _n.Int64(); _iErr == nil {
		r._int64 = _i
		r._isBigInt = false
		r._bigInt = nil
		return nil
	}
	// Try float with zero fractional part only for float-notation numbers (e.g., 1.0, 1e2).
	_s := _n.String()
	if strings.ContainsAny(_s, ".eE") {
		// Read exactly rather than through float64: see jsonIntegerFromLiteral.
		// The round-trip check this replaces asked float64 whether it had lost
		// anything, which is the one question it cannot answer -- 2^53+1 comes
		// back as 2^53 and round-trips perfectly.
		if _i64, _iOK := jsonIntegerFromLiteral(_s); _iOK {
			r._int64 = _i64
			r._isBigInt = false
			r._bigInt = nil
			return nil
		}
	}
	// Try big.Int for values that overflow int64.
	_bi := new(big.Int)
	// Handle float-format bignums (e.g., 1e100).
	if strings.ContainsAny(_s, ".eE") {
		_bf := new(big.Float)
		if _, _ok := _bf.SetString(_s); _ok {
			if _bf.IsInt() {
				_bf.Int(_bi)
				r._bigInt = _bi
				r._isBigInt = true
				r._int64 = 0
				return nil
			}
		}
		return fmt.Errorf("value %s is not an integer", _s)
	}
	if _, _ok := _bi.SetString(_s, 10); _ok {
		r._bigInt = _bi
		r._isBigInt = true
		r._int64 = 0
		return nil
	}
	return fmt.Errorf("value %s is not a valid integer", _s)
}
func (r RootNullBigIntMergedType) MarshalJSON() ([]byte, error) {
	if r._isBigInt && r._bigInt != nil {
		return []byte(r._bigInt.String()), nil
	}
	return json.Marshal(r._int64)
}
func (r RootNullBigIntMergedType) Int64() int64 { return r._int64 }
func (r RootNullBigIntMergedType) BigInt() *big.Int {
	if r._isBigInt && r._bigInt != nil {
		return r._bigInt
	}
	return big.NewInt(r._int64)
}
func (r RootNullBigIntMergedType) IsBigInt() bool { return r._isBigInt }
func (r RootNullBigIntMergedType) String() string { return r.BigInt().String() }

// Validate checks RootNullBigIntMergedType against its JSON Schema constraints.
func (r RootNullBigIntMergedType) Validate() error {
	return nil
}
