// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

type ArrayTypesMetadataItem struct {
	Key                  string                     `json:"key"`
	Value                string                     `json:"value"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (a *ArrayTypesMetadataItem) UnmarshalJSON(data []byte) error {
	type Alias ArrayTypesMetadataItem
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(a),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		// Check required JSON properties are present (only for JSON objects, not null).
		if raw != nil {
			for _, req := range []string{"key", "value"} {
				if _, ok := raw[req]; !ok {
					return fmt.Errorf("%s: required property is missing", req)
				}
			}
		}
		knownFields := map[string]bool{
			"key":   true,
			"value": true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if a.AdditionalProperties == nil {
				a.AdditionalProperties = make(map[string]json.RawMessage)
			}
			a.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (a ArrayTypesMetadataItem) MarshalJSON() ([]byte, error) {
	type Alias ArrayTypesMetadataItem
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range a.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks ArrayTypesMetadataItem against its JSON Schema constraints.
func (a ArrayTypesMetadataItem) Validate() error {
	return nil
}

type ArrayTypes struct {
	Metadata             *[]ArrayTypesMetadataItem  `json:"metadata,omitempty"`
	Scores               *[]float64                 `json:"scores,omitempty"`
	Tags                 *[]string                  `json:"tags,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

func (a *ArrayTypes) UnmarshalJSON(data []byte) error {
	type Alias ArrayTypes
	aux := &struct {
		*Alias
	}{
		Alias: (*Alias)(a),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}
	{
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return err
		}
		knownFields := map[string]bool{
			"metadata": true,
			"scores":   true,
			"tags":     true,
		}
		for k, v := range raw {
			if knownFields[k] {
				continue
			}
			if a.AdditionalProperties == nil {
				a.AdditionalProperties = make(map[string]json.RawMessage)
			}
			a.AdditionalProperties[k] = v
		}
	}

	return nil
}
func (a ArrayTypes) MarshalJSON() ([]byte, error) {
	type Alias ArrayTypes
	aux := struct {
		Alias
	}{
		Alias: (Alias)(a),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range a.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks ArrayTypes against its JSON Schema constraints.
func (a ArrayTypes) Validate() error {
	return nil
}
