// Code generated by schemagen. DO NOT EDIT.

package testpkg

import (
	"encoding/json"
	"fmt"
)

// Person - A person record
type Person struct {
	Active *bool `json:"active,omitempty"`
	// Age in years
	Age                  *int64                     `json:"age,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
	_jsonKeys            map[string]bool            // set by UnmarshalJSON for optional field / dependentSchemas validation
	// Email address
	Email string `json:"email"`
	// Full name
	Name string `json:"name"`
}

func (p *Person) UnmarshalJSON(data []byte) error {
	p.AdditionalProperties = nil
	p._jsonKeys = nil
	if string(data) == "null" {
		return jsonValueErrorf("null is not allowed")
	}
	// The decode below is handed the document cut down to the properties this
	// schema declares, because encoding/json matches a key that matches no field
	// exactly a second time case-insensitively, and would fill "name" from a
	// "NAME" the schema never gave it. See jsonExactProperties and issue #245.
	//
	// The object is parsed once here and read again by the blocks below, so this
	// costs no parse that was not already being paid. Its error is held rather
	// than returned, so that a document which is not an object is still refused
	// by the decode that always refused it, in the words it always used.
	var raw map[string]json.RawMessage
	_rawErr := json.Unmarshal(data, &raw)
	_decodeData := data
	if _rawErr == nil {
		if _exact := jsonExactProperties(raw,
			"active",
			"age",
			"email",
			"name",
		); _exact != nil {
			_decodeData = _exact
		}
	}
	type Alias Person
	aux := &struct {
		*Alias
		Age **jsonInteger `json:"age"`
	}{
		Alias: (*Alias)(p),
	}

	if err := json.Unmarshal(_decodeData, aux); err != nil {
		return jsonDecodeMemberError(data, err, []jsonMemberDecode{
			{name: "active", decode: jsonDecodeValue[*bool]},
			{name: "age", decode: jsonDecodeValue[*jsonInteger]},
			{name: "email", decode: jsonDecodeValue[string]},
			{name: "name", decode: jsonDecodeValue[string]},
		})
	}

	// A number written 1.0 is the integer 1 from draft 6 on, and the shadows
	// above are what let encoding/json see it. Each outer pointer is nil when
	// the property was absent or null, both of which leave the field as it was.
	if aux.Age != nil {
		_iv := *aux.Age
		p.Age = jsonIntegerPtr(_iv, func(_ix0 jsonInteger) int64 { return int64(_ix0) })
	}
	{
		if _rawErr != nil {
			return _rawErr
		}
		// A property the schema gives a type to may not be written as null. By
		// the time the decode above has run there is nothing left to see: a null
		// leaves a nil pointer, a nil collection, or a scalar at its zero, which
		// is exactly what an absent property leaves, so the verdict has to be
		// taken from the document's own keys. See jsonNullRule for the nested
		// spelling of the same rule.
		for _, _nullKey := range []string{
			"active",
			"age",
			"email",
			"name",
		} {
			if _v, ok := raw[_nullKey]; ok && string(_v) == "null" {
				return jsonPathf(jsonValueErrorf("null is not allowed"), "%s", _nullKey)
			}
		}
		p._jsonKeys = make(map[string]bool, len(raw))
		for _k := range raw {
			p._jsonKeys[_k] = true
		}
		knownFields := map[string]bool{
			"active": true,
			"age":    true,
			"email":  true,
			"name":   true,
		}
		for rawKey, rawVal := range raw {
			if knownFields[rawKey] {
				continue
			}
			if p.AdditionalProperties == nil {
				p.AdditionalProperties = make(map[string]json.RawMessage)
			}
			p.AdditionalProperties[rawKey] = rawVal
		}
	}

	return nil
}
func (p Person) MarshalJSON() ([]byte, error) {
	type Alias Person
	aux := struct {
		Alias
	}{
		Alias: (Alias)(p),
	}
	data, err := json.Marshal(aux)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, err
	}
	for k, v := range p.AdditionalProperties {
		obj[k] = v
	}
	return json.Marshal(obj)
}

// Validate checks Person against its JSON Schema constraints.
func (p Person) Validate() error {
	// Required properties must be present in the source JSON. _jsonKeys is
	// populated by UnmarshalJSON; when nil (the value was not built from JSON)
	// presence is untracked and the check is skipped, consistent with how
	// optional-property validation below treats _jsonKeys.
	if p._jsonKeys != nil {
		for _, _req := range []string{"email", "name"} {
			if !p._jsonKeys[_req] {
				return fmt.Errorf("%s: required property is missing", _req)
			}
		}
	}
	return nil
}
