// Code generated by schemagen. DO NOT EDIT.

package testpkg

// Person - A person record
type Person struct {
	Active bool `json:"active,omitempty"`
	// Age in years
	Age int64 `json:"age,omitempty"`
	// Email address
	Email string `json:"email"`
	// Full name
	Name string `json:"name"`
}
