package schemagen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The message a cross-package $ref gets when the owning package has no Go type
// to import for it.
//
// The behaviour is intended and documented -- README, multi-package notes: "A
// $ref into a node the owning package gives no Go type of its own ... is an
// error rather than a copy ... Reference a $defs entry instead, which is named."
// The message was not. It named the *document*, which had been generated, and
// said it had not been -- while the same run's own output left the generated
// file on disk. And it dropped the fragment, which is the only part of the
// reference that says which node the reader has to go and look at. Issue #310.
//
// Two different causes reach the same refusal and need opposite advice: a node
// the owning package gives no declaration of its own (this file), and a document
// that package never generated at all (pkg/generator's
// TestGenerateFailsWhenForeignTypeWasNotRegistered -- unreachable from the
// command line, where an unlisted document is refused earlier, as an
// unresolvable $ref). One says "reference something named in that document", the
// other says "list that document among the inputs".

// missReproduction writes the two documents of issue #310's reproduction and
// returns the source directory, the output directory, and the arguments that
// reproduce it.
func missReproduction(t *testing.T) (src, out string, args []string) {
	t.Helper()
	src = t.TempDir()
	out = t.TempDir()
	writeFile(t, filepath.Join(src, "t.json"), `{
		"$schema":"https://json-schema.org/draft/2020-12/schema",
		"$id":"https://ex.test/t.json",
		"title":"T","type":"object","properties":{"k":{"type":"string","minLength":3}}}`)
	writeFile(t, filepath.Join(src, "root.json"), `{
		"$schema":"https://json-schema.org/draft/2020-12/schema",
		"$id":"https://ex.test/root.json",
		"title":"Root","type":"object",
		"properties":{"a":{"$ref":"https://ex.test/t.json#/properties/k"}}}`)
	args = []string{
		filepath.Join(src, "t.json"), filepath.Join(src, "root.json"),
		"--schema-package", "https://ex.test/t.json=ex.test/m/tpkg",
		"--schema-package", "https://ex.test/root.json=ex.test/m/rootpkg",
		"--root-name", "t.json=T", "--root-name", "root.json=Root",
		"-o", out,
	}
	return src, out, args
}

// TestCrossPackageMissNamesTheFragmentRatherThanTheDocument is issue #310 read
// back off the command.
func TestCrossPackageMissNamesTheFragmentRatherThanTheDocument(t *testing.T) {
	_, out, args := missReproduction(t)

	err := runGenerateArgs(t, args...)
	if err == nil {
		t.Fatal("expected the run to fail: #/properties/k is a node tpkg gives no Go type of its own")
	}
	msg := err.Error()

	// The fragment is the whole of the problem, and the only part of the
	// reference that locates it. A reference to the same document's root would
	// have generated perfectly well.
	if !strings.Contains(msg, "https://ex.test/t.json#/properties/k") {
		t.Errorf("the message does not name the reference that failed, so there is nothing to go and look at.\n"+
			"got: %s", msg)
	}

	// And the claim it used to make was disproved by the run's own output.
	generated := filepath.Join(out, "tpkg", "t.go")
	body, readErr := os.ReadFile(generated)
	if readErr != nil {
		t.Fatalf("the failing run should still have written %s, which is what makes "+
			"\"not generated by their owning package\" false: %v", generated, readErr)
	}
	if !strings.Contains(string(body), "type T struct {") {
		t.Errorf("%s does not declare T; the premise of this test has moved", generated)
	}
	if strings.Contains(msg, "not generated by their owning package") {
		t.Errorf("the message says t.json was not generated by tpkg, and %s is on disk from this very run "+
			"declaring the type. Say what actually failed: the node the fragment points at has no Go "+
			"declaration.\ngot: %s", generated, msg)
	}

	// The advice has to be the one the README gives for this case.
	for _, want := range []string{"no Go type of its own", "$defs"} {
		if !strings.Contains(msg, want) {
			t.Errorf("the message does not contain %q, so it does not say what to write instead.\ngot: %s", want, msg)
		}
	}
}

// The same reference, against a document that *does* name the node, generates.
// Without this the test above passes for a run that fails for some other reason.
func TestCrossPackageRefToANamedDefinitionGenerates(t *testing.T) {
	src := t.TempDir()
	out := t.TempDir()
	writeFile(t, filepath.Join(src, "t.json"), `{
		"$schema":"https://json-schema.org/draft/2020-12/schema",
		"$id":"https://ex.test/t.json",
		"title":"T","type":"object","properties":{"k":{"$ref":"#/$defs/K"}},
		"$defs":{"K":{"type":"string","minLength":3}}}`)
	writeFile(t, filepath.Join(src, "root.json"), `{
		"$schema":"https://json-schema.org/draft/2020-12/schema",
		"$id":"https://ex.test/root.json",
		"title":"Root","type":"object",
		"properties":{"a":{"$ref":"https://ex.test/t.json#/$defs/K"}}}`)

	if err := runGenerateArgs(t,
		filepath.Join(src, "t.json"), filepath.Join(src, "root.json"),
		"--schema-package", "https://ex.test/t.json=ex.test/m/tpkg",
		"--schema-package", "https://ex.test/root.json=ex.test/m/rootpkg",
		"--root-name", "t.json=T", "--root-name", "root.json=Root",
		"-o", out,
	); err != nil {
		t.Fatalf("a $ref to a named definition of another package's document should generate: %v", err)
	}
	body, err := os.ReadFile(filepath.Join(out, "rootpkg", "root.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), `"ex.test/m/tpkg"`) {
		t.Errorf("rootpkg should import tpkg rather than copy the type:\n%s", body)
	}
}

// TestUsageIsPrintedForUsageErrorsAndNotForTheRest is the other half of #310:
// a message this precise is worth nothing if the flag list scrolls it away.
//
// The line between the two is where the run stops answering questions about the
// command line and starts reading schemas. Both directions are held, because
// silencing usage everywhere is the easy over-correction and it takes the flag
// list away from the errors it is the answer to.
func TestUsageIsPrintedForUsageErrorsAndNotForTheRest(t *testing.T) {
	_, _, missArgs := missReproduction(t)

	for _, tc := range []struct {
		name      string
		args      []string
		wantUsage bool
	}{
		{"an unknown flag", []string{"--no-such-flag"}, true},
		{"no input schemas", nil, true},
		{"two opposite flags", []string{"x.json", "--format-assertion", "--format-annotation"}, true},
		{"a $ref that cannot be imported", missArgs, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			cmd := NewRootCmd()
			buf := new(strings.Builder)
			cmd.SetOut(buf)
			cmd.SetErr(buf)
			cmd.SetArgs(append([]string{"generate"}, tc.args...))
			if err := cmd.Execute(); err == nil {
				t.Fatal("expected this invocation to fail")
			}
			printed := strings.Contains(buf.String(), "Usage:\n  schemagen generate")
			if printed != tc.wantUsage {
				verb := "printed"
				if !printed {
					verb = "did not print"
				}
				t.Errorf("the command %s the flag list, and should have done the opposite.\n"+
					"Usage answers a question about the command line and nothing else; after that point it only "+
					"buries the message that says what happened (issue #310).\ngot:\n%s", verb, buf.String())
			}
		})
	}
}
